### ISSUE TITLE
qvd-client can only connect with connection type local

### ISSUE THREAD

**Issue by smoose-nils** [theqvd/theqvd#24]
Hi,

I seem to have a couple of qvd-clients which will only connect with local connection type. ADSL or modem always fail.

This is what qvd-client.log says:

2014/11/28 16:10:22 3520 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Proxy.pm 174 - Connecting to 10.56.10.80:8443
2014/11/28 16:10:23 3520 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Proxy.pm 181 - Sending auth
2014/11/28 16:10:23 3520 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Proxy.pm 208 - Authentication successful
2014/11/28 16:10:24 3520 WARN /usr/bin/qvd-client 78 - Use of uninitialized value $ENV{"DYLD_LIBRARY_PATH"} in concatenation (.) or string at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Proxy.pm line 418.
2014/11/28 16:10:24 3520 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Frame.pm 685 - Starting folder sharing for /home/christopher
2014/11/28 16:10:24 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:25 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:26 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:27 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:28 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:29 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:30 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:31 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:32 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:33 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:34 3520 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Frame.pm 685 - Starting folder sharing for /media
2014/11/28 16:10:34 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:35 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:36 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:37 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:38 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:39 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:40 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:41 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:42 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.
2014/11/28 16:10:43 3520 ERROR /usr/bin/qvd-client 79 - socket closed unexpectedly: Connection refused at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HTTPC.pm line 120.

waiting for X server to begin accepting connections 
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
out closed=== Opened log file at Fri Nov 28 16:24:13 2014 ====
20141128152413: Starting nxagent
running /usr/bin/xinit /etc/X11/Xsession -- /usr/bin/nxagent :100 -ac -name QVD -display nx/nx,options=/var/run/qvd/nxagent.conf:100

And this is qvd-nxagent.log:

NXAGENT - Version 3.5.0

Copyright (C) 2001, 2011 NoMachine.
See http://www.nomachine.com/ for more information.

Info: Agent running with pid '3799'.
Session: Starting session at 'Fri Nov 28 15:58:09 2014'.
Info: Proxy running in server mode with pid '3799'.
Info: Waiting for connection from any host on port '4100'.
Info: Accepted connection from '10.10.6.11'.
Error: Failure negotiating the session in stage '11'.
Error: Aborting session with 'Unable to open display 'nx/nx,options=/var/run/qvd/nxagent.conf:100''.
Session: Aborting session at 'Fri Nov 28 15:58:10 2014'.
Session: Session aborted at 'Fri Nov 28 15:58:10 2014'.

If I choose local at connection speed, everythings works fine.. Any idea why this is happening?

perl-qvd-client version is 3.4.0-22472

Thanks

**Comment by smoose-nils** [comment]
I made some progress on this. I'm using a loadbalancer (lvs) in front of
two l7-routers. Traffic routed to the first l7-router prevents the
client from using the adsl option. When I disable that router everything
seems to be working like expected again.

But if I understand correctly this shouldn't happen since any l7-router
gets the state from the database and then routes the client to the
correct node? Or is this expected behaviour when on first connection the
client is routed through l7r1 but on a later re-connection the client is
routed through l7r2?

**Comment by salva** [comment]
You are doing it in the recommended way, using a load balancer to distribute the load among all the L7Rs. And yes, once the connection gets to any L7R it should be able to forward the connection to the right node.

You may have some network configuration issue. Probably the virtual machines (or containers) are not reachable from all the nodes but only for that running them.

An easy way to test you can reach all the virtual machines is to telnet to the VMA port, for instance:

    $ telnet 10.0.4.253 3030
    Trying 10.0.4.253...
    Connected to 10.0.4.253.
    Escape character is '^]'.
    GET /vma/ping HTTP/1.1

    HTTP/1.1 200 OK
    Content-Type: application/json-simplerpc
    Content-Length: 7
    
    null

    ^C
    Connection closed by foreign host.

In any case, could you attach the logs for both nodes at the point where the crossed connection fails?

**Comment by smoose-nils** [comment]
Thanks for the feedback. I don't know how but the issue disappeared after rebooting.
