### ISSUE TITLE
QVD sources list

### ISSUE THREAD

**Issue by hbdtech** [theqvd/theqvd#25]
3.4.0 source not available any longer?  I've tried 3.5.0 and it works but will not install perl-qvd-node because of dependencies.

Ign http://theqvd.com QVD-3.4.0/main TranslationIndex
Err http://theqvd.com QVD-3.4.0/main amd64 Packages
  404  Not Found
Err http://theqvd.com QVD-3.4.0/main i386 Packages
  404  Not Found
Ign http://theqvd.com QVD-3.4.0/main Translation-en_US
Ign http://theqvd.com QVD-3.4.0/main Translation-en
W: Failed to fetch http://theqvd.com/packages/ubuntu/dists/QVD-3.4.0/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://theqvd.com/packages/ubuntu/dists/QVD-3.4.0/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by ionstorm66** [comment]
There isn't a 3.4 repo anymore. What dependencies issues are you having?

**Comment by hbdtech** [comment]
I found the instructions for the 3.5.0 repository on the download page but I'm going through the documentation to install and it is based on 3.4.0.  First, is there new admin/install documentation for 3.5.0?  Second while following the 3.4.0 documentation it gets to the place to install perl-qvd-node, I try apt-get install perl-qvd-node and it was saying dependencies were hkd and l7r.  When I tried installing them there were other dependencies.  I tried to run the apt-get install perl-qvd-node today and it says it can't be found now.  I guess I just need to have some instructions on how to install 3.5.0 since the documentation is based on an older version.  Thanks for your help.

**Comment by salva** [comment]
qvd-node was an old dummy package that got finally removed in 3.5.

**Comment by hbdtech** [comment]
So I skip that section in the documentation?  Will there still be a node.conf file?

**Comment by hbdtech** [comment]
Ok so I've tried to setup QVD using the 3.5.0 repository and limping my way through the 3.4.0 install guide.  Does not seem to install correctly.  So, any idea when a new install guide may be available?

**Comment by vatral** [comment]
Hello, could you please paste the exact commands you've executed and their results, as well as the contents of your apt sources?

Thanks!

**Comment by hbdtech** [comment]
I have followed the install guide to this point:
http://docs.theqvd.com/docs/QVDInstallationGuide.html#_installation_2

When I execute:
root@myserver:~# apt-get install perl-qvd-node
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 perl-qvd-node : Depends: perl-qvd-hkd but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

If I execute:
root@myserver~# apt-get install perl-qvd-node perl-qvd-hkd
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 perl-qvd-hkd : Depends: qvd-lxc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

If I execute:
root@qvd:/# apt-get install perl-qvd-node perl-qvd-hkd qvd-lxc
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 qvd-lxc : Depends: qvd-liblxc1 (= 1.0.6-25890) but it is not going to be installed
           Depends: qvd-python3-lxc but it is not going to be installed
           Depends: sysv-rc (>= 2.88dsf-24) but 2.88dsf-13.10ubuntu11.1 is to be installed or
                    file-rc (>= 0.8.16) but it is not installable
E: Unable to correct problems, you have held broken packages.


Below is apt sources:
/etc/apt/sources.list:#
/etc/apt/sources.list:
/etc/apt/sources.list:# deb cdrom:[Ubuntu-Server 12.04.2 LTS _Precise Pangolin_ - Release amd64 (20130214)]/ dists/precise/main/binary-i386/
/etc/apt/sources.list:# deb cdrom:[Ubuntu-Server 12.04.2 LTS _Precise Pangolin_ - Release amd64 (20130214)]/ dists/precise/restricted/binary-i386/
/etc/apt/sources.list:# deb cdrom:[Ubuntu-Server 12.04.2 LTS _Precise Pangolin_ - Release amd64 (20130214)]/ precise main restricted
/etc/apt/sources.list:
/etc/apt/sources.list:#deb cdrom:[Ubuntu-Server 12.04.2 LTS _Precise Pangolin_ - Release amd64 (20130214)]/ dists/precise/main/binary-i386/
/etc/apt/sources.list:#deb cdrom:[Ubuntu-Server 12.04.2 LTS _Precise Pangolin_ - Release amd64 (20130214)]/ dists/precise/restricted/binary-i386/
/etc/apt/sources.list:#deb cdrom:[Ubuntu-Server 12.04.2 LTS _Precise Pangolin_ - Release amd64 (20130214)]/ precise main restricted
/etc/apt/sources.list:
/etc/apt/sources.list:# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
/etc/apt/sources.list:# newer versions of the distribution.
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ precise main restricted
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ precise main restricted
/etc/apt/sources.list:
/etc/apt/sources.list:## Major bug fix updates produced after the final release of the
/etc/apt/sources.list:## distribution.
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ precise-updates main restricted
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ precise-updates main restricted
/etc/apt/sources.list:
/etc/apt/sources.list:## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
/etc/apt/sources.list:## team. Also, please note that software in universe WILL NOT receive any
/etc/apt/sources.list:## review or updates from the Ubuntu security team.
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ precise universe
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ precise universe
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ precise-updates universe
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ precise-updates universe
/etc/apt/sources.list:
/etc/apt/sources.list:## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
/etc/apt/sources.list:## team, and may not be under a free licence. Please satisfy yourself as to
/etc/apt/sources.list:## your rights to use the software. Also, please note that software in
/etc/apt/sources.list:## multiverse WILL NOT receive any review or updates from the Ubuntu
/etc/apt/sources.list:## security team.
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ precise multiverse
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ precise multiverse
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ precise-updates multiverse
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ precise-updates multiverse
/etc/apt/sources.list:
/etc/apt/sources.list:## N.B. software from this repository may not have been tested as
/etc/apt/sources.list:## extensively as that contained in the main release, although it includes
/etc/apt/sources.list:## newer versions of some applications which may provide useful features.
/etc/apt/sources.list:## Also, please note that software in backports WILL NOT receive any review
/etc/apt/sources.list:## or updates from the Ubuntu security team.
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ precise-backports main restricted universe multiverse
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ precise-backports main restricted universe multiverse
/etc/apt/sources.list:
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu precise-security main restricted
/etc/apt/sources.list:deb-src http://security.ubuntu.com/ubuntu precise-security main restricted
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu precise-security universe
/etc/apt/sources.list:deb-src http://security.ubuntu.com/ubuntu precise-security universe
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu precise-security multiverse
/etc/apt/sources.list:deb-src http://security.ubuntu.com/ubuntu precise-security multiverse
/etc/apt/sources.list:
/etc/apt/sources.list:## Uncomment the following two lines to add software from Canonical's
/etc/apt/sources.list:## 'partner' repository.
/etc/apt/sources.list:## This software is not part of Ubuntu, but is offered by Canonical and the
/etc/apt/sources.list:## respective vendors as a service to Ubuntu users.
/etc/apt/sources.list:# deb http://archive.canonical.com/ubuntu precise partner
/etc/apt/sources.list:# deb-src http://archive.canonical.com/ubuntu precise partner
/etc/apt/sources.list:
/etc/apt/sources.list:## Uncomment the following two lines to add software from Ubuntu's
/etc/apt/sources.list:## 'extras' repository.
/etc/apt/sources.list:## This software is not part of Ubuntu, but is offered by third-party
/etc/apt/sources.list:## developers who want to ship their latest software.
/etc/apt/sources.list:# deb http://extras.ubuntu.com/ubuntu precise main
/etc/apt/sources.list:# deb-src http://extras.ubuntu.com/ubuntu precise main
/etc/apt/sources.list.d/qvd-35.list:deb http://theqvd.com/packages/ubuntu QVD-3.5.0 main

**Comment by hbdtech** [comment]
Any help?  Has anyone had success building a QVD server with 3.5.0 repository?

**Comment by vatral** [comment]
Hello,

I will have to setup a test environment to take a closer look at that. What distribution are you using?

Thanks!

**Comment by vatral** [comment]
Also, we will be publishing an updated installation guide somewhere in the next two weeks.

**Comment by hbdtech** [comment]
Server is Ubuntu 12.04.  Thanks an updated guide would be helpful.

**Comment by nitomartinez** [comment]
I would recommed using 14.04 if you can. You will find less issues with 14.04

**Comment by hbdtech** [comment]
Install guide updated to 3.5.0.  Thanks
