### ISSUE TITLE
Demo DI will not start

### ISSUE THREAD

**Issue by hbdtech** [theqvd/theqvd#26]
After finally getting 3.5.0 installed and qvd-hkd running I downloaded QVD Demonstration DI (Ubuntu 13.04 – Xfce Desktop for KVM).  Added the OSF, DI, User and created the VM.  Now when trying to start the VM it remains in the stopped state.  Below is the qvd.log file.  Any idea what's wrong?

2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 256 - Notification for channel 'qvd_cmd_for_vm_on_host5' received
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 517 - aborting/cleaning delayed method call
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from load_stop_cmds succeeded
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from load_start_cmds succeeded
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2015/08/06 19:33:44 2208 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 622 - Command 'start' received for vm '1'
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 632 - Creating VM handler agent
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 54 - Using hypervisor type 'kvm'
2015/08/06 19:33:44 2208 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 70 - Command start received by vm 1
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from load_row succeeded
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 147 - Searching DIs with tag 'default' for OSF '1'
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from search_di succeeded
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 32 - Allocating port '2002'
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 165 - Saving runtime row for VM '1': VMA port '3030', X11 port '4100', SSH port '22', VNC port '0', serial port '2002', monitor port '0'
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 217 - No action performed for on_result callback
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from save_runtime_row succeeded
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 135 - Increasing run attempts counter for VM '1'
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 217 - No action performed for on_result callback
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from incr_run_attempts succeeded
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 249 - Retrieving list of ebtables entries for chain 'INPUT'
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 262 - deleting ebtables chain QVD_1_INPUT
2015/08/06 19:33:44 2208 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 265 - Unable to delete chain 'QVD_1_INPUT', rc: 16711680
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 249 - Retrieving list of ebtables entries for chain 'FORWARD'
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 262 - deleting ebtables chain QVD_1_FORWARD
2015/08/06 19:33:44 2208 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 265 - Unable to delete chain 'QVD_1_FORWARD', rc: 16711680
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: 0, ignore_errors: <undef>, cb: _on_done)
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/KVM.pm 233 - mkdir 'overlays_dir' failed: File exists
2015/08/06 19:33:44 2208 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 302 - Running command ['kvm-img','create','-f','qcow2','-b','/var/lib/qvd/storage/images/1-ubuntu-13.04-qvd34.qcow2','/var/lib/qvd/storage/overlays/1$
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 315 - Process 2284 forked
2015/08/06 19:33:44 2208 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 336 - Process 2284 returned rc: 32256, it probably means that the binary was not found
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: 1, ignore_errors: <undef>, cb: _on_error)
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 83 - Changing database state to 'stopping' for VM 1
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 217 - No action performed for on_result callback
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from save_state succeeded
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: 0, ignore_errors: <undef>, cb: _on_done)
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 249 - Retrieving list of ebtables entries for chain 'INPUT'
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 262 - deleting ebtables chain QVD_1_INPUT
2015/08/06 19:33:44 2208 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 265 - Unable to delete chain 'QVD_1_INPUT', rc: 16711680
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 249 - Retrieving list of ebtables entries for chain 'FORWARD'
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 262 - deleting ebtables chain QVD_1_FORWARD
2015/08/06 19:33:44 2208 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 265 - Unable to delete chain 'QVD_1_FORWARD', rc: 16711680
2015/08/06 19:33:44 2208 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/DHCPDHandler.pm 55 - Unregistering mac '', ip '' for VM 1 in DHCP
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/DHCPDHandler.pm 64 - Writing DHCP hosts file '/var/run/qvd/dhcp-hostsfile'
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/DHCPDHandler.pm 75 - Sending HUP signal to dhcpd
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 377 - killing 2231 with signal HUP
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 383 - Clearing runtime row for VM '1'
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 217 - No action performed for on_result callback
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from clear_runtime_row succeeded
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2015/08/06 19:33:44 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 671 - Releasing handler for VM '1'
2015/08/06 19:33:52 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 517 - aborting/cleaning delayed method call
2015/08/06 19:33:52 2208 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Ticker.pm 49 - Ticking
2015/08/06 19:33:52 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 517 - aborting/cleaning delayed method call
2015/08/06 19:33:52 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from load_cmd succeeded
2015/08/06 19:33:52 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2015/08/06 19:33:52 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 223 - unexpected number of rows on query result, 1 expected, 0 received
2015/08/06 19:33:52 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 232 - query set to failed
2015/08/06 19:33:52 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from delete_cmd failed
2015/08/06 19:33:52 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: 1, ignore_errors: <undef>, cb: _on_error)
2015/08/06 19:33:52 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Ticker.pm 57 - Ticking ok at 1438904032.22429 (localtime: 1438904032)
2015/08/06 19:33:52 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from tick succeeded
2015/08/06 19:33:52 2208 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)

QA Config:

admin.ssh.opt.StrictHostKeyChecking=no
admin.ssh.opt.UserKnownHostsFile=/dev/null
client.audio.enable=
client.darwin.screen_resolution.low_res_geometry=800x600
client.darwin.screen_resolution.min=1440x900
client.darwin.screen_resolution.verified=0
client.fullscreen=
client.geometry=1024x768
client.host.name=
client.host.port=8443
client.link=adsl
client.locale=
client.nxagent.extra_args=
client.nxproxy.extra_args=
client.printing.enable=
client.remember_password=0
client.remember_username=1
client.show.remember_password=0
client.show.settings=0
client.slave.client=bin/qvd-slaveclient
client.slave.command=
client.slave.enable=1
client.sshfs.extra_args=-o atomic_o_trunc -o idmap=user
client.ssl.use_cert=0
client.usb.enable=0
client.usb.share_all=0
client.usb.share_list=
client.use_ssl=1
client.user.name=
command.brctl=/sbin/brctl
command.btrfs=/sbin/btrfs
command.darwin.nxproxy=bin/nxproxy
command.darwin.pulseaudio=bin/pulseaudio
command.darwin.sftp-server=/usr/libexec/sftp-server
command.darwin.x11=XQuartz.app
command.dhcpd=/usr/sbin/dnsmasq
command.ebtables=ebtables
command.groupadd=/usr/sbin/groupadd
command.groupdel=/usr/sbin/groupdel
command.ifconfig=/sbin/ifconfig
command.ip=/sbin/ip
command.iptables=iptables
command.kvm=kvm
command.kvm-img=kvm-img
command.lxc-console=/usr/lib/qvd/bin/lxc-console
command.lxc-create=/usr/lib/qvd/bin/lxc-create
command.lxc-destroy=/usr/lib/qvd/bin/lxc-destroy
command.lxc-start=/usr/lib/qvd/bin/lxc-start
command.lxc-stop=/usr/lib/qvd/bin/lxc-stop
command.lxc-wait=/usr/lib/qvd/bin/lxc-wait
command.modprobe=/sbin/modprobe
command.mount=mount
command.nxagent=/usr/bin/nxagent
command.nxagent.args.extra=
command.nxdiag=/usr/lib/qvd/bin/nxdiag.pl
command.nxproxy=/usr/bin/nxproxy
command.open_file=/usr/bin/xdg-open
command.qvd-l7r-slave=/usr/lib/qvd/bin/qvd-l7r-slave
command.qvd-lxc-autodev=/usr/lib/qvd/bin/qvd-lxc-autodev
command.rm=rm
command.sftp-server=/usr/lib/openssh/sftp-server
command.slaveclient=/usr/lib/qvd/bin/qvd-slaveclient
command.sshfs=/usr/lib/qvd/bin/sshfs
command.tar=tar
command.umount=umount
command.unionfs-fuse=/usr/lib/qvd/bin/unionfs
command.usbclnt=/usr/local/bin/usbclnt
command.usbsrv=/usr/local/bin/usbsrv
command.useradd=/usr/sbin/useradd
command.userdel=/usr/sbin/userdel
command.version.lxc=0.7
command.windows.nxproxy=nx\nxproxy.exe
command.windows.pulseaudio=pulseaudio\pulseaudio.exe
command.windows.sftp-server=bin/sftp-server.exe
command.windows.xming=Xming\Xming.exe
command.x-session=/etc/X11/Xsession
command.x-session.args.extra=
command.x11vnc=/usr/bin/x11vnc
command.xhost=/usr/bin/xhost
command.xinit=/usr/bin/xinit
database.host=QVD
database.name=qvddb
database.password=**********
database.user=qvd
hkd.as_user=root
hkd.pid_file=/var/run/qvd/qvd-hkd.pid
hkd.user.umask=0022
hkd.vm.starting.max=6
l7r.address=*
l7r.as_user=root
l7r.auth.plugin.default.salt=qvd1234
l7r.auth.plugins=default
l7r.client.cert.require=0
l7r.loadbalancer.plugin=default
l7r.loadbalancer.plugin.default.weight.cpu=1
l7r.loadbalancer.plugin.default.weight.ram=1
l7r.loadbalancer.plugin.default.weight.random=1
l7r.pid_file=/var/run/qvd/qvd-l7r.pid
l7r.port=8443
l7r.use_ssl=1
l7r.user.umask=0022
log.filename=/var/log/qvd/qvd.log
log.level=DEBUG
model.user.login.case-sensitive=0
nodename=QVD
osf.default.memory=256
osf.default.overlay=1
path.cgroup=/sys/fs/cgroup
path.cgroup.cpu.lxc=/sys/fs/cgroup/cpu/lxc
path.client.pixmaps=pixmaps
path.client.pixmaps.alt=/usr/share/pixmaps
path.darwin.ssl.ca.system=/System/Library/OpenSSL/certs/
path.hypervisor.captures=/var/tmp/qvd/qvd
path.l7r.ssl=/var/run/qvd/l7r/ssl
path.l7r.ssl.ca=/var/run/qvd/l7r/ssl/ca.pem
path.l7r.ssl.cert=/var/run/qvd/l7r/ssl/cert.pem
path.l7r.ssl.crl=/var/run/qvd/l7r/ssl/crl.pem
path.l7r.ssl.key=/var/run/qvd/l7r/ssl/key.pem
path.log=/var/log/qvd
path.qvd.bin=/usr/lib/qvd/bin
path.run=/var/run/qvd
path.run.lxc=/var/run/qvd/lxc
path.serial.captures=/var/tmp/qvd/qvd
path.ssl.ca.personal=certs
path.ssl.ca.system=/etc/ssl/certs
path.storage.basefs=/var/lib/qvd/storage/basefs
path.storage.btrfs.root=/var/lib/qvd/storage
path.storage.check=/var/lib/qvd/storage/homes/.rw_check
path.storage.homefs=/var/lib/qvd/storage/homefs
path.storage.homes=/var/lib/qvd/storage/homes
path.storage.images=/var/lib/qvd/storage/images
path.storage.overlayfs=/var/lib/qvd/storage/overlayfs
path.storage.overlays=/var/lib/qvd/storage/overlays
path.storage.root=/var/lib/qvd/storage
path.storage.rootfs=/var/lib/qvd/storage/rootfs
path.storage.staging=/var/lib/qvd/storage/staging
path.tmp=/var/tmp/qvd
vm.hypervisor=kvm
vm.hypervisor.capture=0
vm.kvm.home.drive.index=1
vm.kvm.virtio=1
vm.lxc.home.per.user=0
vm.lxc.unionfs.bind.ro=1
vm.lxc.unionfs.type=overlayfs
vm.network.bridge=qvdnet
vm.network.dns_server=10.3.15.254
vm.network.domain=
vm.network.firewall.nat.iface=
vm.network.gateway=10.3.15.1
vm.network.ip.start=10.3.15.50
vm.network.mac.prefix=54:52:00
vm.network.netmask=24
vm.network.use_dhcp=1
vm.overlay.persistent=0
vm.serial.capture=0
vm.serial.redirect=1
vm.vnc.opts=
vm.vnc.redirect=0
vma.audio.enable=0
vma.default.client.keyboard=pc105/en
vma.default.client.link=adsl
vma.default.lang=en_US.UTF-8
vma.on_action.connect=
vma.on_action.disconnect=
vma.on_action.expire=
vma.on_action.poweroff=
vma.on_action.pre-connect=
vma.on_action.stop=
vma.on_action.suspend=
vma.on_provisioning.add_user=
vma.on_provisioning.after_add_user=
vma.on_provisioning.mount_home=
vma.on_state.connected=
vma.on_state.disconnected=
vma.on_state.suspended=
vma.pid_file=/var/run/qvd/vma.pid
vma.printing.enable=0
vma.slave.command=/usr/lib/qvd/bin/qvd-vma-slaveserver
vma.slave.enable=0
vma.user.default.groups=
vma.user.default.name=qvd
vma.user.home.drive=/dev/vdb
vma.user.home.fs=ext4
vma.user.home.path=/home
vma.user.shell=/bin/bash
vma.user.umask=0022
wat.admin.login=admin
wat.admin.password=**********
wat.log.filename=/var/log/qvd/qvd-wat.log

**Comment by nitomartinez** [comment]
Hi hdbtech,

thanks for trying QVD. Could you run the following?

which kvm-img
which qemu-img

In case you don't get a response for the first command but yes to the second try the following:

qa config set command.kvm-img=qemu-img

Restart the daemon, and try again.

Please let us know the result.

**Comment by hbdtech** [comment]
Thanks that worked.  Could you give me info as to why this has to be changed?  Did not see anything referenced in the install guide about this setting.

**Comment by nitomartinez** [comment]
Looks like a bug in the Defaults.pm from QVD::Config::Core
kvm-img was the command in Ubuntu 12.04

In 14.04 it is qemu-img

Leaving the ticket open until it is resolved.

**Comment by narenas** [comment]
Hi could you show me the output from the command

'dpkg -l |grep -i qvd“  

Also, could you try inside the vm to do a symlink 

ln -s /usr/share/nx/ /usr/local/lib/nx 
and try to connect again? . 
Regards.

**Comment by hbdtech** [comment]
I'm guessing you meant to put this under issue 27 instead of here?  Copied it to issue 27.

**Comment by salva** [comment]
This issue is solved in the latest releases of QVD. Closing.
