### ISSUE TITLE
QVD Mononode setup help

### ISSUE THREAD

**Issue by rolohaun** [theqvd/theqvd#30]
I am having issues with my mononode qvd install. I am running ubuntu 14.04

I get an error in the log that says IP address 192.168.1.0 not configured on node

My network setup is

QVD server static ip 192.168.0.2

my bridge is setup in the interfaces file
auto qvdnet
iface qvdnet inet static
  pre-up brctl addbr qvdnet
  pre-up iptables -t nat -A POSTROUTING -o eth0 -j SNAT --to-source 192.168.0.2
  pre-up iptables -t nat -A PREROUTING -d 192.168.0.2 -p tcp --dport 8443 -j DNAT --to-destination 192.168.1.3
  post-down brctl delbr qvdnet0
  address 192.168.1.3
  netmask 255.255.255.0

I have my node setup as localhost 192.168.1.0

I can not get my node to start, any help would be appreciated

**Comment by sirishkalidindi** [comment]
Hi ,
what’s the ip of the node ?

**Comment by sirishkalidindi** [comment]
create a new node and the ip should be 192.168.1.3 that should work!

**Comment by rolohaun** [comment]
I have tried that too and then I get the error my host is out of the range for hosts 192.168.1.0 - 192.168.1.3. 

I wonder if I shoud set my VM start ip to 192.168.1.4 and that will solve my issue? I think my host ip is overlapping my vm start ip?

**Comment by narenas** [comment]
Hi rolohaum, 

Could you paste the output of the command following commands? . 

qa config get 
qa host list 
ifconfig -a  

Also i would like to see your /etc/qvd/node.conf file. 

Regards.

**Comment by rolohaun** [comment]
qa config get 

admin.ssh.opt.StrictHostKeyChecking=no
admin.ssh.opt.UserKnownHostsFile=/dev/null
client.audio.enable=
client.darwin.screen_resolution.low_res_geometry=800x600
client.darwin.screen_resolution.min=1440x900
client.darwin.screen_resolution.verified=0
client.fullscreen=
client.geometry=1024x768
client.host.name=
client.host.port=8443
client.link=adsl
client.locale=
client.nxagent.extra_args=
client.nxproxy.extra_args=
client.printing.enable=
client.remember_password=0
client.remember_username=1
client.show.remember_password=0
client.show.settings=0
client.slave.client=bin/qvd-slaveclient
client.slave.command=
client.slave.enable=1
client.sshfs.extra_args=-o atomic_o_trunc -o idmap=user
client.ssl.use_cert=0
client.usb.enable=0
client.usb.share_all=0
client.usb.share_list=
client.use_ssl=1
client.user.name=
command.brctl=/sbin/brctl
command.btrfs=/sbin/btrfs
command.darwin.nxproxy=bin/nxproxy
command.darwin.pulseaudio=bin/pulseaudio
command.darwin.sftp-server=/usr/libexec/sftp-server
command.darwin.x11=XQuartz.app
command.dhcpd=/usr/sbin/dnsmasq
command.ebtables=ebtables
command.groupadd=/usr/sbin/groupadd
command.groupdel=/usr/sbin/groupdel
command.ifconfig=/sbin/ifconfig
command.ip=/sbin/ip
command.iptables=iptables
command.kvm=kvm
command.kvm-img=qemu-img
command.lxc-console=/usr/lib/qvd/bin/lxc-console
command.lxc-create=/usr/lib/qvd/bin/lxc-create
command.lxc-destroy=/usr/lib/qvd/bin/lxc-destroy
command.lxc-start=/usr/lib/qvd/bin/lxc-start
command.lxc-stop=/usr/lib/qvd/bin/lxc-stop
command.lxc-wait=/usr/lib/qvd/bin/lxc-wait
command.modprobe=/sbin/modprobe
command.mount=mount
command.nxagent=/usr/bin/nxagent
command.nxagent.args.extra=
command.nxdiag=/usr/lib/qvd/bin/nxdiag.pl
command.nxproxy=/usr/bin/nxproxy
command.open_file=/usr/bin/xdg-open
command.qvd-l7r-slave=/usr/lib/qvd/bin/qvd-l7r-slave
command.qvd-lxc-autodev=/usr/lib/qvd/bin/qvd-lxc-autodev
command.rm=rm
command.sftp-server=/usr/lib/openssh/sftp-server
command.slaveclient=/usr/lib/qvd/bin/qvd-slaveclient
command.sshfs=/usr/lib/qvd/bin/sshfs
command.tar=tar
command.umount=umount
command.unionfs-fuse=/usr/lib/qvd/bin/unionfs
command.usbclnt=/usr/local/bin/usbclnt
command.usbsrv=/usr/local/bin/usbsrv
command.useradd=/usr/sbin/useradd
command.userdel=/usr/sbin/userdel
command.version.lxc=0.7
command.windows.nxproxy=nx\nxproxy.exe
command.windows.pulseaudio=pulseaudio\pulseaudio.exe
command.windows.sftp-server=bin/sftp-server.exe
command.windows.xming=Xming\Xming.exe
command.x-session=/etc/X11/Xsession
command.x-session.args.extra=
command.x11vnc=/usr/bin/x11vnc
command.xhost=/usr/bin/xhost
command.xinit=/usr/bin/xinit
database.host=localhost
database.name=qvddb
database.password=tweakk69
database.user=qvd
hkd.as_user=root
hkd.pid_file=/var/run/qvd/qvd-hkd.pid
hkd.user.umask=0022
hkd.vm.starting.max=6
l7r.address=*
l7r.as_user=root
l7r.auth.plugin.default.salt=qvd1234
l7r.auth.plugins=default
l7r.client.cert.require=0
l7r.loadbalancer.plugin=default
l7r.loadbalancer.plugin.default.weight.cpu=1
l7r.loadbalancer.plugin.default.weight.ram=1
l7r.loadbalancer.plugin.default.weight.random=1
l7r.pid_file=/var/run/qvd/qvd-l7r.pid
l7r.port=8443
l7r.use_ssl=1
l7r.user.umask=0022
log.filename=/var/log/qvd/qvd.log
log.level=ERROR
model.user.login.case-sensitive=0
nodename=localhost
osf.default.memory=256
osf.default.overlay=1
path.cgroup=/sys/fs/cgroup
path.cgroup.cpu.lxc=/sys/fs/cgroup/cpu/lxc
path.client.pixmaps=pixmaps
path.client.pixmaps.alt=/usr/share/pixmaps
path.darwin.ssl.ca.system=/System/Library/OpenSSL/certs/
path.hypervisor.captures=/var/tmp/qvd/qvd
path.l7r.ssl=/var/run/qvd/l7r/ssl
path.l7r.ssl.ca=/var/run/qvd/l7r/ssl/ca.pem
path.l7r.ssl.cert=/var/run/qvd/l7r/ssl/cert.pem
path.l7r.ssl.crl=/var/run/qvd/l7r/ssl/crl.pem
path.l7r.ssl.key=/var/run/qvd/l7r/ssl/key.pem
path.log=/var/log/qvd
path.qvd.bin=/usr/lib/qvd/bin
path.run=/var/run/qvd
path.run.lxc=/var/run/qvd/lxc
path.serial.captures=/var/tmp/qvd/qvd
path.ssl.ca.personal=certs
path.ssl.ca.system=/etc/ssl/certs
path.storage.basefs=/var/lib/qvd/storage/basefs
path.storage.btrfs.root=/var/lib/qvd/storage
path.storage.check=/var/lib/qvd/storage/homes/.rw_check
path.storage.homefs=/var/lib/qvd/storage/homefs
path.storage.homes=/var/lib/qvd/storage/homes
path.storage.images=/var/lib/qvd/storage/images
path.storage.overlayfs=/var/lib/qvd/storage/overlayfs
path.storage.overlays=/var/lib/qvd/storage/overlays
path.storage.root=/var/lib/qvd/storage
path.storage.rootfs=/var/lib/qvd/storage/rootfs
path.storage.staging=/var/lib/qvd/storage/staging
path.tmp=/var/tmp/qvd
vm.hypervisor=kvm
vm.hypervisor.capture=0
vm.kvm.home.drive.index=1
vm.kvm.virtio=1
vm.lxc.home.per.user=0
vm.lxc.unionfs.bind.ro=1
vm.lxc.unionfs.type=overlayfs
vm.network.bridge=qvdnet
vm.network.dns_server=192.168.0.1
vm.network.domain=
vm.network.firewall.nat.iface=
vm.network.gateway=192.168.0.1
vm.network.ip.start=192.168.1.3
vm.network.mac.prefix=54:52:00
vm.network.netmask=24
vm.network.use_dhcp=1
vm.overlay.persistent=0
vm.serial.capture=0
vm.serial.redirect=1
vm.vnc.opts=
vm.vnc.redirect=0
vma.audio.enable=0
vma.default.client.keyboard=pc105/en
vma.default.client.link=adsl
vma.default.lang=en_US.UTF-8
vma.on_action.connect=
vma.on_action.disconnect=
vma.on_action.expire=
vma.on_action.poweroff=
vma.on_action.pre-connect=
vma.on_action.stop=
vma.on_action.suspend=
vma.on_provisioning.add_user=
vma.on_provisioning.after_add_user=
vma.on_provisioning.mount_home=
vma.on_state.connected=
vma.on_state.disconnected=
vma.on_state.suspended=
vma.pid_file=/var/run/qvd/vma.pid
vma.printing.enable=0
vma.slave.command=/usr/lib/qvd/bin/qvd-vma-slaveserver
vma.slave.enable=0
vma.user.default.groups=
vma.user.default.name=qvd
vma.user.home.drive=/dev/vdb
vma.user.home.fs=ext4
vma.user.home.path=/home
vma.user.shell=/bin/bash
vma.user.umask=0022
wat.admin.login=admin
wat.admin.password=tweakk69
wat.log.filename=/var/log/qvd/qvd-wat.log


qa host list

localhost 192.168.1.3 -                         0            0       stopped

ifconfig -a

eth0      Link encap:Ethernet  HWaddr bc:ae:c5:1b:78:53  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:22 Memory:f7de0000-f7e00000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:966 errors:0 dropped:0 overruns:0 frame:0
          TX packets:966 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:210671 (210.6 KB)  TX bytes:210671 (210.6 KB)

qvdnet    Link encap:Ethernet  HWaddr 16:c1:df:fc:3c:94  
          inet addr:192.168.1.3  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::14c1:dfff:fefc:3c94/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:49 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:7390 (7.3 KB)

wlan0     Link encap:Ethernet  HWaddr 30:b5:c2:18:60:5b  
          inet addr:192.168.0.2  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::32b5:c2ff:fe18:605b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1441 errors:0 dropped:58 overruns:0 frame:0
          TX packets:1295 errors:0 dropped:1 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1252677 (1.2 MB)  TX bytes:218238 (218.2 KB)

**Comment by rolohaun** [comment]
my node.conf

#
# QVD Node Configuration
#

# Name of this node in QVD. Usually the machine's hostname.
nodename=localhost

# Database connection information.
# database.host: where the QVD database is found
# database.name: the name of the QVD database
# database.user: the user account needed to connect
# database.password: the password needed to connect
database.host =localhost
database.name =qvddb
database.user =qvd
database.password =tweakk69

path.run = /var/run/qvd
path.log = /var/log/qvd
path.tmp = /var/tmp/qvd

log.filename = /var/log/qvd/qvd.log

wat.admin.login=admin
wat.admin.password=tweakk69

log.level=ERROR

**Comment by jzeaherra** [comment]
Hi, your node must have an ip in the same subnetwork as your vm network, but before the vm.network.ip.start. Most simple case:

node has ip 192.168.1.1
vm.network.ip.start=192.168.1.2
vm.network.netmask=24

This way your vm's will receive ips starting on 192.168.1.254 and counting down...

On the other hand, when you add your node, the ip must be the one within that subnetwork:
qa host add name=(node-name) address=192.168.1.1

Regards,
Juan

**Comment by rolohaun** [comment]
Should my bridge ip be 192.168.1.2?

**Comment by narenas** [comment]
Hi 

No your bridge must have the same ip as the host that you have added with qa , then is ok, to have 192.168.1.3. 

So for your configuration, the easiest way to fix this, should be changing vm.network.ip.start to vm.network.ip.start=192.168.1.4 . 
# qa config set vm.ip.start=10.3.15.1


Also you have vm.network.gateway=192.168.0.1 ,  that should be 192.168.1.3 (or a gateway in the same subnet 192.168.1.x). For example: 
# qa config set vm.network.gateway=192.168.1.3 

If this not works, please could you share the qvd.log, (please set the log.level to DEBUG in your node.conf file), located in /var/log/qvd/qvd.log . 


Regards.

**Comment by rolohaun** [comment]
ok so this is how it should be setup

Node 192.168.1.1
Vm network start 192.168.1.2
Bridge 192.168.1.1

**Comment by narenas** [comment]
Yep , that should work.

**Comment by rolohaun** [comment]
Alright, I will give it a try tonight and report back.

Thank you!

**Comment by rolohaun** [comment]
that worked, another question though. I logged into my vm with the client and can't seem to stream audio while watching a youtube video? This is with a 512mb memory vm machine I am only trying to watch it in 360p. Do I need more memory? I am using the 13.04 demo image, should I make my own fresh lubuntu image?

**Comment by narenas** [comment]
What is the client that you are using? Windows? Linux? Mac? 

Did you enabled the sound in the client? . 

Is you are using the Linux client you should enable remote access to the pulse server that must be running on your local computer. To do that you can follow this steps. 

execute paprefs command in a console. 
Click on the Network Server tab
Check the Enable network access box to local sound devices. 
Check the Don't require authentication box. 

Also in the virtual Machine check if the /etc/qvd/vma.conf has the audio property enabled. 

vma.audio.enable: 1

Regards.

**Comment by rolohaun** [comment]
I am using the windows client.

I enabled audio on the client and it does start sending audio however the video is no longer displayed.

I am using the 13.04 prebuild image QVD provides I did notice that chromium and firefox as well as flash are out dated. In chromium when I go to Youtube audio plays for about 20 second and then stops there is no video. In firefox both audio and video play but not well.

Possibly this issue is due to the image being out of date with old browsers and flash?

**Comment by jzeaherra** [comment]
Our multimedia support is a bit limited just now. Video streams require bandwidth and cpu, so they don't really work well even on updated navigators. 
We're working on it but I can't give you any dates on that because we don't really have it :-/
Audio on its own, however, should play quite nicely.

**Comment by rolohaun** [comment]
Alright, the last question I have is with the raspberry pi client. When I try to connect to my server I keep getting an error say protocol not defined.

I am using the host, username and password switch. I there any guides for using the raspberry pi client?

**Comment by salva** [comment]
@rolohaun, no, we don't have any guides specific to the Raspberry PI, but on the other hand there is nothing special to it.

The logs, both the client and server ones, may contain some information about what is going wrong in your installation. They are usually stored at `/var/log/qvd.log` and `~/.qvd/client.log`. You can also attach them here and we would help you analyze them.
