### ISSUE TITLE
Raspberry Pi QVD Client Help

### ISSUE THREAD

**Issue by rolohaun** [theqvd/theqvd#31]
I am having trouble getting the QVD Cient for the raspberry pi working.

When I try to connect to my server I keep getting an error say protocol not defined.

I am using the host, username and password switch. I there any guides for using the raspberry pi client?

**Comment by qindel** [comment]
Hi Rolohan,

Have you tried to run with -h to see the help page?

Please run it with -d and place the output.

Place also the version of the client with the option -v.

Please tell us also which version of the raspberry pi you are using.

The lowest version has some performance problems, that is it has not enough power to run.

Regards, 

Nito

On December 27, 2015 8:08:46 PM GMT+01:00, rolohaun <notifications@github.com> wrote:
>I am having trouble getting the QVD Cient for the raspberry pi working
>
>When I try to connect to my server I keep getting an error say protocol
>not defined
>
>I am using the host, username and password switch I there any guides
>for using the raspberry pi client?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/theqvd/theqvd/issues/31

-- 
Nito Martinez
CTO | Qindel Group
E: nito.martinez@qindel.com
M: +34678476906

**Comment by nitomartinez** [comment]
By the way, 

I have updated the latest binary client for raspberry pi to 1.2.1 (the old one was 1.1.8) to:

http://theqvd.com/downloads/binaries/raspberrypi/qvdclient_arm-linux-gnueabihf

Could you test this one? And also provide feedback? (-v option output and -d output)

**Comment by rolohaun** [comment]
I am running on a raspberry pi 2 here is the output of -d

Starting qvd_init. libqvd version: Version: 1.2.1. $Id: qvdclient.h 28272 2015-12-03 08:24:08Z jzea $
Curl version: libcurl/7.42.1 OpenSSL/1.0.2d
Openssl version: OpenSSL 1.0.2d 9 Jul 2015
nxcomp version: 3.5.0.22
Curl pointer is 0x15f23e8Disabling client certificate
Setting progress callback
using HOME environment varSetting cert path to /root/.qvd/certs
Setting NX_HOME to /root
No client certificates used
== Info:   Trying 192.168.0.2...
== Info: TCP_NODELAY set
== Info: Connected to 192.168.0.2 (192.168.0.2) port 8443 (#0)
== Info: ALPN, offering http/1.1
== Info: Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
== Info: successfully set certificate verify locations:
== Info:   CAfile: none
  CApath: /root/.qvd/certs
== Info: TLSv1.2, TLS Unknown, Unknown (22):
== Info: TLSv1.2, TLS handshake, Client hello (1):
== Info: SSLv2, Unknown (22):
== Info: TLSv1.2, TLS handshake, Server hello (2):
== Info: SSLv2, Unknown (22):
== Info: TLSv1.2, TLS handshake, CERT (11):
_qvd_verify_cert_callback: Certificate was validated
== Info: SSLv2, Unknown (22):
== Info: TLSv1.2, TLS handshake, Server finished (14):
== Info: SSLv2, Unknown (22):
== Info: TLSv1.2, TLS handshake, Client key exchange (16):
== Info: SSLv2, Unknown (20):
== Info: TLSv1.2, TLS change cipher, Client hello (1):
== Info: SSLv2, Unknown (22):
== Info: TLSv1.2, TLS handshake, Finished (20):
== Info: SSLv2, Unknown (20):
== Info: TLSv1.2, TLS change cipher, Client hello (1):
== Info: SSLv2, Unknown (22):
== Info: TLSv1.2, TLS handshake, Finished (20):
== Info: SSL connection using TLSv1.2 / AES256-GCM-SHA384
== Info: ALPN, server did not agree to a protocol
== Info: --- Certificate chain
== Info:  0 Subject: C=CA; ST=Alberta; L=Edmonton; O=RFSystems; OU=RFSystems; CN=192.168.0.2; emailAddress=rolohaun@gmail.com
== Info:    Issuer: C=CA; ST=Alberta; L=Edmonton; O=RFSystems; OU=RFSystems; CN=192.168.0.2; emailAddress=rolohaun@gmail.com
== Info:    Version: 3 (0x2)
== Info:    Serial Number: e9690e5f50e87abf
== Info:    Signature Algorithm: sha1WithRSAEncryption
== Info:    Start date: 2015-12-13 22:05:48 GMT
== Info:    Expire date: 2025-12-10 22:05:48 GMT
== Info:    Public Key Algorithm: rsaEncryption
== Info:    RSA Public Key (1024 bits)
== Info:    rsa(n): cc:2f:70:3e:8f:3e:61:f5:ea:7e:10:4c:10:59:05:3a:9c:15:1c:42:06:cf:0f:80:72:70:4c:2d:e6:9e:c3:44:b0:9a:e3:ed:33:42:0b:58:bf:c8:a4:69:2f:6e:87:07:a4:4d:b1:c2:28:34:74:d7:41:d1:fe:c9:8e:bf:de:27:98:44:58:2d:4f:24:9b:7c:21:b0:4a:82:92:f9:0a:b6:0e:58:fc:c7:58:e3:bc:d8:57:1d:e0:eb:4a:3a:e0:c3:06:f2:e0:8f:df:a9:e1:26:73:04:9e:37:69:7c:31:48:7c:a5:30:5e:db:2b:3a:4d:dd:a1:49:5d:62:83:8b:15:
== Info:    rsa(e): 01:00:01:
== Info: X509v3 Subject Key Identifier: 
== Info:   BD:82:C0:B3:65:5A:07:C6:C2:87:11:1B:0E:0A:F0:1F:2A:4F:CD:09
== Info: X509v3 Authority Key Identifier: 
== Info:   keyid:BD:82:C0:B3:65:5A:07:C6:C2:87:11:1B:0E:0A:F0:1F:2A:4F:CD:09
== Info: X509v3 Basic Constraints: 
== Info:   CA:TRUE
== Info:  Signature: 03:13:d0:31:40:3d:38:6b:a4:95:d1:7c:3d:6c:89:b2:21:3c:9e:eb:f9:05:81:51:ca:7a:29:8c:db:7e:b4:4a:79:59:2e:da:7b:fa:bd:e4:69:fa:ef:16:ef:1b:e1:7c:cd:fa:be:37:da:9c:9b:f9:63:3b:26:aa:53:e3:72:14:ff:ec:95:78:c1:94:c8:77:b1:67:93:44:0e:b8:58:e7:39:a6:0c:2e:40:7b:00:9d:4b:2c:6d:29:f9:b9:b4:45:f8:31:5c:55:95:8f:22:da:66:00:f0:af:d6:d4:9c:73:ec:05:25:43:e4:0f:bb:aa:b6:0a:9e:84:71:83:0e:38:
== Info: Server certificate:
== Info: 	 subject: C=CA; ST=Alberta; L=Edmonton; O=RFSystems; OU=RFSystems; CN=192.168.0.2; emailAddress=rolohaun@gmail.com
== Info: 	 start date: 2015-12-13 22:05:48 GMT
== Info: 	 expire date: 2025-12-10 22:05:48 GMT
== Info: 	 issuer: C=CA; ST=Alberta; L=Edmonton; O=RFSystems; OU=RFSystems; CN=192.168.0.2; emailAddress=rolohaun@gmail.com
== Info: 	 SSL certificate verify ok.
== Info: Server auth using Basic with user 'demo3'
== Info: SSLv2, Unknown (23):
=> Send header, 0000000146 bytes (0x00000092)
0000: 47 45 54 20 2f 71 76 64 2f 6c 69 73 74 5f 6f 66 GET /qvd/list_of
0010: 5f 76 6d 20 48 54 54 50 2f 31 2e 31 0d 0a 48 6f _vm HTTP/1.1..Ho
0020: 73 74 3a 20 31 39 32 2e 31 36 38 2e 30 2e 32 3a st: 192.168.0.2:
0030: 38 34 34 33 0d 0a 41 75 74 68 6f 72 69 7a 61 74 8443..Authorizat
0040: 69 6f 6e 3a 20 42 61 73 69 63 20 5a 47 56 74 62 ion: Basic ZGVtb
0050: 7a 4d 36 5a 47 56 74 62 77 3d 3d 0d 0a 55 73 65 zM6ZGVtbw==..Use
0060: 72 2d 41 67 65 6e 74 3a 20 51 56 44 2f 33 2e 31 r-Agent: QVD/3.1
0070: 20 6c 69 62 63 75 72 6c 2f 37 2e 34 32 2e 31 20  libcurl/7.42.1 
0080: 4f 70 65 6e 53 53 4c 2f 31 2e 30 2e 32 64 0d 0a OpenSSL/1.0.2d..
0090: 0d 0a                                           ..
== Info: SSLv2, Unknown (23):
<= Recv header, 0000000017 bytes (0x00000011)
0000: 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d HTTP/1.1 200 OK.
0010: 0a                                              .
<= Recv header, 0000000032 bytes (0x00000020)
0000: 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70 Content-Type: ap
0010: 70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a plication/json..
<= Recv header, 0000000021 bytes (0x00000015)
0000: 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 Content-Length: 
0010: 31 30 31 0d 0a                                  101..
<= Recv header, 0000000002 bytes (0x00000002)
0000: 0d 0a                                           ..
== Info: SSLv2, Unknown (23):
<= Recv data, 0000000101 bytes (0x00000065)
0000: 5b 0a 20 20 20 7b 0a 20 20 20 20 20 20 22 62 6c [.   {.      "bl
0010: 6f 63 6b 65 64 22 20 3a 20 30 2c 0a 20 20 20 20 ocked" : 0,.    
0020: 20 20 22 6e 61 6d 65 22 20 3a 20 22 74 65 73 74   "name" : "test
0030: 22 2c 0a 20 20 20 20 20 20 22 69 64 22 20 3a 20 ",.      "id" : 
0040: 34 34 2c 0a 20 20 20 20 20 20 22 73 74 61 74 65 44,.      "state
0050: 22 20 3a 20 22 72 75 6e 6e 69 6e 67 22 0a 20 20 " : "running".  
0060: 20 7d 0a 5d 0a                                   }.].
== Info: Connection #0 to host 192.168.0.2 left intact
After easy_perform: 0l
No error and no auth error after curl_easy_perform
VMs available: 1
VM json output: [
   {
      "blocked" : 0,
      "name" : "test",
      "id" : 44,
      "state" : "running"
   }
]

VM ID:44 NAME:test STATE:running BLOCKED:0
Progress Callback: Returning list of vms
qvd_connect_to_vm(0x15cf010,44)Setting NX_HOME to /root
Setting cert path to /root/.qvd/certs
No client certificates used
== Info: Rebuilt URL to: https://192.168.0.2:8443/
== Info: Found bundle for host 192.168.0.2: 0x1604200
== Info: Re-using existing connection! (#0) with host 192.168.0.2
== Info: Connected to 192.168.0.2 (192.168.0.2) port 8443 (#0)
== Info: Connection #0 to host 192.168.0.2 left intact
Switch protocols the url is: <GET /qvd/connect_to_vm?id=44&qvd.client.os=linux&qvd.client.geometry=800x600&qvd.client.link=adsl&qvd.client.keyboard=pc%2F105&qvd.client.fullscreen=0 HTTP/1.1
Authorization: Basic ZGVtbzM6ZGVtbw==
Connection: Upgrade
Upgrade: QVD/1.0

>
== Info: SSLv2, Unknown (23):
Before select on send socket is: 3
== Info: SSLv2, Unknown (23):
0 input received was <HTTP/1.1 102 Processing
X-QVD-VM-Info: Session acquired for VM_ID: 44

>
Progress messageProgress Callback: Session acquired for VM_ID: 44


== Info: SSLv2, Unknown (23):
1 input received was <HTTP/1.1 102 Processing
X-QVD-VM-Info: Starting X session at VM 44

>
Progress messageProgress Callback: Starting X session at VM 44


== Info: SSLv2, Unknown (23):
2 input received was <HTTP/1.1 102 Processing
X-QVD-VM-Info: Waiting for X session to come up on VM 44

>
Progress messageProgress Callback: Waiting for X session to come up on VM 44


== Info: SSLv2, Unknown (23):
3 input received was <HTTP/1.1 102 Processing
X-QVD-VM-Info: Connecting X session for VM_ID: 44

>
Progress messageProgress Callback: Connecting X session for VM_ID: 44


== Info: SSLv2, Unknown (23):
4 input received was <HTTP/1.1 102 Processing
X-QVD-VM-Info: Connection established

>
Progress messageProgress Callback: Connection established


== Info: SSLv2, Unknown (23):
5 input received was <HTTP/1.1 101 Switching Protocols
X-QVD-Slave-Key: 1WwTcx8RcahbOLnLjry7A9Bhx7xXEx1dyeuzEbfvrm5FsE4xlCC2dXtBwI449tU5

>
Upgrade of protocol was done
Printing environment variables
Environment var SHELL=/bin/bash
Environment var TERM=xterm
Environment var USER=root
Environment var LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
Environment var SUDO_USER=rpitc
Environment var SUDO_UID=1000
Environment var USERNAME=root
Environment var MAIL=/var/mail/root
Environment var PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment var PWD=/home/rpitc
Environment var SHLVL=1
Environment var SUDO_COMMAND=/bin/su
Environment var HOME=/root
Environment var LOGNAME=root
Environment var SUDO_GID=1000
Environment var DISPLAY=:0.0
Environment var XAUTHORITY=/home/rpitc/.Xauthority
Environment var _=./qvd
Environment var NX_HOME=/root
QVD curl socket is 3Remote fd: 3 Local fd: 5
Before _qvd_client_loop
_qvd_client_loop
_qvd_client_loop(0x15cf010, 3, 5)
_qvd_client_loop setting proxyFd to O_NONBLOCK 22867984

NXPROXY - Version 3.5.0

Copyright (C) 2001, 2010 NoMachine.
See http://www.nomachine.com/ for more information.

Info: Proxy running in client mode with pid '1476'.
Session: Starting session at 'Sat Jan  2 21:28:14 2016'.
== Info: SSLv2, Unknown (23):
== Info: SSLv2, Unknown (23):
Info: Connection with remote proxy completed.
Info: No proxy cookie was provided for authentication.
Info: Forwarding the real X authorization cookie.
Info: Using ADSL link parameters 512/24/1/0.
Info: Using cache parameters 4/4096KB/8192KB/8192KB.
Info: Using pack method 'adaptive-7' with session ''.
Info: Using ZLIB data compression 1/1/32.
Info: Using ZLIB stream compression 4/4.
Info: No suitable cache file found.
Info: Forwarding X11 connections to display ':0.0'.
Session: Session started at 'Sat Jan  2 21:28:14 2016'.
== Info: SSLv2, Unknown (23):
== Info: SSLv2, Unknown (23):
== Info: SSLv2, Unknown (23):
Warning: X connection failed with error 'No protocol specified'.
== Info: SSLv2, Unknown (23):
== Info: SSLv2, Unknown (23):
== Info: SSLv2, Unknown (23):
Session: Terminating session at 'Sat Jan  2 21:28:18 2016'.
Info: Your session was closed before reaching a usable state.
Info: This can be due to the local X server refusing access to the client.
Info: Please check authorization provided by the remote X application.
Session: Session terminated at 'Sat Jan  2 21:28:18 2016'.
Nothing read. receiving curl_easy_recv: 81 CURLE_AGAIN, read 0
No more bytes to read from proxyFd ending
Progress Callback: End of QVD connection
Calling qvd_free with qvd=0x15cf010, and curl=0x15f23e8
after NXTransCleanupForReconnect

**Comment by rolohaun** [comment]
here is the output from -v

libqvd version: Version: 1.2.1. $Id: qvdclient.h 28272 2015-12-03 08:24:08Z jzea $
Curl version: libcurl/7.42.1 OpenSSL/1.0.2d
Openssl version: OpenSSL 1.0.2d 9 Jul 2015
nxcomp version: 3.5.0.22

Changelog:
1.2.1 26/08/2015 Use ASL logging for Apple, openssl: 1.0.2d, jansson: 2.7
1.2.0 07/05/2015 Improve Select on write file descriptors
1.1.9 06/05/2015 Use NXTransCleanupForReconnect for IOS
1.1.8 06/05/2015 Include nxcomp version in the -v flag
1.1.7 03/05/2015 During debug show correct version text
1.1.6 28/04/2015 More time to session takeover
1.1.5  5/12/2014 Support for HTTP code 402
1.1.4 23/11/2014 Extend pass length to 256
1.1.3 21/07/2014 Fix -r switch (not in the qvdclient binary only in the lib
1.1.2 18/07/2014 Fix hardcoded ip in reconnect (option -2)
1.1.1 26/06/2014 Upgraded curl to 7.37.0 and nxcomp to 3.5.0.22 and openssl to 1.0.1h. Use implicit curl_global_init. Debug now goes to stderr.
1.1.0 21/06/2014 Added support for restart -r, and to reconnect twice
1.0.1 12/10/2013 in the client added support for environment vars QVDLOGIN QVDPASSWORD and QVDHOST
                 and in the library support for qvd_get_changelog
1.0   ////////// Initial version

**Comment by nitomartinez** [comment]
A couple of more questions:

1) xhost permissions

have you tried to run:

xhost +

or alternatively

xhost +local:

xhost +si:localuser:$USER

2) Have you been able to connect to the same VM with a linux client (for 
example)?

Regards,

Nito

**Comment by rolohaun** [comment]
xhost +local: fixed my issue, the client works now.

I have a few question now about the client and documentation

How do I enable usb redirection?
How do I enable sound?

**Comment by nitomartinez** [comment]
Hi Rohan, 

Thanks for trying it out, and glad that it worked :-) 

Regarding your questions: 

1) Sound support: 

Please check if you have enabled paprefs and the sound in the VMA. See http://docs.theqvd.com/docs/AdministrationManual.html#qvd-vma-config 

In the command line client you should be able to try it out with: the option "-x media=4713" (please invoke qvdclient -h for help" 

2) USB support: 

I am afraid this hasn't been tested in the command line client, although you should be able to make it work by passing the following option: 

-x slave=63586 

Let me know if this works, if not, then probably it is worth to either: 

- package the normal perl client (not the command line one) for raspberry pi. This should not be too difficult, and patches are welcome :-) 
- Get professional support from theqvd.com ;-) 

Regards, 

Nito 

----- Original Message -----

**Comment by rolohaun** [comment]
Hi Nito,

Thanks for all the help, is it possible to get the perl client? I would much rather prefer an actual GUI client so I don't need to make a script with the user names and passwords in it.

I am a windows system admin and not very familiar with linux yet.

**Comment by nitomartinez** [comment]
The perl client is available here: 

https://github.com/theqvd/theqvd/tree/master/ext/QVD-Client 

although not packaged for raspbian yet :-( 

Currently no customer is sponsoring further developments with raspbian, so not sure how soon we can acomplish this... 

I request it to our marketing department to prioritize it into the roadmap (not sure how far it will go though) 

Thanks for testing QVD :-) 

Nito 

----- Original Message -----

**Comment by rolohaun** [comment]
Thank for all the help Nito, QVD seems like a great solution. I really need a working raspberry pi client for me to start using it with my new start up business but I understand it's not the priority right now.

I hope more companies realize the potential of a 35 dollar thin client and QVD.

Thanks for all the help and I will be checking back to see your progress! Great product!

**Comment by nitomartinez** [comment]
Thanks to you to test it out :-)

Nito
