### ISSUE TITLE
Only able to Login with one User

### ISSUE THREAD

**Issue by ryananderson0219** [theqvd/theqvd#33]
Hello,

I have been able to successfully start and login with one user, but I've created other users and unable to login. I keep getting this error with multiple users (all but the first one I created):

"Unable to connect to remote VM: 503 Service Unavailable

The requested virtual machine is not available: Unable to start X session on VM 16, state went to stopped, retry later"

I am using the same image/flavor, but I am getting different results. I have restarted and trying on of the other accounts first, but get the same error. Then I try the first one again, and it works.

Any ideas?
[qvd.log.txt](https://github.com/theqvd/theqvd/files/120956/qvd.log.txt)

**Comment by nitomartinez** [comment]
Hi,

thanks for keeping up your interest in QVD.


My first suspicion is that either the VMs have not been correctly setup, or that there is a lack of resources (full filesystem, not enough RAM, ...). But let's see, ...

From what I see the VM seems to be correctly going to state running... And the user that is not working is scottsmith and the one that is working is qvd, am I right?


Could you post the output of the following commands?

Providing you are using the Ubuntu distribution:
```
dpkg -l | grep -i qvd
```
or if you are using the RPM one

```
rpm -qa | grep -i qvd
```

Other outputs:

```
qa osf list
```

```
qa di list
```

```
qa user list
```

```
qa vm list
```

**Comment by ryananderson0219** [comment]
I have always loved Linux, and I have been interested in Linux Virtualization since I see a lot of Virtualization with Windows. Resources may be at play, but it is strange that I can login with the first one and not the other, but idk. Here is the information requested.

$ dpkg -l | grep -i qvd
ii  perl-qvd-admin                                        3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-admin-web                                    3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-client                                       3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-config                                       3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-config-core                                  3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-db                                           3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-hkd                                          3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-http                                         3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-httpc                                        3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-httpd                                        3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r                                          3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r-loadbalancer                             3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-log                                          3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-simplerpc                                    3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-uri                                          3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  perl-qvd-vmkiller                                     3.5.0-26038                                         all          Common perl modules from CPAN for QVD.
ii  qvd-admin-web-libs                                    3.5.0-25893                                         amd64        Common perl modules from CPAN for qvd.
ii  qvd-client-libs                                       3.5.0-25893                                         amd64        Common perl modules from CPAN for qvd.
ii  qvd-common-libs                                       3.5.0-25893                                         amd64        Common perl modules from CPAN for qvd.
ii  qvd-fuse-unionfs                                      0.25build10.r21922                                  amd64        FUSE version of UnionFS
ii  qvd-liblxc1                                           1.0.6-25890                                         amd64        Linux Containers userspace tools (library)
ii  qvd-libxcomp3                                         3.5.0-22build-jenkins11-trusty                      amd64        NX X compression library
ii  qvd-lxc                                               1.0.6-25890                                         amd64        Linux Containers userspace tools
ii  qvd-lxc-templates                                     1.0.6-25890                                         amd64        Linux Containers userspace tools (templates)
ii  qvd-node-libs                                         3.5.0-25893                                         amd64        Common perl modules from CPAN for qvd.
ii  qvd-nxproxy                                           3.5.0-22build-jenkins11-trusty                      amd64        NX proxy
ii  qvd-perl                                              5.14.2                                              amd64        Perl Package to be used by qvd-libs
ii  qvd-python3-lxc                                       1.0.6-25890                                         amd64        Linux Containers userspace tools (Python 3.x bindings)

Id Name        RAM  Overlay UserHD
----------------------------------
4  ubutnu-1304 2048 yes     20000 
5  OpenSuse 13 2048 yes     20000 

7  5   2016-02-07-000 7-opensuse-12.3-qvd.tar.gz 2016-02-07-000, default, head (haven't deleted yet, but not using since I'm using KVM at the moment)
8  4   2016-02-07-000 8-ubuntu-13.04-qvd34.qcow2 2016-02-07-000, default, head

Id Login        
----------------
1  ryan.anderson
2  qvd          
3  rylee0219    
4  ryan         
5  scottsmith   

Id Name       User       RealUser   Ip          OSF         DI_Tag         DI             Host                   State   L7R UserState    Blocked Expire soft Expire hard
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
13 ubuntu     qvd        qvd        10.3.15.253 ubutnu-1304 default        2016-02-07-000 rylee0219-Inspiron-546 running -   disconnected 0       -           -          
14 Ryan       rylee0219  rylee0219  10.3.15.252 ubutnu-1304 default        2016-02-07-000 -                      stopped -   disconnected 0       -           -          
16 ryanubuntu ryan       ryan       10.3.15.251 ubutnu-1304 2016-02-07-000 2016-02-07-000 rylee0219-Inspiron-546 running -   disconnected 0       -           -          
17 scottsmith scottsmith scottsmith 10.3.15.250 ubutnu-1304 default        2016-02-07-000 rylee0219-Inspiron-546 running -   disconnected 0       -           -

**Comment by ryananderson0219** [comment]
Oh, and yes you are correct. I can successfully login with qvd, but not scottsmith, ryan.anderson, rylee0219, or ryan)

**Comment by nitomartinez** [comment]
Looks good :-)

I think you have hit a bug which is only corrected in the supported version, but that has an easy workaround (if my suspicions are correct)

the UserHD  is in bytes (output of "qa osf list"). That is for the home you have allocated 20K (roughly), and probably the startup of the X system fills up that space. the reason why the qvd users works, is because that user already exists in the QVD image that you downloaded :-)

Try one of the following:

- Delete the OSF, and recreate it without any userHD parameter (that is optional), or put a higher value in it like 52428800 (50MB). After that you need to recreate the VMs for the users (delete them and add them again).

- More hackerish (I would not recommend this, but it is duable). Stop the VMs, chhange the setting in the osf table in the database, stop the VMs, delete the overlays, and start them again.

As you can see in a fresh installation the first one would probably work better.

Please test this, and let us know the output.

Regards,

**Comment by ryananderson0219** [comment]
I can't thank you enough. Your assistance has been greatly appreciated! Very fast and you knew exactly what the problem was! Issue is resolved now. Thanks again!

I still have a lot to learn about QVD, but from what I see it is amazing.

Thanks for taking the time to show me what was wrong.
