### ISSUE TITLE
Unable to login with created image

### ISSUE THREAD

**Issue by ryananderson0219** [theqvd/theqvd#34]
Sorry to keep bothering you. Got another issue that I can't wrap my head around. I created the image just like the documentation. It will start, but when I try to login it just logs me out and closes the window. I have tried with different settings and users.  It does keep running though. I was able to ssh in via the qa command. I checked to see if the qvd-vma service was running and it was. Can you tell me what I missed.
[qvd.log.txt](https://github.com/theqvd/theqvd/files/125730/qvd.log.txt)

**Comment by nitomartinez** [comment]
Hi,

Thanks for keeping up your interest ;-)

My suspicion is that the nxagent is not starting up.

If you are able to ssh into the image please provide the following logs from inside the VM:

/var/log/qvd.log (this is the VMA log)
/var/log/qvd-nxagent.log

**Comment by ryananderson0219** [comment]
/var/log/qvd.log
2016/02/10 15:42:41 2185 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
237 - Process ID is 2185
2016/02/10 15:42:41 2185 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
239 - Written to /var/run/qvd/vma.pid
2016/02/10 15:42:41 2185 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 217 - Unable to open printing configuration file '/var/run/qvd/printing.conf': No such file or directory at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm line 211.
2016/02/10 16:08:46 2185 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 217 - Unable to open printing configuration file '/var/run/qvd/printing.conf': No such file or directory at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm line 211.
2016/02/10 16:28:19 1056 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
237 - Process ID is 1056
2016/02/10 16:28:19 1056 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
239 - Written to /var/run/qvd/vma.pid
2016/02/10 16:28:19 1056 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 217 - Unable to open printing configuration file '/var/run/qvd/printing.conf': No such file or directory at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm line 211.
2016/02/10 16:28:28 1273 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 735 - starting/resuming X session
2016/02/10 16:28:29 1275 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 374 - provisioning of group 'scottsmith' failed
2016/02/10 16:28:37 1474 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
347 - Process name checking requires Proc::ProcessTable
2016/02/10 16:28:37 1474 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
175 - Already running: 1056 (pidfile=/var/run/qvd/vma.pid)
2016/02/10 16:29:22 1491 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 735 - starting/resuming X session
2016/02/10 16:29:54 1557 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 735 - starting/resuming X session
2016/02/10 18:36:05 1959 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 735 - starting/resuming X session
2016/02/10 18:39:30 2028 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 735 - starting/resuming X session
~                                                                                   "/var/log/qvd.log" [readonly] 15L, 2202C                          1,1           All

/var/log/qvd-nxagent.log
2016/02/10 15:42:41 2185 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
237 - Process ID is 2185
2016/02/10 15:42:41 2185 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
239 - Written to /var/run/qvd/vma.pid
2016/02/10 15:42:41 2185 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 217 - Unable to open printing configuration file '/var/run/qvd/printing.conf': No such file or directory at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm line 211.
2016/02/10 16:08:46 2185 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 217 - Unable to open printing configuration file '/var/run/qvd/printing.conf': No such file or directory at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm line 211.
2016/02/10 16:28:19 1056 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
237 - Process ID is 1056
2016/02/10 16:28:19 1056 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
239 - Written to /var/run/qvd/vma.pid
2016/02/10 16:28:19 1056 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 217 - Unable to open printing configuration file '/var/run/qvd/printing.conf': No such file or directory at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm line 211.
2016/02/10 16:28:28 1273 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 735 - starting/resuming X session
2016/02/10 16:28:29 1275 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 374 - provisioning of group 'scottsmith' failed
2016/02/10 16:28:37 1474 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
347 - Process name checking requires Proc::ProcessTable
2016/02/10 16:28:37 1474 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm
175 - Already running: 1056 (pidfile=/var/run/qvd/vma.pid)
2016/02/10 16:29:22 1491 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/VMA.pm 735 - starting/resuming X session
2016/02/10 15:42:41 2185 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 237 - Process ID is 2185
2016/02/10 15:42:41 2185 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm === Opened log file at Wed Feb 10 16:28:28 2016 ====
20160210222828: Starting nxagent                                                    Checking that no-one is using this disk right now ...                               OK                                                                                  Disk /dev/vdb: 101 cylinders, 16 heads, 63 sectors/track                            sfdisk: ERROR: sector 0 does not have an msdos signature                             /dev/vdb: unrecognized partition table type                                        Old situation:                                                                      No partitions found                                                                 New situation:                                                                      Units = cylinders of 516096 bytes, blocks of 1024 bytes, counting from 0               Device Boot Start     End   #cyls    #blocks   Id  System                        /dev/vdb1          0+    100     101-     50903+  83  Linux                         /dev/vdb2          0       -       0          0    0  Empty                         /dev/vdb3          0       -       0          0    0  Empty                         /dev/vdb4          0       -       0          0    0  Empty                         Warning: no primary partition is marked bootable (active)                           This does not matter for LILO, but the DOS MBR will not boot this disk.             Successfully wrote the new partition table                                          Re-reading the partition table ...                                                  If you created or changed a DOS partition, /dev/foo7, say, then use dd(1)           to zero the first 512 bytes:  dd if=/dev/zero of=/dev/foo7 bs=512 count=1           (See fdisk(8).)                                                                     mke2fs 1.42 (29-Nov-2011)                                                           Filesystem label=                                                                   OS type: Linux                                                                      Block size=1024 (log=0)
Fragment size=1024 (log=0)
Stride=0 blocks, Stripe width=0 blocks
"/var/log/qvd-nxagent.log" [readonly][noeol] 329L, 15349C         1,1           Top

**Comment by ryananderson0219** [comment]
Here they are in file format. I don't think I got everything last time. IT took a little to figure out how to get them out of the VM... :)
Not sure if this helps or not, but here you go. 

[qvd.log.txt](https://github.com/theqvd/theqvd/files/127349/qvd.log.txt)
[qvd-nxagent.log.txt](https://github.com/theqvd/theqvd/files/127348/qvd-nxagent.log.txt)

**Comment by ryananderson0219** [comment]
Here is after I try a few times:

[qvd.log.txt](https://github.com/theqvd/theqvd/files/127359/qvd.log.txt)
[qvd-nxagent.log.txt](https://github.com/theqvd/theqvd/files/127356/qvd-nxagent.log.txt)

**Comment by nitomartinez** [comment]
Hi Ryan,

could you paste also /etc/qvd/vma.conf?

What kind of desktop are you trying ? I mean xfce, Mate, KDE, ....?

For example for XFCE you need to set up in vma.conf:

```
command.x-session: /usr/bin/startxfce4
```


Or for Mate:
```
command.x-session: /usr/bin/mate-session
```

Let me know if this helps

**Comment by ryananderson0219** [comment]
I was originally trying Ubutun regular with Unity. I was reading on another thread that Unity might not be supported, so I tried Lubuntu and skipped the crucial step of command.x-session: /usr/bin/startxfce4. I would like to test out Gnome or KDE. What are the command.x-session for those?

**Comment by nitomartinez** [comment]
Try Mate, that is gnome2 derivative, in short:

```
apt-get install mate-desktop-environment
```

and in vma.conf

```
command.x-session: /usr/bin/mate-session
```

If you want to notify users on image expiration and so on you might aslo want to try with

```
vma.on_action.expire: /usr/local/bin/notify.sh
vma.on_state.disconnected: /usr/local/bin/poweroff.sh
```

But let's try first the mate desktop :-)

**Comment by ryananderson0219** [comment]
Sweet Mate! Worked. I'm doing most of this by remoting/ssh into my server from my phone since im at work. I will look at Mate from my computer when I get home, but it loaded and looked good!

**Comment by nitomartinez** [comment]
:-)
