### ISSUE TITLE
VM start then stop 

### ISSUE THREAD

**Issue by jmg49** [theqvd/theqvd#35]
hello , 
i can't start a kvm ubuntu vm, i used qcow2 from the qvd site , lxc images , it's the same, 
i have tried what's said into #issue28 but nothing new

my interfaces file : 
`

auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
address 10.48.54.196
netmask 255.255.0.0
gateway 10.48.0.200
dns-search coaxis-asp.com
dns-nameservers 8.8.8.8

auto qvdnet
iface qvdnet inet static
  pre-up brctl addbr qvdnet
  pre-up iptables -t nat -A POSTROUTING -o eth0 -j SNAT --to-source 10.48.54.196
  pre-up iptables -t nat -A PREROUTING -d 10.48.54.196 -p tcp --dport 8443 -j DNAT --to-destination 10.48.54.200
  post-down brctl delbr qvdnet0
  address 10.48.54.200
  netmask 255.255.255.0
`
`
qvdserver@qvdserver:/etc/network$ sudo qa config get | grep vm.network
[sudo] password for qvdserver:
vm.network.bridge=qvdnet
vm.network.dns_server=8.8.8.8
vm.network.domain=
vm.network.firewall.nat.iface=
vm.network.gateway=10.48.54.200
vm.network.ip.start=10.48.54.201
vm.network.mac.prefix=54:52:00
vm.network.netmask=24
vm.network.use_dhcp=1

`

here is my qvd.log

2016/02/16 09:46:33 3213 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 70 - Command start received by vm 11
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from load_row succeeded
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 147 - Searching DIs with tag 'default' for OSF '4'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from search_di succeeded
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 32 - Allocating port '2003'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 165 - Saving runtime row for VM '11': VMA port '3030', X11 port '4100', SSH port '22', VNC port '0', serial port '2003', monitor port '0'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 217 - No action performed for on_result callback
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from save_runtime_row succeeded
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 135 - Increasing run attempts counter for VM '11'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 217 - No action performed for on_result callback
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from incr_run_attempts succeeded
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 249 - Retrieving list of ebtables entries for chain 'INPUT'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 262 - deleting ebtables chain QVD_11_INPUT
2016/02/16 09:46:33 3213 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 265 - Unable to delete chain 'QVD_11_INPUT', rc: 16711680
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 249 - Retrieving list of ebtables entries for chain 'FORWARD'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 262 - deleting ebtables chain QVD_11_FORWARD
2016/02/16 09:46:33 3213 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 265 - Unable to delete chain 'QVD_11_FORWARD', rc: 16711680
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: 0, ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/KVM.pm 233 - mkdir 'overlays_dir' failed: Le fichier existe
2016/02/16 09:46:33 3213 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 302 - Running command ['qemu-img','create','-f','qcow2','-b','/var/lib/qvd/storage/images/6-ubuntu-14.04.1-desktop-amd64.iso','/var/lib/qvd/storage/overlays/6-11-overlay.qcow2']
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 315 - Process 3491 forked
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 340 - Process 3491 returned rc: 0
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/KVM.pm 263 - mkdir '/var/lib/qvd/storage/homes/' failed: Le fichier existe
2016/02/16 09:46:33 3213 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 302 - Running command ['qemu-img','create','-f','qcow2','/var/lib/qvd/storage/homes/11-data.qcow2','120']
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 315 - Process 3493 forked
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 340 - Process 3493 returned rc: 0
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:33 3213 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 302 - Running command ['/sbin/brctl','addif','qvdnet','qvdtap0']
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 315 - Process 3501 forked
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 340 - Process 3501 returned rc: 0
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:33 3213 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/DHCPDHandler.pm 47 - Registering mac '54:52:00:30:36:fe', ip '10.48.54.254' for VM 11 in DHCP
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/DHCPDHandler.pm 64 - Writing DHCP hosts file '/var/run/qvd/dhcp-hostsfile'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/DHCPDHandler.pm 75 - Sending HUP signal to dhcpd
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 377 - killing 3236 with signal HUP
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 224 - Adding ebtables entry '-N QVD_11_INPUT -P ACCEPT'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 224 - Adding ebtables entry '-N QVD_11_FORWARD -P ACCEPT'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 224 - Adding ebtables entry '-A QVD_11_FORWARD -s ! 54:52:00:30:36:fe -j DROP'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 224 - Adding ebtables entry '-A QVD_11_INPUT -s ! 54:52:00:30:36:fe -j DROP'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 224 - Adding ebtables entry '-A QVD_11_FORWARD -p 0x800 --ip-source ! 10.48.54.254 -j DROP'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 224 - Adding ebtables entry '-A QVD_11_INPUT -p 0x800 --ip-protocol 17 --ip-source 0.0.0.0 --ip-destination-port 67 -j ACCEPT'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 224 - Adding ebtables entry '-A QVD_11_FORWARD -p 0x800 --ip-protocol 17 --ip-destination-port 67 -j DROP'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 224 - Adding ebtables entry '-A QVD_11_INPUT -p 0x800 --ip-source ! 10.48.54.254 -j DROP'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 224 - Adding ebtables entry '-A INPUT -i qvdtap0 -j QVD_11_INPUT'
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 224 - Adding ebtables entry '-A FORWARD -i qvdtap0 -j QVD_11_FORWARD'
2016/02/16 09:46:33 3213 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 302 - Running command ['/sbin/ifconfig','qvdtap0','up']
2016/02/16 09:46:33 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 315 - Process 3529 forked
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 340 - Process 3529 returned rc: 0
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/KVM.pm 305 - No VNC
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/KVM.pm 313 - No monitor port
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/KVM.pm 324 - Using user storage '/var/lib/qvd/storage/homes/11-data.qcow2' (file=/var/lib/qvd/storage/homes/11-data.qcow2,index=1,media=disk,if=virtio) for VM '11'
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 365 - Output for hypervisor on VM 11 is not being redirected
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/KVM.pm 329 - VM lock fd is 9
2016/02/16 09:46:34 3213 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 302 - Running command ['kvm','-m','128','-name','qvd/11/newvm','-net','nic,macaddr=54:52:00:30:36:fe,vlan=0,model=virtio','-net','tap,vlan=0,fd=3','-nographic','-drive','file=/var/lib/qvd/storage/overlays/6-11-overlay.qcow2,index=0,media=disk,if=virtio,boot=on','-drive','file=/var/lib/qvd/storage/homes/11-data.qcow2,index=1,media=disk,if=virtio']
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 315 - Process 3530 forked
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 363 - process 3530 keeps running on the background
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 412 - calling RPC service http://10.48.54.254:3030/vma/ping
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 340 - Process 3530 returned rc: 256
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: 1, ignore_errors: 1, cb: CODE(0x34d3ba8))
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 297 - stopping VMA monitor
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMAMonitor.pm 43 - Stopping VMA monitor
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 518 - aborting RPC call
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 83 - Changing database state to 'stopping' for VM 11
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 217 - No action performed for on_result callback
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from save_state succeeded
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: 0, ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 249 - Retrieving list of ebtables entries for chain 'INPUT'
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 255 - Deleting rule '1. -i qvdtap0 -j QVD_11_INPUT'
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 262 - deleting ebtables chain QVD_11_INPUT
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 249 - Retrieving list of ebtables entries for chain 'FORWARD'
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 255 - Deleting rule '1. -i qvdtap0 -j QVD_11_FORWARD'
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 262 - deleting ebtables chain QVD_11_FORWARD
2016/02/16 09:46:34 3213 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/DHCPDHandler.pm 55 - Unregistering mac '54:52:00:30:36:fe', ip '10.48.54.254' for VM 11 in DHCP
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/DHCPDHandler.pm 64 - Writing DHCP hosts file '/var/run/qvd/dhcp-hostsfile'
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/DHCPDHandler.pm 75 - Sending HUP signal to dhcpd
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 377 - killing 3236 with signal HUP
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 383 - Clearing runtime row for VM '11'
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 217 - No action performed for on_result callback
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 240 - query from clear_runtime_row succeeded
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2016/02/16 09:46:34 3213 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 671 - Releasing handler for VM '11'

thanks in advance

**Comment by vatral** [comment]
Hello, I can see from the log that KVM starts, then immediately exits with an error for some reason. Please try running:

    kvm -m 128 -name qvd/11/newvm -net nic,macaddr=54:52:00:30:36:fe,vlan=0,model=virtio -net tap,vlan=0,fd=3 -nographic -drive file=/var/lib/qvd/storage/overlays/6-11-overlay.qcow2,index=0,media=disk,if=virtio,boot=on -drive file=/var/lib/qvd/storage/homes/11-data.qcow2,index=1,media=disk,if=virtio

as root on the commandline to see what error it's producing.

**Comment by jmg49** [comment]
done => 
Could not access KVM kernel module: No such file or directory
failed to initialize KVM: No such file or directory .....

qvdserver@qvdserver:~$ which qemu
qvdserver@qvdserver:~$ which kvm
/usr/bin/kvm

test the same command with qemu-system-x86_64 
=>
qemu-system-x86_64: -net tap,vlan=0,fd=3: TUNGETIFF ioctl() failed: Inappropriate ioctl for device
TUNSETOFFLOAD ioctl() failed: Inappropriate ioctl for device
qemu-kvm: boot=on|off is deprecated and will be ignored. Future versions will reject this parameter. Please update your scripts.
qemu-system-x86_64: -drive file=/var/lib/qvd/storage/overlays/6-11-overlay.qcow2,index=0,media=disk,if=virtio,boot=on: could not open disk image /var/lib/qvd/storage/overlays/6-11-overlay.qcow2: Could not open '/var/lib/qvd/storage/overlays/6-11-overlay.qcow2': No such file or directory

i don't know why , kvm is not found, 

in order to test .qcow2 files , i have to use qemu-system-x86_64 instead of kvm .....

**Comment by vatral** [comment]
> Could not access KVM kernel module: No such file or directory
> failed to initialize KVM: No such file or directory .....

This indicates the KVM module isn't loaded. KVM needs a kernel module and hardware support. Try as root:

    modprobe kvm

And: 

    modprobe kvm-intel

Or, if using an AMD CPU:

    modprobe kvm-amd

Check dmesg for errors, it won't work if the hardware doesn't support virtualization, or it's not enabled. If the hardware does support virtualization, check the BIOS, as it comes disabled by default on some hardware.

If you don't have virtualization support, you will have to go with LXC instead.

**Comment by jmg49** [comment]
Ok thanks , the server doesn t support hardware virtualization, 
I will change for another one i would prefer stay with kvm,

**Comment by vatral** [comment]
Okay, I am closing this issue, then.
