### ISSUE TITLE
QVD client very slow

### ISSUE THREAD

**Issue by marcoc65** [theqvd/theqvd#36]
HI,
in my company we have 20 PC with qvd.
same pc (8) have problem with client (very very slow)
in this pc  xserver.log say:
winMultiWindowXMsgProc - WM_CHANGE_STATE - IconicState

please help me

Marco

**Comment by narenas** [comment]
Please , could you tell us what is the client version that you are running. 

Also we´ll need to know the version if QVD which you are installing (server) and the one that you are running on the clients. 

Also we´d need to know if you have enabled the printing, the audio and the port forwarding options. 

Regards.

**Comment by marcoc65** [comment]
we have windows client (how can I see the qvd client version?) download
from qvd site last week.
vm lubuntu  14.04
QVD server on ubuntu 14.04 installed few day ago
printing audio disable

same windows configuration (apparently), same qvd client config, same vm
(es vm_pc18)  work well from some windows client and wrong from other. I
think the problem is in windows environment.

this night I make new tests
tell me if  some log is required

Marco


2016-03-01 10:09 GMT+01:00 narenas <notifications@github.com>:

**Comment by salva** [comment]
@marcoc65, were you able to determine the cause of the slowness in the QVD client? Is there anything still we could do to help you?
