### ISSUE TITLE
Vnc Issues

### ISSUE THREAD

**Issue by ryananderson0219** [theqvd/theqvd#38]
This is probably a very basic thing, but I can't get VNC to work for the life of me. The documentation says that it is built in. I have enabled it...I think by using "qa config set vm.vnc.redirect=1" then restarting the server. I'm using KVM. I have a vnc client installed. I keep getting connection refused when I try to use the command line to start it. What am I missing? What other information will be helpful in diagnosing the issue?

Thanks for all the support you have giving me so far! I really appreciate it. Learning so much!

**Comment by jzeaherra** [comment]
Hi,
   Please, have a look at 6.4.13 in the docs:
http://docs.theqvd.com/docs/AdministrationManual.html#_basic_administrative_operations
The vnc system is prepared to be used from the administration tool like this:

# qa vm vnc -f name=myVM

Remember you must have vncviewer installed in the server.

If this doesn't work, you should have a look at the kvm command line options with ps in the server's console. The HKD should be executing kvm with the "-vnc: xxxx" option.

Please, tell me if this helped.

Regards,
Juan

**Comment by ryananderson0219** [comment]
I've been looking through the documents, but I still can't seem to figure out why I can't vnc into my VM. Here is part of the log file (I had attached the whole thing as well):
[qvd.txt](https://github.com/theqvd/theqvd/files/234973/qvd.txt)


2016/04/25 10:03:15 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/KVM.pm 301 - VNC is at display ':-3899'
2016/04/25 10:03:15 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/KVM.pm 313 - No monitor port
2016/04/25 10:03:15 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/KVM.pm 324 - Using user storage '/var/lib/qvd/storage/homes/21-data.qcow2' (file=/var/lib/qvd/storage/homes/21-data.qcow2,index=1,media=disk,if=virtio) for VM '21'
2016/04/25 10:03:15 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 365 - Output for hypervisor on VM 21 is not being redirected
2016/04/25 10:03:15 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/KVM.pm 329 - VM lock fd is 9
2016/04/25 10:03:15 22695 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 302 - Running command ['kvm','-m','3072','-name','qvd/21/UbuntuMate','-net','nic,macaddr=54:52:00:03:0f:fb,vlan=0,model=virtio','-net','tap,vlan=0,fd=3','-vnc',':-3899','-drive','file=/var/lib/qvd/storage/overlays/6-21-overlay.qcow2,index=0,media=disk,if=virtio,boot=on','-drive','file=/var/lib/qvd/storage/homes/21-data.qcow2,index=1,media=disk,if=virtio']
2016/04/25 10:03:15 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 315 - Process 22771 forked
2016/04/25 10:03:15 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 363 - process 22771 keeps running on the background
2016/04/25 10:03:15 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 412 - calling RPC service http://10.3.15.251:3030/vma/ping
2016/04/25 10:03:18 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 453 - bad response status: 595
2016/04/25 10:03:18 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: 1, ignore_errors: <undef>, cb: _on_error)
2016/04/25 10:03:18 22695 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 316 - vma_monitor_failed for vm '21', tries: 1/40
2016/04/25 10:03:28 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 517 - aborting/cleaning delayed method call
2016/04/25 10:03:28 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 412 - calling RPC service http://10.3.15.251:3030/vma/ping
2016/04/25 10:03:28 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 118 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2016/04/25 10:03:28 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 297 - stopping VMA monitor
2016/04/25 10:03:28 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMAMonitor.pm 43 - Stopping VMA monitor
2016/04/25 10:03:28 22695 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 83 - Changing database state to 'running' for VM 21

**Comment by jzeaherra** [comment]
Hi,
  I've been looking into the issue and it seems the vnc command is not working correctly. Thanks for helping us detect this bug.

  In the meanwhile, you can run inside the server:
netstat -apn|grep kvm 

That will give you the list of listening ports for each kvm process so that you can connect to them with any vnc client you want. 

Also, please bear in mind that the vnc option is there just for diagnosing. You won't be able to use the desktop from vnc. QVD is prepared to be used from qvd-client, and there are a series of actions that are only triggered when connecting with it (such as creating the appropriate user inside the vm, starting xserver, etc.. )

Thanks again!
Juan

**Comment by salva** [comment]
@ryananderson0219, were you able to solve this issue regarding connecting to the virtual machines using VNC?
