### ISSUE TITLE
Trying to set up testlab on VirtualBox

### ISSUE THREAD

**Issue by UpsilonB** [theqvd/theqvd#39]
Hi

I am trying to set up a virtual testlab on VirtualBox.
I have created 2 vm's. One vm running th database and another running th QVD server and HKD.

Connection between the two vm's seems to be correct and the apache works to fill the database. I can even use the server node to configure the database. In QVD-WAT everything seems to work correctly.

But...when I try to start the QVD kvm vm demo it does not start. The QVD node states it is running. The QVd vm seems to get an ip assigned in the correct range. But after a few seconds the stae 'starting' blinks and the vm is stopped.

Since I am trying to acheive this in VirtualBox I am using a LXC image, because the KVM image wont work, correct?

Could somebody quide me into configuring LXC the correct way?

Thx!

PS: I am setting up this testlab and the complete configuration to learn more about VDI in general and QVD in specific.

**Comment by jzeaherra** [comment]
Hi,

   As far as I know, nested virtualization is not working yet in Virtual Box, so yes, so should be using lxc in your test lab.

   Please follow this [administration manual topic](http://docs.theqvd.com/docs/AdministrationManual.html#_qvd_base_configuration) on lxc configuration.

Also, are your using one of our demonstration disk images [here](http://theqvd.com/product/download)  or are you creating it on your own?

Regards,
Juan

**Comment by UpsilonB** [comment]
Thanks for the reply. 

Ok, so I was on the right track: I already did the base configuration and downloaded one of the lxc images on the QVD website. I was able to setup the image in the QVD-WAT.

I just don't know where to look for to start debugging. How can I debug or where do I have to look to give you more info so you can help me?

This path doesn't excist path.cgroup.cpu.lxc=/sys/fs/cgroup/cpu/lxc. Maybe that's a clue?

**Comment by jzeaherra** [comment]
That path is not a problem unless the hkd is complaining about it. In that case it wouldn't even start, giving an error in the log. And... about the log, that is the starting point for debugging:
/var/log/qvd/qvd.log

What does the log say when you start the hkd? And when you try to start a vm?

**Comment by UpsilonB** [comment]
There is no error logged when I start/stop/restart the qvd-hkd
This error is logged when I start the vm via QVD-WAT:

2016/05/22 23:26:23 5491 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 110 - Unable to mount unionfs-fuse mix of '/var/lib/qvd/storage/basefs//3-ubuntu-13.04-i386-qvd' (ro) and '/var/lib/qvd/storage/overlayfs/3-4-overlayfs' (rw) into '/var/lib/qvd/storage/rootfs/4-fs'

**Comment by jzeaherra** [comment]
Looks like your problem is unionfs. Try changing to another supported fs like this:

qa config set vm.lxc.unionfs.type=aufs

or 

qa config set vm.lxc.unionfs.type=overlayfs

Restart the hkd and try again.

**Comment by UpsilonB** [comment]
I get the exact same error with overlayfs. But the error mentions overlayfs.

With aufs it takes a long long time starting, but then it says stopping and the image is stopped. No error is logged.

It does write something to the virtual hdd though. (I didn't just run out of disk space did I? :s)


udev                           1013240        8     1013232   1% /dev
tmpfs                           204908      988      203920   1% /run
/dev/mapper/ubuntu--vg-root   23357308 15430336     6717424  70% /
none                                 4        0           4   0% /sys/fs/cgroup
cgmfs                              100        0         100   0% /run/cgmanager/fs
none                              5120        0        5120   0% /run/lock
none                           1024540        0     1024540   0% /run/shm
none                            102400        0      102400   0% /run/user
/dev/sda1                       240972    39595      188936  18% /boot
aufs                          23357308 15430336     6717424  70% /var/lib/qvd/storage/rootfs/4-fs

**Comment by jzeaherra** [comment]
Could you please attach the log from trying to start a vm using aufs?

**Comment by UpsilonB** [comment]
I set the log level to ALL

[log.txt](https://github.com/theqvd/theqvd/files/277711/log.txt)

**Comment by jzeaherra** [comment]
The vm seems to be booting, but the hkd can't contact it. So it finally gives up and stops it.

Looks like a connectivity issue then. As you're using VirtualBox, maybe it is the promiscuous mode in the advanced network settings of your node. By default it is set to 'Deny', and you must set it to 'Allow all' for bridges to work inside.

Am I correct?

**Comment by salva** [comment]
@UpsilonB: were you able to solve your issue?
