### ISSUE TITLE
VM dont start 

### ISSUE THREAD

**Issue by sirishkalidindi** [theqvd/theqvd#41]
Team,

Configured qvd on ubuntu 14.04. Host is running fine but VM is not starting up. Attached the log.

Thanks for help in advance 

Sirish K
[qvdlog.txt](https://github.com/theqvd/theqvd/files/424742/qvdlog.txt)

**Comment by sirishkalidindi** [comment]
Can someone look into this please..

**Comment by jzeaherra** [comment]
Hi Sirish,

Sorry for the delay! Seems like you have trouble with overlayfs and it's probably easier for you to just use aufs instead. You can do that with:
qa config set vm.lxc.unionfs.type=aufs

Then, restart the hkd.

Regards,
Juan
