### ISSUE TITLE
Save password on Windows QVD client?

### ISSUE THREAD

**Issue by BartDG180** [theqvd/theqvd#42]
I asked this question:

>>*We're using QVD at work and it works pretty good. There 's just one thing that annoys me: my ICT  >>service has provided me with a password that\'s impossible to remember. When I use the QVD client  >>on my iPad, I can have it remember the password, which is very  handy. For the Windows client, it >>seems I cannot? Can I enter this password manually somewhere? Maybe in a configuration file or >>something? I've searched the web for a solution to this, but can't find one anywhere since most of the >>docs are about the Linux version.*

>The response was: 
>modify in your home directory the file c:\Users\username\.qvd\client.conf and add 
>client.show.remember_password = 1 
>client.remember_password = 1
>That way you can both choose if your password is being remembered and it will appear enable by default.

Unfortunately, there seems to be no \.qvd\ subdirectory in the c:\users\username folder.  And I have enabled "show hidden files and folders" in the windows explorer.

Somebody any idea?  Thanks!

**Comment by BartDG180** [comment]
Ok, update.  I found the client.conf file, but it's not in the  c:\Users\username\.qvd\ folder, but in the C:\Users\Erlend\AppData\Roaming\QVD folder.

I was able to add the 
client.show.remember_password=1
client.remember_password=1
And now the client indeed shows a checkbox to remember the password.  I can enter the password and check the box and log in.  When I quit the session, the password is still displayed (dotted out), but when I then completely quit QVD and restart the client, the password is gone again.

Any ideas?

**Comment by nitomartinez** [comment]
Please try the following, put the clear password in the client.conf as in:

client.user.password=myclearpassword

**Disclaimer: This is not secure**

**Comment by BartDG180** [comment]
Hi,

I've just tried this, this also doesn't work.
I've tried it with only the line "client.user.password=myclearpassword" added, and also in combination with "client.show.remember_password=1" and "client.remember_password=1".  
I tried some different variations, but nothing seems to work...

Could this be a bug?

**Comment by nitomartinez** [comment]
Hmm,

what version of the client are you using? 

This is mine:
`
ii  perl-qvd-client                                             3.5.0-26038                                                 all          Common perl modules from CPAN for QVD.
`

This seemed to be added in commit:

83d361166a47a6bd65c841547822bb63fde916ee

Please check if you got this change in your client, if not it could be a bug

**Comment by nitomartinez** [comment]
Just checked and the client package in windows

qvd-client-setup-3.5.0-27493.exe

has not this change included.

Two options:

- Copy the source files inside your client
- Use the supported version (with all the latest patches). See the changes from 3.5.0 (I think that was the latest released version in the community edition) here:

https://github.com/theqvd/theqvd/blob/master/Changelog

**Comment by BartDG180** [comment]
I don't know exactly which version number of the client I'm using, I can't see that anywhere on the windows client.  But I can tell you it's the most recent one available on the website.3.5.0.x.

I'm very willing to use a beta version or something. Where can I download that?  Copying source files inside the client would probably also work, but I would have to  be told which files I need to copy where (and where I can find them).  I know my way around computers pretty good, but I'm not a coder.

Thanks!

**Comment by nitomartinez** [comment]
I can't help you with the download version (this is out of my control)

Not sure where the files are in the windows version either, but I would start with:

* Finding the file Frame.pm inside your windows client
* Make a copy
* Substitute it with this https://github.com/theqvd/theqvd/blob/master/ext/QVD-Client/lib/QVD/Client/Frame.pm

Please be aware that is an absolut hack and there might be side effects, if you it brakes, please restore the original file.

**Comment by BartDG180** [comment]
Hi,

I've tried this, but it doesn't work.  The client doesn't start anymore when I replace the file.  On the other hand, I only need to download the file like it is and replace the old file, yes?  I'm asking because the old file is 30kB large, and the new file is 397kB large, which is a lot bigger.  I'm wondering if this is correct or if I should do something else with this file before copying it.

For now, I've copied the old file back and everything works ok again.

Thanks!

**Comment by nitomartinez** [comment]
Doesn't look right (the size I mean)
`
$wget https://raw.githubusercontent.com/theqvd/theqvd/master/ext/QVD-Client/lib/QVD/Client/Frame.pm
$ ls -l Frame.pm 
-rw-rw-r-- 1 user group 43492 oct 12 16:17 Frame.pm
`

**Comment by BartDG180** [comment]
Ok, so I fired up the good old Linux Mint virtualbox image, and pulled that Frame.pm file in with the command you provided above.
Now I got a 43kB file, which seemed a lot more fitting.  
Unfortunately, replacing the original Frame.pm file with this one also doens't do much good: the client doesn't start.  So this sadly doesn't seem to work...

If you've got anything else I can try, I'm more than willing.  Thanks for your help so far!

**Comment by nitomartinez** [comment]
That means that there are other dependencies, that have been incorporated into the file.

Without going through the source code for this specicific case, the only other option, would be to 
go through all the files in the windows client and get the latest version from the source code.

Not sure if that would work but you can always try :-)

Summary of steps:

- Leave the binaries untouched (NX, perl, X server), focus only on the .pl and .pm files (perl modules and scripts)
- Backup all the .pl and .pm files
- Copy the relevant files for the following modules (be aware that this is from the top of my head, not tested):
- https://github.com/theqvd/theqvd/tree/master/ext/QVD-Client
- https://github.com/theqvd/theqvd/tree/master/ext/QVD-Config-Core
- https://github.com/theqvd/theqvd/tree/master/ext/QVD-HTTP
- https://github.com/theqvd/theqvd/tree/master/ext/QVD-HTTPC
- https://github.com/theqvd/theqvd/tree/master/ext/QVD-Log
- https://github.com/theqvd/theqvd/tree/master/ext/QVD-URI

I think with this it should be sufficient...

Not sure when in the windows version is going to be released for the general public next, it is in the new upcoming release which is due soon, but I am not sure if I can give you publicly the dates yet :-P

**Comment by BartDG180** [comment]
Whoa! That seems like a lot of work for something I'm not even sure off will work! :)
I think I'll just wait for the upcoming release.  I'm guessing it can't be all that long anyway since the last release dates from February this year. 

Thanks so very much for your help, much appreciated!!

Cheers!

**Comment by nitomartinez** [comment]
Glad to help.

Will close this issue.
