### ISSUE TITLE
QVD on XenServer?

### ISSUE THREAD

**Issue by ryananderson0219** [theqvd/theqvd#43]
Hello all,

Has anyone successfully installed QVD on XenServer? I get all the pieces running...DB and Node. I Imported the KVM Ubuntu image. It tries to start for a long time, but then it stops. I have attached the log file.

[qvd.txt](https://github.com/theqvd/theqvd/files/576549/qvd.txt)

Thanks for your time!

**Comment by jzeaherra** [comment]
Hi,
    KVM mode won't work con XenServer nodes, given that XenServer doesn't exactly support nested virtualization: https://discussions.citrix.com/topic/379168-nested-hypervisors-in-xenserver-7/
( I'm not a XenServer expert in case you want to investigate further on the issue... I just made a quick search ).

   On the other hand, you could just switch to LXC images. That should work even on virtual nodes.

Regards,
Juan

**Comment by ryananderson0219** [comment]
I think I'm missing something. I'm trying to test this using lxc. When I try to switch to lxc by using these commands:

# qa config set vm.hypervisor=lxc
# qa config set vm.lxc.unionfs.bind.ro=0
# qa config set vm.lxc.unionfs.type=unionfs-fuse
# qa config set command.unionfs-fuse=/usr/bin/unionfs

Then restart the qvd-hdk service, the node goes to a stopped status and won't come back up. If I change back to kvm it will go back to running.

I think the line that is making it stop is this:
2016/11/10 08:02:56 31211 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 389 - /sys/fs/cgroup/cpu/lxc does not lay inside a cgroups file system
2016/11/10 08:02:56 31211 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 168 - GOODBYE!
I can follow the path until /sys/fs/cgroup/cpu/ but lxc is missing.

**Comment by jzeaherra** [comment]
Depending on your distro, it could be your "path.cgroup.cpu.lxc = /sys/fs/cgroup/cpu/lxc" differs from our default value. Look for this path in your system and update this option accordingly before restarting the hkd.
If you don't have any cgroups you should install the appropiate packages: cgroup-lite OR cgmanager usually work, depending on your distro.
