### ISSUE TITLE
It is not possible to read the wat.admin.password from configuration as stated in the documentation

### ISSUE THREAD

**Issue by HenrikBach1** [theqvd/theqvd#49]
Hi,

It is not possible to read the wat.admin.password from configuration as stated in the documentation:

"-------------------
perl -Mperlrc=. -Mlib::glob=*/lib QVD-Admin/bin/qvd-admin.pl config get wat.admin.password
Error: Syntax error: undefined value for key: 'wat.admin.password'
-------------------"

However,

"-------------------
perl -Mperlrc=. -Mlib::glob=*/lib QVD-Admin/bin/qvd-admin.pl config get | grep -i password
client.remember_password=0
client.show.remember_password=0
client.user.password=
database.password=passw0rd
wat.admin.password=admin
-------------------"

does its job...

/Henrik

**Comment by vatral** [comment]
Which part of the documentation are you reading? I don't think there was any part telling the user to "config get wat.admin.password". There is a part asking to "config set wat.admin.password".

Reading an unconfigured setting returns an error, but "config get" without arguments returns all the parameters known, including the unconfigured ones. That does seem confusing and I'll see if we can do something about that.

**Comment by HenrikBach1** [comment]
You are absolutely right, that there is no part asking for that. 

However, I think it is convenient to do precise get/set commands to be sure that I overwrite the correct property. 

Thank you for thinking about what you can do. But, regard it is a nice-to-have feature.
