### ISSUE TITLE
Where has Makefile.PL in QVD-Config-Core gone? 

### ISSUE THREAD

**Issue by HenrikBach1** [theqvd/theqvd#50]
Hi,

Please, explain me, where Makefile.PL in QVD-Config-Core has gone?

I'm able to find it in a previously downloaded zip'ed file, the 7th December, but not in its git directory or a freshly downloaded zip'ed file.

/Henrik

**Comment by vatral** [comment]
Hi,

Did you update the source tree recently? This was a cleanup commit that was made almost a month ago.

Part of the changes it made was removing some redundant build code. Perl had several attempts at making a module build system, and one of them has Makefile.PL and the newer one has Build.PL instead.

The code that was using the newer build system also came with Makefile.PL for backwards compatiblity reasons, but that was removed in that commit. So you just have to use Build.PL instead:

```
perl Build.PL
./Build
sudo ./Build install

```

I see the README needs updating to account for this, sorry for the inconvenience.

**Comment by HenrikBach1** [comment]
Ok. No problem.
