### ISSUE TITLE
Can't open perl script "Build.PL": No such file or directory

### ISSUE THREAD

**Issue by HenrikBach1** [theqvd/theqvd#51]
Hi,

Now (while I'm awaiting answer on https://github.com/theqvd/theqvd/issues/48) I'm trying to test the new build, test and install process (as suggested in https://github.com/theqvd/theqvd/issues/50) in a Vagrant/VirtualBox/Ubuntu 16.04 environment using my own supplemental Makefile configuration.

"----------------
cd QVD-Log && \
perl Build.PL && \
./Build && \
sudo ./Build install && \
touch ../QVD-Log.Installed && \
true
Can't open perl script "Build.PL": No such file or directory
../QVD-Makefile:70: recipe for target 'QVD-Log' failed
make: *** [QVD-Log] Error 2
theqvd/ext# ls -al QVD-Log
total 32
drwxr-xr-x  4 root root 4096 Dec 28 12:26 .
drwxr-xr-x 33 root root 4096 Dec 28 14:36 ..
-rw-r--r--  1 root root  107 Dec 28 12:26 Changes
-rw-r--r--  1 root root  117 Dec 28 12:26 ignore.txt
drwxr-xr-x  3 root root 4096 Dec 28 12:26 lib
-rw-r--r--  1 root root  687 Dec 28 12:26 Makefile.PL
-rw-r--r--  1 root root  684 Dec 28 12:26 README
drwxr-xr-x  2 root root 4096 Dec 28 12:26 t
theqvd/ext# find | grep Makefile.PL
./QVD-ParallelNet/Makefile.PL
./QVD-HTTPC/Makefile.PL
./QVD-L7R-Authenticator-Plugin-TOTP/Makefile.PL
./QVD-Admin/Makefile.PL
./Linux-Proc-Mounts/Makefile.PL
./QVD-DB/Makefile.PL
./QVD-HKD/Makefile.PL
./QVD-L7R-Authenticator-Plugin-Ldap/Makefile.PL
./IO-Socket-Forwarder/Makefile.PL
./QVD-Config/Makefile.PL
./QVD-L7R-Authenticator-Plugin-Auto/Makefile.PL
./QVD-SimpleRPC/Makefile.PL
./QVD-URI/Makefile.PL
./QVD-Log/Makefile.PL
./QVD-HTTPD/Makefile.PL
./QVD-L7R-LoadBalancer/Makefile.PL
./QVD-HTTP/Makefile.PL
./QVD-L7R/Makefile.PL
./QVD-Build-libs/Makefile.PL
./QVD-Node/Makefile.PL
./QVD-StressTester/Makefile.PL
./QVD-VNCProxy/Makefile.PL
./Linux-Proc-Mountinfo/Makefile.PL
root@ubuntu-xenial:/project/theqvd/ext# find | grep Build.PL
./QVD-Admin-Web/Build.PL
./QVD-Client/Build.PL
./QVD-EasyCustomize/Build.PL
./QVD-VMA-SlaveClient/Build.PL
./QVD-Config-Core/Build.PL
./QVD-VMA/Build.PL
./QVD-VMKiller/Build.PL
----------------"

It seems that most of  the modules still is build "the old" way. Should I take that fact into account, too?

/Henrik

**Comment by vatral** [comment]
Yes, that's normal. Our internal build process follows this logic: If there's a Build.PL use that, if not, Makefile.PL.
