### ISSUE TITLE
Should I back track to an older version of Test::Pod::Coverage?

### ISSUE THREAD

**Issue by HenrikBach1** [theqvd/theqvd#52]
Hi,

Should I back track to an older version of Test::Pod::Coverage?:
"-----------------
Building QVD-SimpleRPC from Makefile.PL...
Generating a Unix-style Makefile
Writing Makefile for QVD::SimpleRPC
Writing MYMETA.yml and MYMETA.json
make[1]: Entering directory '/project/theqvd/ext/QVD-SimpleRPC'
cp lib/QVD/SimpleRPC/Server.pm blib/lib/QVD/SimpleRPC/Server.pm
cp lib/QVD/SimpleRPC/Client/Parallel.pm blib/lib/QVD/SimpleRPC/Client/Parallel.pm
cp lib/QVD/SimpleRPC.pm blib/lib/QVD/SimpleRPC.pm
cp lib/QVD/SimpleRPC/Client.pm blib/lib/QVD/SimpleRPC/Client.pm
Manifying 3 pod documents
make[1]: Leaving directory '/project/theqvd/ext/QVD-SimpleRPC'
make[1]: Entering directory '/project/theqvd/ext/QVD-SimpleRPC'
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ....... 1/1 # Testing QVD::SimpleRPC 0.01, Perl 5.022001, /usr/bin/perl
t/00-load.t ....... ok   
t/boilerplate.t ... ok   
t/pod-coverage.t .. skipped: Test::Pod::Coverage 1.08 required for testing POD coverage
t/pod.t ........... 1/4 
Failed test 'POD test for blib/lib/QVD/SimpleRPC/Server.pm'
at /usr/local/share/perl/5.22.1/Test/Pod.pm line 187.
blib/lib/QVD/SimpleRPC/Server.pm (121): '=item' outside of any '=over'
blib/lib/QVD/SimpleRPC/Server.pm (137): You forgot a '=back' before '=head1'
Looks like you failed 1 test of 4.
t/pod.t ........... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 

Test Summary Report
t/boilerplate.t (Wstat: 0 Tests: 3 Failed: 0)
  TODO passed:   1
t/pod.t         (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
Files=4, Tests=8,  1 wallclock secs ( 0.01 usr  0.01 sys +  0.13 cusr  0.01 csys =  0.16 CPU)
Result: FAIL
Failed 1/4 test programs. 1/8 subtests failed.
Makefile:842: recipe for target 'test_dynamic' failed
make[1]: *** [test_dynamic] Error 1
make[1]: Leaving directory '/project/theqvd/ext/QVD-SimpleRPC'
../QVD-Makefile:71: recipe for target 'QVD-SimpleRPC' failed
make: *** [QVD-SimpleRPC] Error 2
root@ubuntu-xenial:/project/theqvd/ext# cpanm Test::Pod::Coverage
--> Working on Test::Pod::Coverage
Fetching http://www.cpan.org/authors/id/N/NE/NEILB/Test-Pod-Coverage-1.10.tar.gz ... OK
Configuring Test-Pod-Coverage-1.10 ... OK
==> Found dependencies: Pod::Coverage
--> Working on Pod::Coverage
Fetching http://www.cpan.org/authors/id/R/RC/RCLAMP/Pod-Coverage-0.23.tar.gz ... OK
-----------------"

/Henrik

**Comment by vatral** [comment]
Hello?

Why backtrack?

POD is the Perl inline documentation format. The pod.t test checks the correctness of the documentation directives (indeed there is a problem currently in that file), and pod-coverage.t checks that every function in the file is documented.

Both tests are completely unrelated to the actual functionality of the product, and really I'd ignore them both for the purpose of getting things running.

Note that when we create a new module we use a script that generates the default directory structure, documentation headings and some very basic tests. This includes documentation tests even in the places where it has little importance. For instance QVD::SimpleRPC is an internal module of ours and generally of no interest to end users, so documenting it thoroughly isn't a huge priority.

I'll take note that there's an issue with the POD syntax in this file, but I'd recommend you ignore this unless you're really concerned with the documentation of the internals of QVD.

**Comment by HenrikBach1** [comment]
Thank you for your answer.
