### ISSUE TITLE
[Solved] 4.0: qvd-wat hanging on spinning wheel on ubuntu 16.04

### ISSUE THREAD

**Issue by smoose-nils** [theqvd/theqvd#56]
After following the quick install for ubuntu for qvd 4.0 philippe the WAT page does not load correctly.

Expected: See the admin interface
Result: Never ending spinning wheel

This is the qvd-wat.log

[Tue Mar 21 12:46:38 2017] [debug] GET "/"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/platform/host-details.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/platform/osf-details.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/qvd-management/config-qvd.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/platform/di-details.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/wat-management/config-wat.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/proto-views.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/platform/vm-spy.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/views/mine.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/wat-management/tenant-details.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/views/default.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/wat-management/tenant-list.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/wat-management/administrator-list.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/wat-management/administrator-details.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/wat-management/role-list.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/wat-management/role-details.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/wat-management/log-list.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/wat-management/log-details.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/wat-management/property.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/login/login.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/home/home.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/help/about.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/help/documentation.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/bb-views/profile/profile.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/websockets/websockets.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/websockets/websockets.vm.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/websockets/websockets.user.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/websockets/websockets.host.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/websockets/websockets.osf.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/websockets/websockets.stats.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/style/style.css"
[Tue Mar 21 12:46:39 2017] [debug] GET "/style/custom_style.css"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery/jquery.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-ui/jquery-ui.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-ui/jquery-ui.min.css"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-datetimepicker/jquery.datetimepicker.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-datetimepicker/jquery.datetimepicker.css"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-tags-input/jquery.tagsinput.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-tags-input/jquery.tagsinput.css"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-cookie/jquery.cookie.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-tablescroll/jquery.tablescroll.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-mbExtruder/mbExtruder.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-mbExtruder/css/mbExtruder.css"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-mbFlipText/jquery.mb.flipText.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-hoverIntent/jquery.hoverIntent.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/waitForImages/jquery.waitforimages.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-qtip/jquery.qtip.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-qtip/imagesloaded.pkg.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jquery-qtip/jquery.qtip.min.css"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/underscore/underscore.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/expanding-textareas/expanding.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/backbone/backbone.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/i18next/i18next-1.7.3.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/asciidoc/asciidoc.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/font-awesome/css/font-awesome.min.css"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/font-awesome-animation/font-awesome-animation.min.css"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/fastclick/fastclick.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/sass.js/sass.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/evol.colorpicker/evol.colorpicker.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/evol.colorpicker/evol.colorpicker.min.css"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jsPDF/jspdf.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/jsPDF/jspdf.plugin.addimage.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/html2canvas/html2canvas4.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/FileSaver/FileSaver.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/chosen/chosen.jquery.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/chosen/chosen.min.css"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/flot/jquery.flot.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/flot/jquery.flot.pie.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/flot/jquery.flot.resize.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/flot/jquery.flot.selection.min.js"
[Tue Mar 21 12:46:39 2017] [debug] GET "/lib/thirds/flot-axislabels/jquery.flot.axislabels.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/thirds/google-fonts/google-fonts.css"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/constants/constants.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/constants/constants-acls.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/constants/constants-qvd-config.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/init.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/start.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-router/router.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/actions/actions.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/util/util.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/binds/binds.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/session/config.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/session/login.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/doc/doc.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/interface/interface.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/interface/interface-messages.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/interface/interface-graphs.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/interface/interface-customize.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/interface/interface-templates.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/interface/interface-live.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/default-role.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/default-administrator.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/default-tenant.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/default-user.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/default-vm.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/default-host.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/default-osf.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/default-di.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/default-log.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/menu.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/documentation-sections.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/settings/acl-groups.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/translations/translations.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/proto-model.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/platform/vm.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/platform/user.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/platform/host.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/platform/osf.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/platform/di.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/wat-management/administrator.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/wat-management/tenant.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/wat-management/role.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/wat-management/log.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/wat-management/property.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-models/wat-management/config_wat.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-collections/proto-collection.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-collections/platform/vms.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-collections/platform/users.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-collections/platform/hosts.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-collections/platform/osfs.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-collections/platform/dis.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-collections/wat-management/administrators.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-collections/wat-management/tenants.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-collections/wat-management/roles.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-collections/wat-management/logs.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-collections/wat-management/properties.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/user-common.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/vm-common.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/host-common.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/osf-common.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/di-common.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/wat-management/administrator-common.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/wat-management/role-common.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/wat-management/administrator-role-common.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/wat-management/tenant-common.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/proto-main.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/proto-list.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/proto-details.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/vm-list.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/user-list.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/host-list.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/osf-list.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/di-list.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/user-details.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/lib/bb-views/platform/vm-details.js"
[Tue Mar 21 12:46:40 2017] [debug] GET "/images/favicon.ico"
[Tue Mar 21 12:46:41 2017] [debug] GET "/templates/common/main.tpl"
[Tue Mar 21 12:46:41 2017] [debug] GET "/templates/common/footer.tpl"
[Tue Mar 21 12:46:41 2017] [debug] GET "/templates/common/menu.tpl"
[Tue Mar 21 12:46:41 2017] [debug] GET "/templates/editor/common.tpl"
[Tue Mar 21 12:46:41 2017] [debug] GET "/templates/editor/common-properties.tpl"
[Tue Mar 21 12:46:41 2017] [debug] GET "/templates/doc/related-links.tpl"
[Tue Mar 21 12:46:41 2017] [debug] GET "/templates/view/customize.tpl"
[Tue Mar 21 12:46:41 2017] [debug] GET "/templates/config/customizer-tool.tpl"
[Tue Mar 21 12:46:41 2017] [debug] GET "/templates/view/customize-form.tpl"
[Tue Mar 21 12:46:41 2017] [debug] GET "/templates/error/refresh.tpl"
[Tue Mar 21 12:46:41 2017] [debug] GET "/templates/error/404.tpl"
[Tue Mar 21 12:46:41 2017] [debug] GET "/config.json"
[Tue Mar 21 12:46:41 2017] [debug] GET "/lib/translations/dictionaries/nl.json"
[Tue Mar 21 12:46:41 2017] [debug] GET "/lib/translations/dictionaries/en.json"
[Tue Mar 21 12:46:41 2017] [debug] Template "not_found.production.html.ep" not found
[Tue Mar 21 12:46:41 2017] [debug] Template "not_found.html.ep" not found
[Tue Mar 21 12:46:41 2017] [debug] Rendering cached template "mojo/not_found.html.ep"
[Tue Mar 21 12:46:41 2017] [debug] 404 Not Found (0.003173s, 315.159/s)
[Tue Mar 21 12:46:41 2017] [debug] GET "/images/logo-header.png"

**Comment by jzeaherra** [comment]
Hi,

  Please have a look at the following section of the general installation guide: 
http://docs.theqvd.com/docs/en/4.0/QVDInstallationGuide.html#_wat

The quick install guides take for granted you're making a local installation. Given your logs, that's not the case, so you have to change the apiURL to your server's ip.

Regards,
Juan

**Comment by smoose-nils** [comment]
Hi Juan,

Thanks for your answer. I've altered the config.json
I was actually trying to access the server by it's DNS-name (pointing to the IP) and not the IP it self. That doesn't work, is that expected behaviour?

Accessing it by IP does work and entering the DNS-name in config.json also works.

**Comment by jzeaherra** [comment]
Yes, the WAT is designed so that it can be installed separated from the API. Given this, and the fact that it's impossible to guess what will be the API endpoint (or endpoints) configured by each sysadmin, we default to localhost, which won't work unless you are accessing locally.

Hope this helps,
Juan
