### ISSUE TITLE
4.0: qvd-gui-client ssl error

### ISSUE THREAD

**Issue by smoose-nils** [theqvd/theqvd#58]
Hi,

I'm getting the following error when connecting to my testsetup:

Unable to connect to qvd.smoose.org:8443: SSL connect attempt failed because of handshake problems error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Proxy.pm line 321 thread 1.

qvd-client.log
2017/03/21 19:44:55 5344 INFO /usr/bin/qvd-client 81 - user_dir: /home/nils/.qvd
2017/03/21 19:44:55 5344 INFO /usr/bin/qvd-client 82 - app_dir: /usr
2017/03/21 19:44:55 5344 INFO /usr/bin/qvd-client 87 - user_certs_dir: /home/nils/.qvd/certs
2017/03/21 19:44:55 5344 INFO /usr/bin/qvd-client 91 - pixmaps_dir: /usr/share/pixmaps
2017/03/21 19:45:10 5344 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Proxy.pm 444 - Connecting to qvd.smoose.org:8443
2017/03/21 19:45:10 5344 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Proxy.pm 279 - SSL option SSL_version set: TLSv1_1:!SSLv3:!SSLv2:!TLSv1
2017/03/21 19:45:10 5344 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Proxy.pm 235 - Can't open /home/nils/.qvd/accepted_certs.json: No such file or directory
2017/03/21 19:45:11 5344 ERROR /usr/bin/qvd-client 95 - Unable to connect to qvd.smoose.org:8443: SSL connect attempt failed because of handshake problems error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Proxy.pm line 321 thread 1.
2017/03/21 19:45:11 5344 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Proxy.pm 324 - Connection error: Unable to connect to qvd.smoose.org:8443: SSL connect attempt failed because of handshake problems error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version at /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/Client/Proxy.pm line 321 thread 1.
2017/03/21 19:47:29 5344 INFO /usr/bin/qvd-client 145 - Exiting

I'm using the autoselfsigned certificate but the error seems to indicate a version mismatch of the protocol being used?

**Comment by jzeaherra** [comment]
Hi,
 Could you please share your linux distro and openssl version for both your server and client?
4.0 enforces by default latest ssl, and yes, it can be troublesome.

**Comment by smoose-nils** [comment]
Sure,

Client:
Ubuntu 16.04.2 (also tried 16.10)
openssl:
  Installed: 1.0.2g-1ubuntu4.6
  Candidate:     1.0.2g-1ubuntu4.6

Server
Ubuntu 16.04.2
root@qvd:~# apt-cache policy openssl
openssl:
  Installed: 1.0.2g-1ubuntu4.6
  Candidate: 1.0.2g-1ubuntu4.6

**Comment by jzeaherra** [comment]
Ok, we have a problem with the Ubuntu package. It has an excessively restrictive default ssl config. While we package it again, please insert the following line in your /home/<user>/.qvd/client.conf file:
client.ssl.options.SSL_version = SSLv23:!SSLv3:!SSLv2:!TLSv1

Thanks for the tip,
Juan

**Comment by smoose-nils** [comment]
Thanks that worked around it.
After regenerating the certificate to meet the qvd client's demands and changing command.version.mount.overlayfs to > 1 in the WAT, I got my testimage is running

By the way, is the preferred way to ask questions (that aren't bugs) about the qvd to raise a new issue here? Or are there other channels for that?

**Comment by jzeaherra** [comment]
This is the correct place :) 
Questions here, will help the community.

Regards,
Juan

**Comment by jzeaherra** [comment]
Also, commercial inquiries can be sent to info@theqvd.com
