### ISSUE TITLE
Can you assist with Virtualbox demo appliance?

### ISSUE THREAD

**Issue by basd925** [theqvd/theqvd#59]
I apologize for making two support requests in a row and will understand if you can't help. My Virtualbox QVD appliance will not authenticate user when I attempt to access from the host computer. (I tried both qvd/qvd and demo/demo).  I do get a certificate and I accept it -- but response is "unable to authenticate user".  The windows qvd client running on another computer seems to see the Virtualbox QVD appliance, because it "rejects" the login -- although there is no certificate to accept.

In the running Virtualbox QVD appliance, I can log in both as qvd/qvd and root.

I can ssh to the Virtualbox QVD appliance from the host computer and from the windows computer on the LAN.  I turned off firewalls for testing.  The VirtualBox QVD appliance reports I have accessed via ssh from 10.0.2.22.  The primary adapter in the QVD appliance reports as 10.0.2.15, but I can't ping it.

I noticed a potential conflict -- the appliance has qvdnet running on 10.0.0.1.  My host runs a VPN on 10.0.0.x where it is assigned as 10.0.0.2.

**Comment by jzeaherra** [comment]
Hi,
    Please ask as many questions as you need. We'll make our best effort to answer everything.

The login for the pre-configured user is:
user: qvd-demo
pass: qvd-demo

You can also access the WAT through https://10.0.2.15:443/ (given the addresses you give us) and login with:
user: superadmin@*
pass: superadmin

There you can manage users and vms as you wish.

The appliance is configured in nat mode by default. Only ssh, qvd and wat ports are redirected from the host. By default you shouldn't be able to ping. Of course, you can make as many changes you want to the appliance.

About your potential conflict, yes you may have problems. From the WAT:
upper-right corner -> management -> config.
left menu -> vm
options:
-  vm.network.gateway 
-  vm.network.ip.start 
-  vm.network.netmask 

You can also do it from the appliance's command line as root user:
http://docs.theqvd.com/docs/en/4.0/QVDInstallationGuide.html#_internal_configuration_parameters_of_qvd

After changing the vm.network parameters, you must change qvdnet address accordingly.
Vm addresses don't change when you alter vm.network either, so you will need to create a new vm for user qvd-demo.

Please tell us if you need further assistance.
Regards,
Juan

**Comment by basd925** [comment]
Works better with the correct login!

:-)

QVD appliance is running on my linux server, accessed from my Win10 laptop -- all went well.

**Comment by basd925** [comment]
On 03/22/2017 01:15 AM, jzeaherra wrote:
> You can also access the WAT through https://10.0.2.15:443/ (given the addresses you give us) ...

I could not access via that URL, but https://192.168.1.100:7443 appears to access the WAT.  (I used
the Virtualbox network device advanced settings to set the host IP address for the port re-direct.)

I get to the WAT page (the title comes up on the browser tab) -- but then all I see is a spinning
gear and no login screen or any text.

I used Linux Firefox and Chrome.  I run a lot of security addons in Firefox that could be a problem,
but not in Chrome.

**Comment by jzeaherra** [comment]
Hi,
   WAT needs to know where the API is listening. The appliance is setup for local nat access, but you can still make it if you tell the WAT how to get to the API:

ssh into the appliance as root and update:
/usr/lib/qvd/wat/config.json:
{
   "apiUrl": "https://192.168.1.100:7443"
}

That should make it.

**Comment by basd925** [comment]
Ok.  I changed the Virtualbox redirect [back] from the LAN and logged in as https://localhost:443.

That worked, thank you.

**Comment by jzeaherra** [comment]
Nice. I'll close this then.

Regards,
Juan
