### ISSUE TITLE
Help with 4.0 - Machine not Starting

### ISSUE THREAD

**Issue by ryananderson0219** [theqvd/theqvd#61]
Hello, I have started from scratch on a fresh install of Ubuntu Server 16.04.02 LTS, I have went through the setup guide and I am able to open the WAT, import a default image (ub16.04-xfce4-lxc.tgz), but the machine will not start up. I looked through the logs, and it says: 

2017/03/27 08:01:38 6374 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 112 - Unable to mount overlayfs mix of '/var/lib/qvd/storage/basefs//10006-ub16.04-xfce4-lxc' (ro) and '/var/lib/qvd/storage/overlayfs/10006-10003-overlayfs' (rw) into '/var/lib/qvd/storage/rootfs/10003-fs'

I thought this may be permissions, so I applied 777 to all the folders, just in case, but that didn't help.

[qvd.txt](https://github.com/theqvd/theqvd/files/872524/qvd.txt)

**Comment by vatral** [comment]
Hello,

Please try running this command in a terminal, as root, and reply with the result:

    mount -t overlayfs -o rw,upperdir=/var/lib/qvd/storage/overlayfs/10005-10001-overlayfs,lowerdir=/var/lib/qvd/storage/basefs//10005-ub16.04-xfce4-lxc overlayfs /var/lib/qvd/storage/rootfs/10001-fs

Thanks.

**Comment by ryananderson0219** [comment]
Here is my results:
mount: mount point /var/lib/qvd/storage/rootfs/10001-fs does not exist

**Comment by vatral** [comment]
Please create the directory and try again

**Comment by ryananderson0219** [comment]
Ok, I added the folder and tried again:
mount: mount point /var/lib/qvd/storage/rootfs/10001-fs does not exist

adminuser@qvdnode01:/var/lib/qvd/storage/rootfs$ mkdir 10001-fs
adminuser@qvdnode01:/var/lib/qvd/storage/rootfs$ sudo mount -t overlayfs -o rw,upperdir=/var/lib/qvd/storage/overlayfs/10005-10001-overlayfs,lowerdir=/var/lib/qvd/storage/basefs//10005-ub16.04-xfce4-lxc overlayfs /var/lib/qvd/storage/rootfs/10001-fs
mount: wrong fs type, bad option, bad superblock on overlayfs,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
adminuser@qvdnode01:/var/lib/qvd/storage/rootfs$

**Comment by vatral** [comment]
Okay, I see now.

In recent Linux distributions the overlayfs filesystem has been renamed to "overlay".

If you are running to QVD-4.0 then it should use the new module name by default. If you are running an older release, then we recommend upgrading to 4.0, as the old versions have the module name hardcoded.

**Comment by ryananderson0219** [comment]
I have QVD 4.0 installed on Ubuntu 16.04.02 LTS. I have included a screenshot of the installed applications I thought might be relevant:

![screenshot from 2017-03-27 09-38-16](https://cloud.githubusercontent.com/assets/10710278/24362052/31b9bef2-12d1-11e7-9f7e-b57329f97d41.png)

**Comment by vatral** [comment]
Wait, my mistake. That fix hasn't been packaged yet and should be in 4.0.1.

I'll get back to you soon on this matter.

**Comment by vatral** [comment]
Okay, if you are in a hurry, here is a provisional fix:

Edit /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/LXC/FS/overlays.pm (you should back it up, just in case). 

Change "overlayfs" to "overlay" on lines 13, 26 and 27 ( modprobe, -t and -o ).

This is of course not ideal, but it should work for testing until we can get a permanent fix released, which will be very soon.

**Comment by ryananderson0219** [comment]
I don't seem to have overlays.pm. I do have overlayfs.pm

adminuser@qvdnode01:/usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler/LXC/FS$ ls
aufs.pm  bind.pm  btrfs.pm  overlayfs.pm  unionfs_fuse.pm

**Comment by vatral** [comment]
Sorry, typo. overlayfs.pm is the right one.

**Comment by ryananderson0219** [comment]
I tried that, and didn't help, even restart the machine. I changed from lxc to kvm (I uploaded the kvm image from the website), and I seem to be getting further, however it is giving me this error:

2017/03/27 13:51:56 2231 WARN /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/VMHandler.pm 321 - vma_monitor_failed for vm '10004', tries: 6/40

Should I switch back and continue troubleshooting lxc? I don't think I really care which one I use, I just want to try to get it functioning.

Thanks,

**Comment by ryananderson0219** [comment]
Not sure everything is correct, I try to see what I missed. Nothing seems to be showing up on this screen either, but when I go in to users or nodes they are there:
![image](https://cloud.githubusercontent.com/assets/10710278/24373107/e99b355e-12f5-11e7-944c-4db27ffe3756.png)

**Comment by ryananderson0219** [comment]
I can't get 4.0 to work on my system. I keep getting the same error. I will reinstall 3.5 for now unless you have any other ideas.

**Comment by vatral** [comment]
Hello,

We're working on your problem. 

After the changes I suggested, did anything work differently? Please send a log.

The warning you're getting is harmless. While a machine is starting, HKD tries to connect to the agent service it should be running. It's expected to fail several times while the machine is booting and bringing services up, and it's only an actual problem if the service never comes up and HKD gives up trying. In such cases, the usual problem is network issues, or for custom made VM images, the lack of the VMA service.

Did the machine fail to come up at all, or did you give up on waiting before it timed out? The first start of a VM can take a while, and subsequent starts will be much faster.

Please send us logs with your KVM setup as well.

Thanks

**Comment by ryananderson0219** [comment]
Not sure what I was doing wrong. I finally got the server up and running using the appliance. It is working great expect for another issue, in which I created another ticket.

Thanks for your help.
