### ISSUE TITLE
Creating VMs from CLI

### ISSUE THREAD

**Issue by ryananderson0219** [theqvd/theqvd#62]
I'm missing something. I'm trying to create a VM from CLI. Here is the code I'm using and the response:

**qvd@qvd4:~$ sudo qa4 vm new name=myvm, user=myuser, osf=myosf
Invalid argument value**

I thought maybe it was the naming of the osf or usernames, so I created new ones just like the name above, but I keep getting this error.

| id    | name         | overlay | user_storage | memory | tenant  | number_of_vms | number_of_dis |
+-------+--------------+---------+--------------+--------+---------+---------------+---------------+
| 10000 | qvd-test-osf |       1 |            0 |    256 | default |             1 |             1 |
| 10001 | 2GB/2GB      |       1 |         2048 |   2048 | default |             4 |             2 |
**| 10002 | myosf        |       1 |         2048 |   2048 | default |             0 |             0 |**

 id    | tenant     | name                     | blocked | number_of_vms | number_of_vms_connected |
+-------+------------+--------------------------+---------+---------------+-------------------------+
**| 10005 | default    | myuser                   |       0 |             0 |                       0 |**
| 10004 | default    | ryan.anderson |       0 |             2 |                       0 |

**Comment by frantracer** [comment]
Hello Ryan,

There is a problem in some calls of the qa4 that do not deal properly with element names, and you should provide its ID instead. In this case you should write:

**qvd@qvd4:~$ sudo qa4 vm new name=myvm, user_id=10005, osf_id=10002**

This is a known issue and we will fix in future releases.

Should you need further information let us know and thanks for your feedback.

**Comment by ryananderson0219** [comment]
Thanks for your response. Got it working with your help. :)
