### ISSUE TITLE
Question about Multi-Node 4.0 Environment

### ISSUE THREAD

**Issue by ryananderson0219** [theqvd/theqvd#63]
I have two nodes, one is running correctly, however I can't seem to get the second one running. Maybe I'm doing this completely wrong (I am assuming that each node must have a separate "qvdnet0" network), but here is my setup (let me know if this is wrong, or if there is a better way):

Node01 (includes the DB, WAT, CLI and API - this is actually the 4.0 appliance):
hostname: qvd4
eth0: 192.168.3.35
qvdnet0: 10.0.0.1
Static Route added (ip add route 10.0.0.2 via 192.168.3.35) - I am able to ping 10.0.0.2 (Node02)

node.conf:
nodename=qvdnode01
database.host=localhost

Node02 (includes CLI and API - wasn't sure if it was necessary or not):
hostname: qvdnode01
eth0: 192.168.3.36
qvdnet0: 10.0.0.2
Static Route added (ip add route 10.0.0.1 via 192.168.3.36) - I am able to ping 10.0.0.1 (Node01)

node.conf:
nodename=qvdnode02
database.host=192.168.3.35

I have verified that the service is running and have restarted it several times, but the WAT will not show as running for qvdnode02. Where can I begin to troubleshoot? I have tried looking at the logs on qvdnode02, but they are empty.

**Comment by ryananderson0219** [comment]
Silly me...I forgot to turn logging to DEBUG. I changed the logging to DEBUG and got the below output. For some reason it isn't connecting to the database I think. I can use this command to connect to the DB: $ psql -U qvd -W -h 192.168.3.35 -d qvd

2017/05/03 20:06:48 7989 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 177 - Signal TERM received
2017/05/03 20:06:48 7989 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 531 - aborting database query
2017/05/03 20:06:48 7989 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 168 - GOODBYE!
2017/05/03 20:06:48 8050 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 93 - Log4perl already initialized, doing nothing
2017/05/03 20:06:48 8051 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 237 - Process ID is 8051
2017/05/03 20:06:48 8051 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 239 - Written to /var/run/qvd/qvd-hkd.pid
2017/05/03 20:06:48 8051 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 186 - Defining die handler
2017/05/03 20:06:48 8051 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Config.pm 56 - Loading configuration from file '/etc/qvd/node.conf'
2017/05/03 20:06:48 8051 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 143 - HKD starting, PID: 8051
2017/05/03 20:06:48 8051 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd.lock
2017/05/03 20:06:48 8051 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 3
2017/05/03 20:06:48 8051 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/05/03 20:06:48 8051 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd-vm.lock
2017/05/03 20:06:48 8051 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 7
2017/05/03 20:06:48 8051 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/05/03 20:06:48 8051 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 283 - Connecting to database
2017/05/03 20:13:19 8051 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 531 - aborting database query
2017/05/03 20:13:19 8051 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 168 - GOODBYE!

**Comment by ryananderson0219** [comment]
Okay, I feel real crazy now. All that was wrong was an extra space after the password. Gets me every time! I was able to get the node up and running now, however I still can't get a VM to start. I keep getting this error: "Unable to signal dnsmasq process"

 And I also want to know if this is the correct setup for a multi-node environment?

**Comment by salva** [comment]
On a multi-node configuration, you need a network shared by all nodes and virtual machines/containers.

This is usually done creating a bridge in every node and then attaching a real interface (i.e. eth1) to that bridge and connecting those interfaces through a switch. 

The IPs registered on the database must be those of the bridges.

For instance, using the network 10.0.0.0/24, assign IP 10.0.0.1 to node1 and 10.0.0.2 to node2. Eth1 in both nodes must be connected through a switch.

On node1 run:

    brctl addbr qvdnet
    ifconfig qvdnet 10.0.0.1 netmask 255.255.255.0 up
    brctl addif qvdnet eth1

And in node2:

    brctl addbr qvdnet
    ifconfig qvdnet 10.0.0.2 netmask 255.255.255.0 up
    brctl addif qvdnet eth1

(note that the IP layer should not be configured on the eth1 interfaces)

Check that you can ping one node from the other at the private QVD address. For instance, from node2:

    ping 10.0.0.1

You have to ensure that all the QVD network parameters are set correctly too, but this is done in the same way as in the mono-node case.

If you want to provide Internet access to the virtual machines, you will also need to setup a router connecting the private qvd network to the Internet. For testing purposes, you can just configure one of the nodes also as the router, adding an iptables rule doing nating and setting the node IP (i.e. 10.0.0.1) as the default gateway in the QVD configuration.

**Comment by ryananderson0219** [comment]
Thanks for the information! I have almost everything working like I want. :) However, when the nodes boot up, "qvdnet" doesn't auto start. I have to input "ifup qvdnet" after it boots for the network to come up. Am I missing something in my network config?

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp

auto qvdnet
iface qvdnet inet static
  pre-up brctl addbr qvdnet
  address 10.0.0.2
  netmask 255.255.255.0
  gateway 10.0.0.254
  dns-nameservers 192.168.3.101 8.8.8.8
  pre-up brctl addif qvdnet eth0

**Comment by salva** [comment]
You are configuring eth0 with its own IP and then also adding it to the bridge, that is wrong. Try removing the entries configuring `eth0` (`auto eth0` and `iface eth0 inet dhcp`).

Anyway, I advice you to follow the Debian documentation about [bridge network connections](https://wiki.debian.org/BridgeNetworkConnections), for instance:

```
auto qvdnet
iface qvdnet inet static
    bridge_ports eth1
        address 10.0.0.1
        broadcast 10.0.0.255
        netmask 255.255.255.0
```

Also, you can not use 10.0.0.254 as the gateway address, as that IP is going to be assigned to some VM. QVD expects nodes and other network elements to use low IPs from the assigned network (for example between 10.0.0.1 and 10.0.0.16), and uses the IPs above for the VMs (the boundary is set using the configuration parameter `vm.network.ip.start`).

**Comment by ryananderson0219** [comment]
Awesome! Thanks a lot. Everything seems to be working great.
