### ISSUE TITLE
WAT Not Actively Updating

### ISSUE THREAD

**Issue by ryananderson0219** [theqvd/theqvd#67]
Hello,

Not sure if this has been asked before, but I couldn't find it. When I install the Appliance, everything works as expected. So I decided I wanted to try to install from scratch. I did that and have mostly everything working, except that when I login to WAT, the first page shows no stats. Also when I start/stop a node the node page in wat doesn't update until I refresh the page. Has anyone seen this? Do you know what I could be missing?

Ubuntu 16.04
QVD 4.0
![wat_ nodepage](https://user-images.githubusercontent.com/10710278/28718365-282d65e6-736b-11e7-907f-4014d85ec7fe.png)
![wat_ page1](https://user-images.githubusercontent.com/10710278/28718366-28311e34-736b-11e7-870e-8ced5509202f.png)

Thanks,
Ryan

**Comment by ryananderson0219** [comment]
I found out what the problem was. My password had an "@" symbol in it. Once I took that out of my password it worked. That strange thing is that the same password worked in the appliance.

**Comment by frantracer** [comment]
Hello Ryan, thanks for reporting these kind of problems. We will try to reproduce this issue and fix it, because you should be able to use a "@" in the password.

**Comment by ryananderson0219** [comment]
Thanks for looking into this. The password in question was my database password. It would connect and thought everything was good until I looked in the qvd-wat.log file and noticed that the host it was trying to connect had part of my password... everything after the @ symbol. That's when I decided to change my password to see if that would resolve it and it did.

**Comment by frantracer** [comment]
Hello Ryan, I think what the problem might be, but could you send the configuration file where you set the password for the database?

**Comment by ryananderson0219** [comment]
I setup two users to the database (to test). It stops working after I change the password in /etc/qvd/api.conf not the /etc/qvd/node.conf. Here is my config file:

[api.txt](https://github.com/theqvd/theqvd/files/1190599/api.txt)

**Comment by frantracer** [comment]
I tried to change both password in node.conf and api.conf and I cannot reproduce this issue. Could you send the error log trace with only a part of the password you saw?

**Comment by ryananderson0219** [comment]
Absolutely, here is my log file:
[qvd-wat.txt](https://github.com/theqvd/theqvd/files/1190703/qvd-wat.txt)

**Comment by frantracer** [comment]
I cannot reproduce this issue. Did you change the api.conf file while the API was running? If you did, try to restart the API with the password you said.

Other problem could be that the api.conf or node.conf is not correct, I mean there are some invalid characters like windows carriage return or similar. Could you send the actual file you are using that reproduce the error? Because the qvd-wat.txt does not contain the same password set in the api.txt file.

But I can ensure you that using @ is not the only reason for that to fail, because I tried several passwords with unusual characters and it is working.
