### ISSUE TITLE
Node is stopped

### ISSUE THREAD

**Issue by rlunardo** [theqvd/theqvd#73]
Hello,
I try for the first time this product.
I have installed THEQVD plattform on Linux Ubuntu  16.04.3.
I have followed all rows of "Quick Install Guide Server Linux Ubuntu"
At the end I can access to QVD/WAT, but I see that node is stopped and I have not way to start it.
I have verified status of all service:
postgresql
qvd-api
qvd-hkd

It are all running
could you help me please?

Thank you in advance

**Comment by frantracer** [comment]
Hello rlunardo,

If the qvd-hkd is running the host status shall be "running", ensure you have the qvd-hkd process running by executing `ps ax | grep qvd-hkd`

Additionally provide us the logs of the qvd-hkd process stored in "/var/log/qvd/qvd.log".

Best regards,
Fran

**Comment by rlunardo** [comment]
Thank you Fran for your answer.
this is the result of command  ps ax | grep qvd-hkd 
19040 pts/0    S+     0:00 grep --color=auto qvd-hkd

Into qvd.log I see only this row:
2017/10/05 10:15:03 5607 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/L7R/LoadBalancer/Plugin/Default.pm 47 - Unable to assign vm to host, there is no host available

I can tell you also that my tests are on a VM running on StackMAX (private CLOUD based on Opennebula). I don't know if if is compatible.

**Comment by frantracer** [comment]
It seems an error on the configuration of QVD, it does not seem it is related with your environment.
Could you provide the information about the node configuration in file "/etc/qvd/node.conf" and the host configuration in QVD by running the command "qa4 host get"?

**Comment by rlunardo** [comment]
Dear Fran, here is information about /etc/qvd/node.inf:
#
# QVD Node Configuration
#

# Name of this node in QVD. Usually the machine's hostname.
nodename=ubuntu1604

# Database connection information.
# database.host: where the QVD database is found
# database.name: the name of the QVD database
# database.user: the user account needed to connect
# database.password: the password needed to connect
database.host =ubuntu1604
database.name =qvddb
database.user =qvd
database.password =passw0rd

path.run = /var/run/qvd
path.log = /var/log/qvd
path.tmp = /var/tmp/qvd

log.filename = /var/log/qvd/qvd.log

wat.admin.login=admin
wat.admin.password=admin

log.level=ERROR

here the result of "qa4 host get":
.-------+------------+---------+-----------+----------+---------+---------+-------------------------.
| id    | name       | blocked | address   | frontend | backend | state   | number_of_vms_connected |
+-------+------------+---------+-----------+----------+---------+---------+-------------------------+
| 10001 | ubuntu1604 |       0 | 10.3.15.1 |        1 |       1 | stopped |                       0 |
'-------+------------+---------+-----------+----------+---------+---------+-------------------------'
Total: 1

I add also the information about /etc/network/interface because in my environment (opennebula) the network is configured as you can see here. There is a contextualizator that set IP config of VM. There is not eth0 but ens3. I have modified qvdnet0 in interface:
auto lo
iface lo inet loopback

auto ens3
iface ens3 inet static
  address 192.168.90.86
  network 192.168.90.0
  netmask 255.255.255.0
  gateway 192.168.90.254

auto qvdnet0
iface qvdnet0 inet static
  pre-up brctl addbr qvdnet0
  pre-up iptables -t nat -A POSTROUTING -o ens3 -j SNAT --to-source 192.168.90.86
  pre-up iptables -t nat -A PREROUTING -d 192.168.90.86 -p tcp --dport 8443 -j DNAT --to-destination 10.3.15.1
  post-down brctl delbr qvdnet0
  address 10.3.15.1
  netmask 255.255.255.0

**Comment by frantracer** [comment]
Set "log.level=DEBUG" in the configuration and run again the hkd process, and write back the log please.

PD: Please reformat the comment to be readable.

**Comment by rlunardo** [comment]
I'm sorry Fran. I have seen too late that comments were enormous ..
Here log after DEBUG set:
2017/10/09 16:00:26 20434 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 93 - Log4perl already initialized, doing nothing
2017/10/09 16:00:26 20436 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 237 - Process ID is 20436
2017/10/09 16:00:26 20436 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 239 - Written to /var/run/qvd/qvd-hkd.pid
2017/10/09 16:00:26 20436 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 186 - Defining die handler
2017/10/09 16:00:26 20436 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Config.pm 56 - Loading configuration from file '/etc/qvd/node.conf'
2017/10/09 16:00:26 20436 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 143 - HKD starting, PID: 20436
2017/10/09 16:00:26 20436 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd.lock
2017/10/09 16:00:26 20436 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 3
2017/10/09 16:00:26 20436 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/10/09 16:00:26 20436 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd-vm.lock
2017/10/09 16:00:26 20436 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 7
2017/10/09 16:00:26 20436 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/10/09 16:00:26 20436 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 283 - Connecting to database

**Comment by frantracer** [comment]
Thanks :)
It seems the connection to the database is not ok:
```
database.host =ubuntu1604
database.name =qvddb
database.user =qvd
database.password =passw0rd
```
The "database.host" should be an IP address, I do not know if "ubuntu1604" can be resolved to a correct IP. Maybe you should try to replace it with "192.168.90.86"

**Comment by rlunardo** [comment]
I have change "database.host" from machine name to 192.168.90.86 and also localhost. But node is always stopped:
2017/10/09 16:21:27 20701 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 93 - Log4perl already initialized, doing nothing
2017/10/09 16:21:27 20702 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 237 - Process ID is 20702
2017/10/09 16:21:27 20702 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 239 - Written to /var/run/qvd/qvd-hkd.pid
2017/10/09 16:21:27 20702 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 186 - Defining die handler
2017/10/09 16:21:27 20702 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Config.pm 56 - Loading configuration from file '/etc/qvd/node.conf'
2017/10/09 16:21:27 20702 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 143 - HKD starting, PID: 20702
2017/10/09 16:21:27 20702 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd.lock
2017/10/09 16:21:27 20702 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 3
2017/10/09 16:21:27 20702 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/10/09 16:21:27 20702 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd-vm.lock
2017/10/09 16:21:27 20702 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 7
2017/10/09 16:21:27 20702 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/10/09 16:21:27 20702 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 283 - Connecting to database
2017/10/09 16:22:47 20702 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 177 - Signal TERM received
2017/10/09 16:22:47 20702 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 531 - aborting database query
2017/10/09 16:22:47 20702 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 168 - GOODBYE!
2017/10/09 16:22:47 20753 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 93 - Log4perl already initialized, doing nothing
2017/10/09 16:22:47 20754 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 237 - Process ID is 20754
2017/10/09 16:22:47 20754 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 239 - Written to /var/run/qvd/qvd-hkd.pid
2017/10/09 16:22:47 20754 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 186 - Defining die handler
2017/10/09 16:22:47 20754 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Config.pm 56 - Loading configuration from file '/etc/qvd/node.conf'
2017/10/09 16:22:47 20754 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 143 - HKD starting, PID: 20754
2017/10/09 16:22:47 20754 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd.lock
2017/10/09 16:22:47 20754 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 3
2017/10/09 16:22:47 20754 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/10/09 16:22:47 20754 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd-vm.lock
2017/10/09 16:22:47 20754 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 7
2017/10/09 16:22:47 20754 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/10/09 16:22:47 20754 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 283 - Connecting to database
2017/10/09 16:24:17 20754 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 177 - Signal TERM received
2017/10/09 16:24:17 20754 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 531 - aborting database query
2017/10/09 16:24:17 20754 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 168 - GOODBYE!
2017/10/09 16:24:18 20801 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 93 - Log4perl already initialized, doing nothing
2017/10/09 16:24:18 20802 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 237 - Process ID is 20802
2017/10/09 16:24:18 20802 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 239 - Written to /var/run/qvd/qvd-hkd.pid
2017/10/09 16:24:18 20802 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 186 - Defining die handler
2017/10/09 16:24:18 20802 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Config.pm 56 - Loading configuration from file '/etc/qvd/node.conf'
2017/10/09 16:24:18 20802 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 143 - HKD starting, PID: 20802
2017/10/09 16:24:18 20802 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd.lock
2017/10/09 16:24:18 20802 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 3
2017/10/09 16:24:18 20802 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/10/09 16:24:18 20802 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd-vm.lock
2017/10/09 16:24:18 20802 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 7
2017/10/09 16:24:18 20802 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/10/09 16:24:18 20802 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 283 - Connecting to database
2017/10/09 16:24:57 20802 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 177 - Signal TERM received
2017/10/09 16:24:57 20802 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 531 - aborting database query
2017/10/09 16:24:57 20802 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 168 - GOODBYE!
2017/10/09 16:24:57 20839 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 93 - Log4perl already initialized, doing nothing
2017/10/09 16:24:57 20840 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 237 - Process ID is 20840
2017/10/09 16:24:57 20840 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 239 - Written to /var/run/qvd/qvd-hkd.pid
2017/10/09 16:24:57 20840 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/App/Daemon.pm 186 - Defining die handler
2017/10/09 16:24:57 20840 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Config.pm 56 - Loading configuration from file '/etc/qvd/node.conf'
2017/10/09 16:24:57 20840 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 143 - HKD starting, PID: 20840
2017/10/09 16:24:57 20840 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd.lock
2017/10/09 16:24:57 20840 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 3
2017/10/09 16:24:57 20840 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/10/09 16:24:57 20840 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 480 - locking /var/run/qvd/hkd-vm.lock
2017/10/09 16:24:57 20840 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 486 - flock file descriptor is 7
2017/10/09 16:24:57 20840 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 120 - invoking callback (failed: , ignore_errors: <undef>, cb: _on_done)
2017/10/09 16:24:57 20840 INFO /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 283 - Connecting to database

**Comment by frantracer** [comment]
As I said I think it is a problem with the credentials to the database. Could you sent the content of "/etc/qvd/api.conf"?

**Comment by rlunardo** [comment]
It seem to be. Here api.conf
database.host=localhost (I check also with 192.168.90.86)
database.name=qvddb
database.user=qvd
database.password=passw0rd
api.user=root
api.group=root
path.api.ssl=/etc/qvd/certs

**Comment by salva** [comment]
@rlunardo: for some reason the HKD is not able to connect to the database using TCP/IP.

Could you check PostgreSQL is listening on TCP port 5432 (for instance, running `netstat -an`)?

Also, could you post the PostgreSQL log, usually at `/var/log/postgresql/postgresql-*-main.log`?

**Comment by rlunardo** [comment]
Hi Salva, today after I have seen this error  in  /var/log/postgresql/postgresql-*-main.log :
2017-10-10 16:07:46 CEST [7528-1] qvd@qvddb FATAL:  password authentication failed for user "qvd"
2017-10-10 16:07:46 CEST [7528-2] qvd@qvddb DETAIL:  Connection matched pg_hba.conf line 95: "host    all             all             ::1/128                 md5"

I have tried to recreate from scratch all the procedure. I'm sure that qvd password is 'passw0rd'. But results it is the same:
netstat -an:
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN
tcp        0      0 192.168.90.96:443       192.168.90.167:6798     ESTABLISHED
tcp        0      0 192.168.90.96:443       192.168.90.167:6739     ESTABLISHED
tcp        0      0 192.168.90.96:443       192.168.90.167:6769     ESTABLISHED
tcp        0      0 127.0.0.1:33274         127.0.0.1:443           TIME_WAIT
tcp        0      0 192.168.90.96:443       192.168.90.167:6794     ESTABLISHED
tcp        0      0 192.168.90.96:443       192.168.90.167:6767     ESTABLISHED
tcp        0    256 192.168.90.96:22        192.168.90.167:6204     ESTABLISHED
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 ::1:5432                :::*                    LISTEN
tcp6       0      0 ::1:5432                ::1:53264               ESTABLISHED
tcp6       0      0 ::1:53338               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:5432                ::1:53332               ESTABLISHED
tcp6       0      0 ::1:5432                ::1:53338               ESTABLISHED
tcp6       0      0 ::1:53352               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:5432                ::1:53266               ESTABLISHED
tcp6       0      0 ::1:53344               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:53332               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:53266               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:53368               ::1:5432                TIME_WAIT
tcp6       0      0 ::1:53342               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:5432                ::1:53272               ESTABLISHED
tcp6       0      0 ::1:5432                ::1:53274               ESTABLISHED
tcp6       0      0 ::1:53384               ::1:5432                TIME_WAIT
tcp6       0      0 ::1:53340               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:53346               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:53274               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:53264               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:5432                ::1:53346               ESTABLISHED
tcp6       0      0 ::1:53272               ::1:5432                ESTABLISHED
tcp6       0      0 ::1:53376               ::1:5432                TIME_WAIT
tcp6       0      0 ::1:5432                ::1:53352               ESTABLISHED
tcp6       0      0 ::1:5432                ::1:53342               ESTABLISHED
tcp6       0      0 ::1:5432                ::1:53340               ESTABLISHED
tcp6       0      0 ::1:53364               ::1:5432                TIME_WAIT
tcp6       0      0 ::1:5432                ::1:53344               ESTABLISHED
tcp6       0      0 ::1:53380               ::1:5432                TIME_WAIT
tcp6       0      0 ::1:53388               ::1:5432                TIME_WAIT
udp6       0      0 ::1:60212               ::1:60212               ESTABLISHED
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ]         DGRAM                    15256    /run/user/0/systemd/notify
unix  2      [ ACC ]     STREAM     LISTENING     15257    /run/user/0/systemd/private
unix  2      [ ACC ]     SEQPACKET  LISTENING     16788    /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     22201    /sys/fs/cgroup/cgmanager/sock
unix  2      [ ACC ]     STREAM     LISTENING     16778    /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     16782    /run/systemd/journal/stdout
unix  7      [ ]         DGRAM                    16783    /run/systemd/journal/socket
unix  2      [ ACC ]     STREAM     LISTENING     16787    /run/systemd/fsck.progress
unix  9      [ ]         DGRAM                    16789    /run/systemd/journal/dev-log
unix  2      [ ACC ]     STREAM     LISTENING     21417    /var/run/postgresql/.s.PGSQL.5432
unix  2      [ ACC ]     STREAM     LISTENING     16795    /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     16798    /run/lvm/lvmpolld.socket
unix  2      [ ]         DGRAM                    16799    /run/systemd/journal/syslog
unix  2      [ ACC ]     STREAM     LISTENING     18597    @ISCSIADM_ABSTRACT_NAMESPACE
unix  2      [ ACC ]     STREAM     LISTENING     11559    /run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     11556    /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     11557    /run/snapd.socket
unix  2      [ ACC ]     STREAM     LISTENING     11558    /run/snapd-snap.socket
unix  2      [ ACC ]     STREAM     LISTENING     11561    /var/run/dbus/system_bus_socket
unix  3      [ ]         DGRAM                    16777    /run/systemd/notify
unix  3      [ ]         STREAM     CONNECTED     18440    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     16284
unix  3      [ ]         STREAM     CONNECTED     12755    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     26720
unix  2      [ ]         DGRAM                    10778
unix  3      [ ]         STREAM     CONNECTED     13855
unix  3      [ ]         STREAM     CONNECTED     26721    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     14915
unix  3      [ ]         STREAM     CONNECTED     17519    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     18508    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     9478     /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     17518
unix  3      [ ]         STREAM     CONNECTED     13422
unix  3      [ ]         STREAM     CONNECTED     16286    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     17418    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     12754    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     12753    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     17452
unix  3      [ ]         STREAM     CONNECTED     13928
unix  3      [ ]         STREAM     CONNECTED     17410
unix  3      [ ]         STREAM     CONNECTED     13919
unix  2      [ ]         DGRAM                    13929
unix  3      [ ]         STREAM     CONNECTED     9809
unix  3      [ ]         STREAM     CONNECTED     17411    /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    11357
unix  3      [ ]         DGRAM                    17292
unix  3      [ ]         DGRAM                    11361
unix  3      [ ]         DGRAM                    17294
unix  2      [ ]         DGRAM                    15252
unix  3      [ ]         STREAM     CONNECTED     11590
unix  3      [ ]         DGRAM                    17293
unix  3      [ ]         STREAM     CONNECTED     9680
unix  3      [ ]         STREAM     CONNECTED     15244    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     13063
unix  3      [ ]         DGRAM                    17295
unix  2      [ ]         DGRAM                    32049
unix  2      [ ]         DGRAM                    18601
unix  3      [ ]         STREAM     CONNECTED     11355
unix  2      [ ]         DGRAM                    13069
unix  3      [ ]         STREAM     CONNECTED     17347    /var/run/dbus/system_bus_socket
unix  3      [ ]         DGRAM                    11362
unix  2      [ ]         DGRAM                    9351
unix  2      [ ]         DGRAM                    18596
unix  2      [ ]         DGRAM                    12897
unix  3      [ ]         STREAM     CONNECTED     9503     /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     14718    /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    17342
unix  3      [ ]         STREAM     CONNECTED     11591
unix  3      [ ]         STREAM     CONNECTED     17348    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     17345
unix  3      [ ]         STREAM     CONNECTED     17346
unix  2      [ ]         DGRAM                    11937
unix  2      [ ]         DGRAM                    17288

I have executed: 'Edit the file /etc/postgresql/9.x/main/pg_hba.conf and add the following line to the beginning:
host qvddb qvd 192.168.0.0/24 md5'
Results into the log file is the same:
cat  /var/log/postgresql/postgresql-*-main.log
2017-10-10 16:04:27 CEST [7169-1] LOG:  database system was shut down at 2017-10-10 16:04:26 CEST
2017-10-10 16:04:27 CEST [7169-2] LOG:  MultiXact member wraparound protections are now enabled
2017-10-10 16:04:27 CEST [7168-1] LOG:  database system is ready to accept connections
2017-10-10 16:04:27 CEST [7173-1] LOG:  autovacuum launcher started
2017-10-10 16:04:28 CEST [7175-1] [unknown]@[unknown] LOG:  incomplete startup packet
2017-10-10 16:06:05 CEST [7168-2] LOG:  received fast shutdown request
2017-10-10 16:06:05 CEST [7168-3] LOG:  aborting any active transactions
2017-10-10 16:06:05 CEST [7173-2] LOG:  autovacuum launcher shutting down
2017-10-10 16:06:05 CEST [7170-1] LOG:  shutting down
2017-10-10 16:06:05 CEST [7170-2] LOG:  database system is shut down
2017-10-10 16:06:07 CEST [7502-1] LOG:  database system was shut down at 2017-10-10 16:06:05 CEST
2017-10-10 16:06:07 CEST [7502-2] LOG:  MultiXact member wraparound protections are now enabled
2017-10-10 16:06:07 CEST [7501-1] LOG:  database system is ready to accept connections
2017-10-10 16:06:07 CEST [7506-1] LOG:  autovacuum launcher started
2017-10-10 16:06:07 CEST [7508-1] [unknown]@[unknown] LOG:  incomplete startup packet
2017-10-10 16:07:46 CEST [7528-1] qvd@qvddb FATAL:  password authentication failed for user "qvd"
2017-10-10 16:07:46 CEST [7528-2] qvd@qvddb DETAIL:  Connection matched pg_hba.conf line 95: "host    all             all             ::1/128                 md5"
2017-10-10 16:07:46 CEST [7529-1] qvd@qvddb FATAL:  password authentication failed for user "qvd"
2017-10-10 16:07:46 CEST [7529-2] qvd@qvddb DETAIL:  Connection matched pg_hba.conf line 95: "host    all             all             ::1/128                 md5"
2017-10-10 16:07:46 CEST [7530-1] qvd@qvddb FATAL:  password authentication failed for user "qvd"

**Comment by salva** [comment]
Well, the log is pretty clear, you are using the wrong password. Ensure you don't have trailing spaces on the configuration file entries where you set it.

Also, try to log manually using `psql` (ensure you request a TCP connection).

**Comment by rlunardo** [comment]
Dear Salva, I have tried to logon manually with IP and localhost. Password is: passw0rd (like config files)
root@ubuntu1604:~# psql -h 192.168.90.86 -d qvddb -U qvd -W
Password for user qvd:
psql (9.5.9)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

qvddb=> \q
root@ubuntu1604:~# psql -h localhost -d qvddb -U qvd -W
Password for user qvd:
psql (9.5.9)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

qvddb=>

It seem that config files: /etc/qvd/node.conf and /etc/qvd/api.conf are not able to send password informatioon to Postgres
I have created several VMs with same results.

**Comment by salva** [comment]
Could you attach here both configuration files?

It is important that you use GitHub file attach feature. Don't use copy&paste!

**Comment by rlunardo** [comment]
Here files requested


[VDI.zip](https://github.com/theqvd/theqvd/files/1375548/VDI.zip)

**Comment by salva** [comment]
There is a trailing space on the password field. Remove it!

**Comment by rlunardo** [comment]
A stupid space ....
Yes, now node is running on all my test VMs.

thank you
Best regards

**Comment by jlopez-daishogroup** [comment]
Hi, I know this thread is closed but my problem is related to this topic.
I am installing QVD in an Ubuntu VirtualBox image.
I am following the steps described in the quick installation guide.
It seems that everything is working, I can do login to the WAT, but the node is stopped, I followed the steps said in this thread but I cant get the node to start.
Should I need to configure LXC to make it work in a virtual machine or following the installation guide should be enough?

Kind regards.
