### ISSUE TITLE
Start VM and client connect

### ISSUE THREAD

**Issue by rlunardo** [theqvd/theqvd#74]
Sorry for the inconvenience.
I would like to propose your VDI platform to our major customer.
The final test will be to create a Microsoft Windows 10 VDI and see how it works.
I have had several installation issues due to a space inserted after password, in the node configuration file. Now solved thanks to you.
I wanted to try the virtual machine.
I've created OS Flavours for Ubuntu and downloaded the image from your site: https://s3.amazonaws.com/QVD_Images/4.0/ub16.04-xfce4-kvm.qcow2.
I've created a new user. I created a new vm.
VM does not start. This is what I find in the /var/log/qvd/qvd.log log:

2017/10/16 20:10:25 1599 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 356 - IP address 10.3.15.1 not configured on node
2017/10/23 09:21:29 2023 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 112 - command (tar x -f /var/lib/qvd/storage/images/10000-ub16.04-xfce4-kvm.qcow2 -C /var/lib/qvd/storage/basefs/untar-2023-1508743289-7579.67682966587 --numeric-owner) failed
2017/10/23 10:26:24 2023 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 112 - command (tar x -f /var/lib/qvd/storage/images/10000-ub16.04-xfce4-kvm.qcow2 -C /var/lib/qvd/storage/basefs/untar-2023-1508747184-2767.49982240581 --numeric-owner) failed
2017/10/23 10:48:50 2023 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 112 - command (tar x -f /var/lib/qvd/storage/images/10000-ub16.04-xfce4-kvm.qcow2 -C /var/lib/qvd/storage/basefs/untar-2023-1508748530-6610.1876533093 --numeric-owner) failed
2017/10/23 10:48:52 28007 FATAL /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/L7R.pm 416 - Unable to start VM 10000
2017/10/23 10:49:04 2023 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 112 - command (tar x -f /var/lib/qvd/storage/images/10000-ub16.04-xfce4-kvm.qcow2 -C /var/lib/qvd/storage/basefs/untar-2023-1508748544-6506.92012715268 --numeric-owner) failed
2017/10/23 10:49:06 28025 FATAL /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/L7R.pm 416 - Unable to start VM 10000
2017/10/23 10:49:35 2023 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 112 - command (tar x -f /var/lib/qvd/storage/images/10000-ub16.04-xfce4-kvm.qcow2 -C /var/lib/qvd/storage/basefs/untar-2023-1508748575-8310.64337379196 --numeric-owner) failed
2017/10/23 10:49:37 28043 FATAL /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/L7R.pm 416 - Unable to start VM 10000
2017/10/23 10:50:10 2023 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 112 - command (tar x -f /var/lib/qvd/storage/images/10000-ub16.04-xfce4-kvm.qcow2 -C /var/lib/qvd/storage/basefs/untar-2023-1508748610-424.005619396866 --numeric-owner) failed
2017/10/23 10:50:12 28061 FATAL /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/L7R.pm 416 - Unable to start VM 10000
2017/10/23 10:51:10 2023 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 112 - command (tar x -f /var/lib/qvd/storage/images/10000-ub16.04-xfce4-kvm.qcow2 -C /var/lib/qvd/storage/basefs/untar-2023-1508748670-4375.46227414803 --numeric-owner) failed
2017/10/23 10:51:12 28080 FATAL /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/L7R.pm 416 - Unable to start VM 10000
2017/10/23 14:40:11 1601 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD.pm 356 - IP address 10.3.15.1 not configured on node
2017/10/23 12:50:44 2016 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 112 - command (tar x -f /var/lib/qvd/storage/images/10000-ub16.04-xfce4-kvm.qcow2 -C /var/lib/qvd/storage/basefs/untar-2016-1508755844-7454.8778081688 --numeric-owner) failed
2017/10/23 12:50:46 2070 FATAL /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/L7R.pm 416 - Unable to start VM 10000
2017/10/23 13:46:39 2016 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 112 - command (tar x -f /var/lib/qvd/storage/images/10001-ub16.04-xfce4-kvm.qcow2 -C /var/lib/qvd/storage/basefs/untar-2016-1508759199-6237.23195619441 --numeric-owner) failed

If I try to connect from my Windows machine with QVD Client, I answer:
socket closed unexpectedly at QVD/HTTPC.pm line 330
Can you help me?

Thank you

**Comment by jzeaherra** [comment]
QVD is preconfigured for using lxc images, but you have uploaded a kvm type, so you've got two options: 
1.- Change the configuration of QVD for using kvm images.
2.- Upload one of the lxc images we provide instead.

I think the second option will be easier for you. Also, lxc delivers the highest desktop density.

**Comment by rlunardo** [comment]
Thanks a lot Jzeaherra.
I have download LXC Ubuntu image.
Now it try to start but stopped with this error:
2017/10/23 14:42:34 2016 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.14.2/QVD/HKD/Agent.pm 112 - Unable to mount overlayfs mix of '/var/lib/qvd/storage/basefs//10002-ub16.04-xfce4-lxc' (ro) and '/var/lib/qvd/storage/overlayfs/10002-10002-overlayfs' (rw) into '/var/lib/qvd/storage/rootfs/10002-fs'

**Comment by jzeaherra** [comment]
You may have some problem with overlayfs. Use unionfs instead:

1.- Inside WAT, select "QVD Config" from "QVD Management" menu at the top.
2.- Select vm from the left.
3.- Look for "vm.lxc.unionfs.type" (do not mistake with vm.lxc.unionfs.overlayfs.module.name)
4.- Replace "overlayfs" with "unionfs_fuse" and save changes.
5.- Restart the HKD in your host and try again.

**Comment by rlunardo** [comment]
Ok, I have replaced its
Now it works and I can also connect by client

Kind Regards
