### ISSUE TITLE
Unable to locate package perl-qvd-hkd on Ubuntu 16.04 Xenial

### ISSUE THREAD

**Issue by dndotnet** [theqvd/theqvd#77]
I followed "qvd-4-0-installation-server-ubuntu"

wget -qO - https://theqvd.com/packages/key/public.key | sudo apt-key add -
echo "deb http://theqvd.com/packages/ubuntu-xenial QVD-4.0-current main" > /etc/apt/sources.list.d/qvd.list
apt-get update
apt-get install perl-qvd-hkd

After Applying the above command I get the following error:-

E: Unable to locate package perl-qvd-hkd

lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

Kindly help me. I'm in Pakistan.

**Comment by vatral** [comment]
Hello,

I have tried this in a VM and everything worked correctly. Maybe there is some kind of network error on your side? Please try:

    apt-get clean
    rm /var/lib/apt/lists/*
    apt-get update
    apt-get install perl-qvd-hkd

Please paste all the output generated from those commands here.

**Comment by dndotnet** [comment]
@vatral 

I have applied the commands you wrote here.. but still getting the same output.

apt install perl-qvd-hkd  

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package perl-qvd-hkd

The internet is working fine on my VM and other links or downloads are working fine except the above.. I try to manually enter the URL "http://theqvd.com/packages/ubuntu-xenial%20QVD-4.0-current%20main".. the output in the web browser is:
Not Found
The requested URL /packages/ubuntu-xenial QVD-4.0-current main was not found on this server.

Apache/2.4.18 (Ubuntu) Server at hulkbuster.qindel.com Port 8080

**Comment by dndotnet** [comment]
@vatral 
Actually the apt-list has not been updating or adding in the system.. might be that doesnt exist or permit or moved.. as I have also try to open the URL in a web browser and the result shows that the link is not actually available... see...

http://theqvd.com/packages/ubuntu-xenial%20QVD-4.0-current%20main

Not Found
The requested URL /packages/ubuntu-xenial QVD-4.0-current main was not found on this server.

Apache/2.4.18 (Ubuntu) Server at hulkbuster.qindel.com Port 8080

**Comment by dndotnet** [comment]
@vatral 

Hello is there any download link for deb file so that I can download and install manually, thanks

**Comment by vatral** [comment]
Hello, let's try this again. Please run these commands:

    rm /var/lib/apt/lists/*
    apt update

Please paste here every single line that's produced.

**Comment by dndotnet** [comment]
@vatral 
Yes.. I have tried these again but still the same error..

apt install perl-qvd-hkd

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package perl-qvd-hkd

**Comment by vatral** [comment]
No, you're not running the right command. Please run:

    rm /var/lib/apt/lists/*
    apt update

And nothing else. Do not install anything yet. I want to see specificially what "apt update" prints to the console.

**Comment by dndotnet** [comment]
@vatral 
Ok, here is the output..

sudo apt update

Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [460 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages [414 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [198 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [7,224 B]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/restricted i386 Packages [7,224 B]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/restricted Translation-en [2,152 B]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [321 kB]
Get:12 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1,201 kB]
Get:13 http://security.ubuntu.com/ubuntu xenial-security/universe i386 Packages [280 kB]
Get:14 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [121 kB]
Get:15 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3,208 B]
Get:16 http://security.ubuntu.com/ubuntu xenial-security/multiverse i386 Packages [3,376 B]
Get:17 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [1,408 B]
Get:18 http://us.archive.ubuntu.com/ubuntu xenial/main i386 Packages [1,196 kB]
Get:19 http://us.archive.ubuntu.com/ubuntu xenial/main Translation-en [568 kB]
Get:20 http://us.archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [8,344 B]
Get:21 http://us.archive.ubuntu.com/ubuntu xenial/restricted i386 Packages [8,684 B]
Get:22 http://us.archive.ubuntu.com/ubuntu xenial/restricted Translation-en [2,908 B]
Get:23 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [7,532 kB]
Get:24 http://us.archive.ubuntu.com/ubuntu xenial/universe i386 Packages [7,512 kB]
Get:25 http://us.archive.ubuntu.com/ubuntu xenial/universe Translation-en [4,354 kB]
Get:26 http://us.archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [144 kB]
Get:27 http://us.archive.ubuntu.com/ubuntu xenial/multiverse i386 Packages [140 kB]
Get:28 http://us.archive.ubuntu.com/ubuntu xenial/multiverse Translation-en [106 kB]
Get:29 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [737 kB]
Get:30 http://us.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [684 kB]
Get:31 http://us.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [306 kB]
Get:32 http://us.archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [7,560 B]
Get:33 http://us.archive.ubuntu.com/ubuntu xenial-updates/restricted i386 Packages [7,524 B]
Get:34 http://us.archive.ubuntu.com/ubuntu xenial-updates/restricted Translation-en [2,272 B]
Get:35 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [593 kB]
Get:36 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [548 kB]
Get:37 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [240 kB]
Get:38 http://us.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.2 kB]
Get:39 http://us.archive.ubuntu.com/ubuntu xenial-updates/multiverse i386 Packages [15.3 kB]
Get:40 http://us.archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8,052 B]
Get:41 http://us.archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [4,836 B]
Get:42 http://us.archive.ubuntu.com/ubuntu xenial-backports/main i386 Packages [4,840 B]
Get:43 http://us.archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [3,220 B]
Get:44 http://us.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [6,624 B]
Get:45 http://us.archive.ubuntu.com/ubuntu xenial-backports/universe i386 Packages [6,616 B]
Get:46 http://us.archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [3,768 B]
Fetched 28.3 MB in 36s (769 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.

**Comment by vatral** [comment]
Well, that does seem to make things quite clear: you do not have the QVD repository enabled.

Do you have a /etc/apt/sources.list.d/qvd.list file, and what is inside it?

**Comment by dndotnet** [comment]
@vatral 

Yes brother I had shared earlier that one reason might be that sources list are not updating on my system.. if its not URL or permission issue.. so with that actually I have concluded the documented Query/commands is not working as it should expected.. http://www.theqvd.com/documentation/qvd-4-0-installation-server-ubuntu
I have tried same commands.. so might be some copy paste issue.. but console didnt show any syntax error.. runs ok but didnt produces the required result in terms of creating qvd.list  or /etc/apt/sources.list.d/qvd.list file...

so the solution for me is that I have added the line "deb http://theqvd.com/packages/ubuntu-xenial QVD-4.0-current main" to directly in "/etc/apt/sources.list"   :)

**Comment by vatral** [comment]
Okay, is everything working now?

**Comment by dndotnet** [comment]
@vatral 
Yes, Thank you

**Comment by vatral** [comment]
Okay, then I am closing this issue.

Please open a new one if you have further issues.
