### ISSUE TITLE
Can't start qvd-api (QVD 4.1)

### ISSUE THREAD

**Issue by dlins** [theqvd/theqvd#79]
Hi folks,

I'm trying to install QVD 4.1 on a Ubuntu 16.04.5 LTS completely up to date but I can't start 
qvd-api service. Can anyone help me? I'm  stuk.

Here's the message I receive from "service qvd-api status" command:

----------------------------------------------------
```
● qvd-api.service - LSB: QVD API Daemon
   Loaded: loaded (/etc/init.d/qvd-api; bad; vendor preset: enabled)
   Active: active (exited) since Tue 2018-10-09 14:44:07 -03; 22min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3875 ExecStop=/etc/init.d/qvd-api stop (code=exited, status=0/SUCCESS)
  Process: 3886 ExecStart=/etc/init.d/qvd-api start (code=exited, status=0/SUCCESS)

Oct 09 14:44:06 Haack systemd[1]: Starting LSB: QVD API Daemon...
Oct 09 14:44:07 Haack qvd-api[3886]: Can't load application from file "/usr/lib/qvd/bin/qvd-api.pl": Can't call method "cmp" on an undefined value at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Date/Manip/Recur.pm li
Oct 09 14:44:07 Haack qvd-api[3886]: Compilation failed in require at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/Config.pm line 10.
Oct 09 14:44:07 Haack qvd-api[3886]: BEGIN failed--compilation aborted at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/Config.pm line 10.
Oct 09 14:44:07 Haack qvd-api[3886]: Compilation failed in require at /usr/lib/qvd/bin/qvd-api.pl line 22.
Oct 09 14:44:07 Haack qvd-api[3886]: BEGIN failed--compilation aborted at /usr/lib/qvd/bin/qvd-api.pl line 22.
Oct 09 14:44:07 Haack qvd-api[3886]: Compilation failed in require at (eval 80) line 1.
Oct 09 14:44:07 Haack systemd[1]: Started LSB: QVD API Daemon.

```
----------------------------------------------------

**Comment by dlins** [comment]
Hi,

reinstalling the server from scratch, I got the same error, but now running the qvd-deploy-db.pl script.
This script had run perfectly well last week. But now throws the erros:

`Can't call method "cmp" on an undefined value at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Date/Manip/Recur.pm line 2225.
Compilation failed in require at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/DB/Translator.pm line 5.
BEGIN failed--compilation aborted at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/DB/Translator.pm line 5.
Compilation failed in require at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/DB.pm line 17.
Compilation failed in require at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/DB/Simple.pm line 6.
BEGIN failed--compilation aborted at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/DB/Simple.pm line 6.
Compilation failed in require at /usr/lib/qvd/bin/qvd-deploy-db.pl line 8.
BEGIN failed--compilation aborted at /usr/lib/qvd/bin/qvd-deploy-db.pl line 8.`

**Comment by jzeaherra** [comment]
Hi Daniel,

 I assume you're installing from our repository, right?
deb http://theqvd.com/packages/ubuntu-xenial QVD-4.1.0 main

Are you following the installation guide? 
http://docs.theqvd.com/docs/en/4.1/QVDInstallationGuide.html

Did you see any errors while installing the packages?

Also, please try this and tell us the result:
1. Run without any args: /usr/lib/qvd/bin/perl
2. In the interactive mode type:
use QVD::Log;<enter>

And:
1. Run again without any args: /usr/lib/qvd/bin/perl
2. In the interactive mode type:
use Log::Log4perl;<enter>

For the two above, tell us if nothing happens (which would mean the modules load fine) or post the error it will print.

**Comment by dlins** [comment]
Hi @jzeaherra,

yes and yes. I'm using  "http://theqvd.com/packages/ubuntu-xenial QVD-4.1.0 main" repo and
I'm following the 4.1/QVDInstalationGuide.html instalation guide.

I got no errors while installing perl-qvd-db and postgresql packages, the only ones necessary
to run `qvd-deploy-db.pl` script.

Nothing happens when I run `use Log::Log4perl;` command (it works!). But I got the following
error message after running `use QVD::Log;` command:

```
# /usr/lib/qvd/bin/perl
use QVD::Log;
Can't call method "cmp" on an undefined value at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Date/Manip/Recur.pm line 2225.
Compilation failed in require at - line 1.
BEGIN failed--compilation aborted at - line 1.
```

Thanks a lot for your support.

**Comment by jzeaherra** [comment]
Could you please send the result of:
dpkg -l | grep -i qvd
?

**Comment by dlins** [comment]
```
# dpkg -l | grep -i qvd
ii  perl-qvd-config                     4.1.0-31657-xenial-e1b9adb9                all          Common perl modules from CPAN for QVD.
ii  perl-qvd-config-core                4.1.0-31657-xenial-e1b9adb9                all          Common perl modules from CPAN for QVD.
ii  perl-qvd-db                         4.1.0-31657-xenial-e1b9adb9                all          Common perl modules from CPAN for QVD.
ii  perl-qvd-log                        4.1.0-31657-xenial-e1b9adb9                all          Common perl modules from CPAN for QVD.
ii  qvd-common-libs                     4.1.0-31657-xenial-e1b9adb9                amd64        Common perl modules from CPAN for qvd.
ii  qvd-perl                            5.26.1-2ubuntu1                            amd64        Perl Package to be used by qvd-libs
```

**Comment by dlins** [comment]
`/usr/lib/qvd/bin/perl -MLog::Dispatch::FileRotate -e1` has no result.

Timezone:
```
# cat /etc/timezone
America/Sao_Paulo
```

Locale:
```
# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by vatral** [comment]
Hello! We've not seen this error before and so far are not having much luck reproducing it. Please try the following:

    /usr/lib/qvd/bin/cpan Carp::Always

Just accept the defaults to any questions.

Run this command:

    /usr/lib/qvd/bin/cpan -MCarp::Always -MQVD::Log -e1

Please paste everything that results from that in an answer. This should help us figure out what is going wrong.

Thanks!

**Comment by dlins** [comment]
```
# /usr/lib/qvd/bin/cpan Carp::Always

CPAN.pm requires configuration, but most of it can be done automatically.
If you answer 'no' below, you will enter an interactive dialog for each
configuration option instead.

Would you like to configure as much as possible automatically? [yes] yes
Fetching with LWP:
http://www.cpan.org/authors/01mailrc.txt.gz
Reading '/home/apoio/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with LWP:
http://www.cpan.org/modules/02packages.details.txt.gz
Reading '/home/apoio/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Mon, 15 Oct 2018 11:54:21 GMT
............................................................................DONE
Fetching with LWP:
http://www.cpan.org/modules/03modlist.data.gz
Reading '/home/apoio/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /home/apoio/.cpan/Metadata
Running install for module 'Carp::Always'
Fetching with LWP:
http://www.cpan.org/authors/id/F/FE/FERREIRA/Carp-Always-0.16.tar.gz
Fetching with LWP:
http://www.cpan.org/authors/id/F/FE/FERREIRA/CHECKSUMS
Checksum for /home/apoio/.cpan/sources/authors/id/F/FE/FERREIRA/Carp-Always-0.16.tar.gz ok
Configuring F/FE/FERREIRA/Carp-Always-0.16.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Carp::Always
Writing MYMETA.yml and MYMETA.json
  FERREIRA/Carp-Always-0.16.tar.gz
  /usr/lib/qvd/bin/perl Makefile.PL -- OK
Running make for F/FE/FERREIRA/Carp-Always-0.16.tar.gz
  FERREIRA/Carp-Always-0.16.tar.gz
  make -- NOT OK
  No such file or directory
```


```
# /usr/lib/qvd/bin/cpan -MCarp::Always -MQVD::Log -e1
Unknown option: e
Unknown option: 1
Nothing to install!
```


```
# /usr/lib/qvd/bin/cpan -MCarp::Always -MQVD::Log
Nothing to install!
```

Thanks again for your help!

**Comment by dlins** [comment]
Hi Vadim,

I created a virtual machine (VirtualBox) that reproduces de error and exported it as an OVA 
appliance. You can download it here: 

https://drive.google.com/file/d/10AseNQuc4vI9xHKLeU7c8pmAxlTdKjxY/view?usp=sharing
User: qvd
Password: qvd

I just installed Ubuntu 16.04 server (default installation + openssh-server) and followed the the
QVDInstalationGuide.pdf (**A Beginner's Guide to QVD 4.1 Installation**) until page 12 - **Installation of the QVD tables**, when I got stuck at the command: qvd-deploy-db.pl.

I hope that helps!
Thanks.

**Comment by vatral** [comment]
Hi! You need some development tools for that to work. Also, I made a small mistake there. Please try:

    apt-get install build-essential
    /usr/lib/qvd/bin/cpan Carp::Always
    /usr/lib/qvd/bin/perl -MCarp::Always -MQVD::Log -e1
    

Thanks!

**Comment by dlins** [comment]
Hi! Here's the output:

```
# /usr/lib/qvd/bin/cpan Carp::Always

CPAN.pm requires configuration, but most of it can be done automatically.
If you answer 'no' below, you will enter an interactive dialog for each
configuration option instead.

Would you like to configure as much as possible automatically? [yes] yes
Fetching with LWP:
http://www.cpan.org/authors/01mailrc.txt.gz
Reading '/home/qvd/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with LWP:
http://www.cpan.org/modules/02packages.details.txt.gz
Reading '/home/qvd/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Tue, 16 Oct 2018 10:54:28 GMT
............................................................................DONE
Fetching with LWP:
http://www.cpan.org/modules/03modlist.data.gz
Reading '/home/qvd/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /home/qvd/.cpan/Metadata
Running install for module 'Carp::Always'
Fetching with LWP:
http://www.cpan.org/authors/id/F/FE/FERREIRA/Carp-Always-0.16.tar.gz
Fetching with LWP:
http://www.cpan.org/authors/id/F/FE/FERREIRA/CHECKSUMS
Checksum for /home/qvd/.cpan/sources/authors/id/F/FE/FERREIRA/Carp-Always-0.16.tar.gz ok
Configuring F/FE/FERREIRA/Carp-Always-0.16.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Carp::Always
Writing MYMETA.yml and MYMETA.json
  FERREIRA/Carp-Always-0.16.tar.gz
  /usr/lib/qvd/bin/perl Makefile.PL -- OK
Running make for F/FE/FERREIRA/Carp-Always-0.16.tar.gz
cp lib/Carp/Always.pm blib/lib/Carp/Always.pm
Manifying 1 pod document
  FERREIRA/Carp-Always-0.16.tar.gz
  /usr/bin/make -- OK
Running make test
PERL_DL_NONLAZY=1 "/usr/lib/qvd/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/001use.t ........... 1/1 # Testing Carp::Always 0.16, Perl 5.026001, /usr/lib/qvd/bin/perl
t/001use.t ........... ok   
t/010simple.t ........ ok    
t/098pod-coverage.t .. skipped: Test::Pod::Coverage 1.04 required for testing POD coverage
t/099pod.t ........... skipped: No Developer Tests for non-developers
All tests successful.
Files=4, Tests=17,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.42 cusr  0.07 csys =  0.52 CPU)
Result: PASS
  FERREIRA/Carp-Always-0.16.tar.gz
  /usr/bin/make test -- OK
Running make install
Manifying 1 pod document
Installing /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Carp/Always.pm
Installing /usr/lib/qvd/man/man3/Carp::Always.3
Appending installation info to /usr/lib/qvd/lib/perl5/5.26.1/x86_64-linux-thread-multi/perllocal.pod
  FERREIRA/Carp-Always-0.16.tar.gz
  /usr/bin/make install  -- OK
```

```
# /usr/lib/qvd/bin/perl -MCarp::Always -MQVD::Log -e1
Can't call method "cmp" on an undefined value at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Date/Manip/Recur.pm line 2225.
	Date::Manip::Recur::_locate_n(Date::Manip::Recur=HASH(0x2704080), "first") called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Date/Manip/Recur.pm line 1021
	Date::Manip::Recur::dates(Date::Manip::Recur=HASH(0x2704080)) called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Date/Manip/DM6.pm line 614
	Date::Manip::DM6::ParseRecur("0:0:0:1*0:0:0", "1 weeks ago", "0:0:0:-6:23:59:59", "4 weeks later") called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Log/Dispatch/FileRotate.pm line 549
	Log::Dispatch::FileRotate::_gen_occurance(Log::Dispatch::FileRotate=HASH(0x2973dc0), "0:0:0:1*0:0:0", 1) called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Log/Dispatch/FileRotate.pm line 634
	Log::Dispatch::FileRotate::_get_next_occurance(Log::Dispatch::FileRotate=HASH(0x2973dc0), "0:0:0:1*0:0:0") called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Log/Dispatch/FileRotate.pm line 196
	Log::Dispatch::FileRotate::setDatePattern(Log::Dispatch::FileRotate=HASH(0x2973dc0), "yyyy-MM-dd") called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Log/Dispatch/FileRotate.pm line 96
	Log::Dispatch::FileRotate::new("Log::Dispatch::FileRotate", "min_level", "debug", "size", 50, "max", 20, "filename", ...) called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Log/Log4perl/Appender.pm line 84
	Log::Log4perl::Appender::new("Log::Log4perl::Appender", "Log::Dispatch::FileRotate", "name", "LOGFILE", "l4p_post_config_subs", ARRAY(0x147e718), "l4p_depends_on", ARRAY(0x15dcad0), ...) called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Log/Log4perl/Config.pm line 413
	Log::Log4perl::Config::create_appender_instance(HASH(0x15dcec0), "LOGFILE", HASH(0x147e6e8), ARRAY(0x147e718), undef) called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Log/Log4perl/Config.pm line 305
	Log::Log4perl::Config::_init("Log::Log4perl::Config", HASH(0x12a42c8)) called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Log/Log4perl/Config.pm line 36
	Log::Log4perl::Config::init("Log::Log4perl::Config", HASH(0x12a42c8)) called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Log/Log4perl.pm line 253
	Log::Log4perl::init(HASH(0x12a42c8)) called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Log/Log4perl.pm line 239
	Log::Log4perl::init_once(HASH(0x12a42c8)) called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/Log.pm line 95
	require QVD/Log.pm called at -e line 0
	main::BEGIN() called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/Log.pm line 0
	eval {...} called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/Log.pm line 0
Compilation failed in require.
 at -e line 0.
	main::BEGIN() called at -e line 0
	eval {...} called at -e line 0
BEGIN failed--compilation aborted.
 at -e line 0.
```

**Comment by vatral** [comment]
Hi, that's exactly what I was looking for, thank you!

I will get back to you as soon as I figure out what's going on.

**Comment by dlins** [comment]
Thanks a lot, Vadim!

**Comment by vatral** [comment]
Hello!

I've tracked down the problem to one of the modules we package. There's a bug report against it that sounds exactly like the problem you're having. Please try this:

    /usr/lib/qvd/bin/cpan Date::Manip

Does this fix the problem for you?


Also, while I can reproduce the problem on your VM, so far I haven't succeeded to do so on a clean one -- it seems likely that there is some sort of configuration change that makes a difference in whether the bug happens or not.

**Comment by dlins** [comment]
It works! 

At the end, the three commands that fixed the problem were:

```
apt-get install build-essential
/usr/lib/qvd/bin/cpan Carp::Always
/usr/lib/qvd/bin/cpan Date::Manip
```

Thank you very much for your help.
Best regards,
Daniel.

**Comment by jlopez-daishogroup** [comment]
Good afternoon, I am having a problem trying to install QVD. I am following the PDF installation documentation and everything go well until i need to execute /usr/lib/qvd/bin/qvd-deploy-db.pl. I get the following error:
`- Checking /usr/lib/qvd/bin/qvd-init-data.dat ...
[OK]
[ERROR] Code 0: OK. Message:
 DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=;host=;connect_timeout=20','',...) failed: FATAL:  role "root" does not exist

Trace begun at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/DBI.pm line 689
DBI::__ANON__(undef, undef) called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/DBI.pm line 746
DBI::connect('DBI', 'dbi:Pg:dbname=;host=;connect_timeout=20', '', '', 'HASH(0x5eeada8)') called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/DBIx/Class/Storage/DBI.pm line 1517
DBIx::Class::Storage::DBI::try {...}  at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Try/Tiny.pm line 102
eval {...} at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Try/Tiny.pm line 93
Try::Tiny::try('CODE(0x62b7a20)', 'Try::Tiny::Catch=REF(0x5f02ed8)') called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/DBIx/Class/Storage/DBI.pm line 1559
DBIx::Class::Storage::DBI::_connect('DBIx::Class::Storage::DBI::Pg=HASH(0x109e7c8)') called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/DBIx/Class/Storage/DBI.pm line 1048
DBIx::Class::Storage::DBI::_populate_dbh('DBIx::Class::Storage::DBI::Pg=HASH(0x109e7c8)') called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/DBIx/Class/Storage/DBI.pm line 947
DBIx::Class::Storage::DBI::ensure_connected('DBIx::Class::Storage::DBI::Pg=HASH(0x109e7c8)') called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/DBIx/Class/Storage/DBI.pm line 1568
DBIx::Class::Storage::DBI::txn_begin('DBIx::Class::Storage::DBI::Pg=HASH(0x109e7c8)') called at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/DBIx/Class/Schema.pm line 687
DBIx::Class::Schema::txn_begin('QVD::DB=HASH(0x109e438)') called at /usr/lib/qvd/bin/qvd-deploy-db.pl line 289
main::try {...}  at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Try/Tiny.pm line 102
eval {...} at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/Try/Tiny.pm line 93
Try::Tiny::try('CODE(0x5bcd420)', 'Try::Tiny::Catch=REF(0x5b47230)') called at /usr/lib/qvd/bin/qvd-deploy-db.pl line 321
 at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/DBIx/Class/Storage.pm line 113. at /usr/lib/qvd/bin/qvd-deploy-db.pl line 289`

I am trying to install in a VirtualBox virtual machine.
Can you help me please?

**Comment by MatMercer** [comment]
@dlins I'm having the same problem in Windows. I can't start QVD Client.
