### ISSUE TITLE
Raptor Issue

### ISSUE THREAD

**Issue by TheBarzFR** [theqvd/theqvd#80]
Hi to all,
I setting up two nodes with qvd ubuntu distro..
I got trouble with WAT, in fat in the two nodes installed with same error: 
"Raptor not found"

Coud you help me ?

**Comment by jzeaherra** [comment]
Hi,
Have you installed qvd-wat package? 
Also, what guide are you following for installing?

Regards,
Juan

**Comment by TheBarzFR** [comment]
Hi, 
Yes i followed the documentation

**Comment by jzeaherra** [comment]
But... what guide are you following? We've got a general installation guide and quick installation.

Could send us the result of this:
`dpkg -l|grep -i qvd`
Both nodes.

**Comment by TheBarzFR** [comment]
ii  perl-qvd-admin4                        4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-api                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-config                        4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-config-core                   4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-db                            4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-hkd                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-http                          4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-httpc                         4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-httpd                         4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r-authenticator-plugin-ldap 4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r-authenticator-plugin-totp 4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r-loadbalancer              4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-log                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-simplerpc                     4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-uri                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-vmproxy                       4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  qvd-admin4-libs                        4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-api-libs                           4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-common-libs                        4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-fuse-unionfs                       0.25build10                                   amd64        FUSE version of UnionFS
ii  qvd-hkd-libs                           4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-liblxc1                            1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools (library)
ii  qvd-lxc                                1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools
ii  qvd-lxc-templates                      1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools (templates)
ii  qvd-perl                               5.26.1-2ubuntu1                               amd64        Perl Package to be used by qvd-libs
ii  qvd-python3-lxc                        1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools (Python 3.x bindings)

**Comment by TheBarzFR** [comment]
same for the other node:
ii  perl-qvd-admin4                        4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-api                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-config                        4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-config-core                   4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-db                            4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-hkd                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-http                          4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-httpc                         4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-httpd                         4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r-authenticator-plugin-ldap 4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r-authenticator-plugin-totp 4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r-loadbalancer              4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-log                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-simplerpc                     4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-uri                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-vmproxy                       4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  qvd-admin4-libs                        4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-api-libs                           4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-common-libs                        4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-fuse-unionfs                       0.25build10                                   amd64        FUSE version of UnionFS
ii  qvd-hkd-libs                           4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-liblxc1                            1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools (library)
ii  qvd-lxc                                1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools
ii  qvd-lxc-templates                      1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools (templates)
ii  qvd-perl                               5.26.1-2ubuntu1                               amd64        Perl Package to be used by qvd-libs
ii  qvd-python3-lxc                        1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools (Python 3.x bindings)

**Comment by jzeaherra** [comment]
Ok,
 So I supposed you didn't read this from my previous questions:
>Have you installed qvd-wat package?

The answer is no. Go ahead, install it and try again.

**Comment by TheBarzFR** [comment]
ok, sorry, i sure to done thats...
thanks

**Comment by jzeaherra** [comment]
Never mind. Don't hesitate to ask any questions, and also, please send us any problems you find in our docs.
Regards,
Juan
