### ISSUE TITLE
WAT: Dented wheel with noends

### ISSUE THREAD

**Issue by TheBarzFR** [theqvd/theqvd#81]
Hi 
I have some troubles with WAT now,
I got the dented wheel turning no end. No other display comes. on two nodes is the same.
Restart don't doing right things.
Could you help me ?

about services: 
qvd-api[4047]: Server available at https://127.0.0.1:443/

qvd-hkd[4080]: given is experimental at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/...
qvd-hkd[4080]: when is experimental at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/A...
qvd-hkd[4080]: when is experimental at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/A...
systemd[1]: Started LSB: Example initscript.

systemd[1]: Started PostgreSQL RDBMS

List all packages installed:

ii  perl-qvd-admin4                        4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-api                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-config                        4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-config-core                   4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-db                            4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-hkd                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-http                          4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-httpc                         4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-httpd                         4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r-authenticator-plugin-ldap 4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r-authenticator-plugin-totp 4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-l7r-loadbalancer              4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-log                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-simplerpc                     4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-uri                           4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  perl-qvd-vmproxy                       4.1.0-31657-xenial-e1b9adb9                   all          Common perl modules from CPAN for QVD.
ii  qvd-admin4-libs                        4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-api-libs                           4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-common-libs                        4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-fuse-unionfs                       0.25build10                                   amd64        FUSE version of UnionFS
ii  qvd-hkd-libs                           4.1.0-31657-xenial-e1b9adb9                   amd64        Common perl modules from CPAN for qvd.
ii  qvd-liblxc1                            1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools (library)
ii  qvd-lxc                                1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools
ii  qvd-lxc-templates                      1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools (templates)
ii  qvd-perl                               5.26.1-2ubuntu1                               amd64        Perl Package to be used by qvd-libs
ii  qvd-python3-lxc                        1.0.6-0ubuntu0.3                              amd64        Linux Containers userspace tools (Python 3.x bindings)
ii  qvd-wat                                4.1.0-xenial-31657-e1b9adb9                   all          QVD Web administration tool

**Comment by jzeaherra** [comment]
Hi,

You need to setup ip here:
/usr/lib/qvd/wat/config.json:
```
{
"apiUrl": "https://<the ip you access from browser>:443"
}
```

wat needs to know where it can find the api (this is this way for the case where api and wat live in different nodes)

**Comment by TheBarzFR** [comment]
Oh Yes,  i seen this note in past. Not written on docs. Ok Thanks
