### ISSUE TITLE
Can't get node running

### ISSUE THREAD

**Issue by jlopez-daishogroup** [theqvd/theqvd#86]
Hi, There is another closed thread related to this but I think it is not the same problem.b
I am installing QVD in an Ubuntu VirtualBox image.
I am following the steps described in the quick installation guide.
It seems that everything is working, I can do login to the WAT, but the node is stopped, I followed the steps said in other similar thread but I can't get the node to start.
Should I need to configure LXC to make it work in a virtual machine or following the installation guide should be enough?

Kind regards

**Comment by womanderful** [comment]
Hi,
For starters can you please provide the following infos as per the other thread?
- ps ax | grep qvd-hkd
- cat /etc/qvd/node.conf (beware the password!)
- qa4 host get

**Comment by jlopez-daishogroup** [comment]
Thank you very much for your answer. Here you are the information:
- ps ax | grep qvd-hkd
4267 pts/5    S+     0:00 grep --color=auto qvd-hkd
- cat /etc/qvd/node.conf
nodename=default
database.host=localhost
database.name=qvddb
database.user=qvd
database.password=******
log.level=DEBUG
- qa4 host get
.-------+-------+---------+-----------+----------+---------+---------+-------------------------.
| id    | name  | blocked | address   | frontend | backend | state   | number_of_vms_connected |
+-------+-------+---------+-----------+----------+---------+---------+-------------------------+
| 10000 | node1 |       0 | 10.3.15.1 |        1 |       1 | stopped |                       0 |
'-------+-------+---------+-----------+----------+---------+---------+-------------------------'
Total: 1

Kind regards

**Comment by womanderful** [comment]
So the HKD is not running hence the node is down. Can you please edit the host entry in the database and change "node1" into your actual hostname, then try to start the HKD again? If that doesn't work, we'll have to go the DEBUG and qvd.log route.

**Comment by womanderful** [comment]
Oh and please edit the node.conf too to reflect the same change.
nodename=(your hostname here)

**Comment by jlopez-daishogroup** [comment]
Thank you very much for your help.
The node is already running, but now I am trying to start a VM, I can see a message saying that the request has been sent ok but I dont know how to access to the VM desktop, it seems the vm is stopped. I have created a disk image using the suse cow2 file.
Is that ok?

**Comment by womanderful** [comment]
The first thing to check would be the hypervisor. qcow2 images require you to use the "kvm" hypervisor rather than "lxc".

**Comment by womanderful** [comment]
On second thought, kvm is not going to work under virtualbox. Do leave the hypervisor as "lxc" and use an lxc image instead of a qcow2 one.

**Comment by jlopez-daishogroup** [comment]
Hi, thank you very much. I am going to try with LXC.
I will use the administration manual.
I will keep you updated.

Kind regards.

**Comment by jlopez-daishogroup** [comment]
I am having a problem.
I have executed the commands to set up LXC.
I created a flavour, I added the ubuntu LXC DI and create a VM.
I tried to start the VM and the status changed to starting, but finally, it did nothing.
I changed the flavour memory to 1024 and restarted the machine.
NOw when I try to start the VM it does nothing...Did I do something wrong restarting the machine?

**Comment by jlopez-daishogroup** [comment]
That was a disk space problem.
Now when try to start the VM it tries, but finally does not get the running status.
I guess something fails, these are last lines log the log file:
`2019/07/23 16:14:40 3798 WARN /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/Agent.pm 342 - Process 4044 returned rc: 32256, it probably means that the binary was not found
2019/07/23 16:14:40 3798 ERROR /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/Agent.pm 112 - Unable to mount unionfs-fuse mix of '/var/lib/qvd/storage/basefs//10002-ub16.04-xfce4-lxc' (ro) and '/var/lib/qvd/storage/overlayfs/10002-10007-overlayfs' (rw) into '/var/lib/qvd/storage/rootfs/10007-fs'
2019/07/23 16:14:40 3798 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/Agent.pm 120 - invoking callback (failed: 1, ignore_errors: <undef>, cb: _on_error)
2019/07/23 16:14:40 3798 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/VMHandler/LXC.pm 561 - Unmounting filesystems under '/var/lib/qvd/storage/rootfs/10007-fs'
2019/07/23 16:14:40 3798 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/VMHandler/LXC.pm 580 - No filesystem mounted at '/var/lib/qvd/storage/rootfs/10007-fs' found
2019/07/23 16:14:40 3798 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/VMHandler.pm 393 - Clearing runtime row for VM '10007'
2019/07/23 16:14:40 3798 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/Agent.pm 219 - No action performed for on_result callback
2019/07/23 16:14:40 3798 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/Agent.pm 242 - query from clear_runtime_row succeeded
2019/07/23 16:14:40 3798 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD/Agent.pm 120 - invoking callback (failed: <undef>, ignore_errors: <undef>, cb: _on_done)
2019/07/23 16:14:40 3798 DEBUG /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HKD.pm 690 - Releasing handler for VM '10007'`

**Comment by jlopez-daishogroup** [comment]
Using the GUI Cli, I got the following error (after accepting certificate errors):
`socket closed unexpectedly:  () at /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/HTTPC.pm line 369.`
I can see in the WAT that the VM is trying to start, but finally, it can't start.

**Comment by jlopez-daishogroup** [comment]
Good morning, I had a problem in the LXC configuration. Now everything is working.
I have one last question: The GUI client, which port is connecting to?
Thank you very much for your help and support.

**Comment by womanderful** [comment]
8443.
