### ISSUE TITLE
Moving QVD

### ISSUE THREAD

**Issue by hbdtech** [theqvd/theqvd#87]
Trying to move my current QVD install into a virtual environment.  All looks good so far and I've copied an image from the staging dir of the old server into the new server.  Created the OSF, DI, and Virtial Machine along with a user.  However when I try to start the VM nothing happens.  Would really like to keep the vm as it was built on the old server if possible.  I've attached the qvd.log file.  Thanks

[qvd.log](https://github.com/theqvd/theqvd/files/3644778/qvd.log)

**Comment by womanderful** [comment]
Hi,

You seem to be using a KVM image ("10001-qvd5.img") but your QVD installation is configured to use LXC images. You can fix this issue by configuring QVD to use KVM images, however the VM may still not boot because you'd end up trying to run a VM within a VM, and nested virtualisation has its own set of caveats.

It's worth a try but don't hold your breath.

**Comment by hbdtech** [comment]
To see if I can get this working I've downloaded the pre-built LXC image provided.  Created the OSF, etc. but still no start.  I'm running out of breath.  Attached qvd.log.

Thanks
[qvd.log](https://github.com/theqvd/theqvd/files/3648917/qvd.log)

**Comment by womanderful** [comment]
The error "it probably means that the binary was not found" in line 55 of the log you attached means that you don't seem to have /usr/bin/unionfs available. You may need to install unionfs.

**Comment by hbdtech** [comment]
Ok thanks that got the vm started.  Now I can't connect with client, I'm getting an SSL error.  In the qvd.log I'm seeing FATAL /usr/lib/qvd/lib/perl5/site_perl/5.26.1/QVD/L7R.pm 45 - SSL key file '/var/run/qvd/l7r/ssl/key.pem' isn't readable.  I read another issue here having the same issue and I've gone through the SSL setup in the guide multiple times without any luck.  Thank you for your help with this.

**Comment by hbdtech** [comment]
Anybody have an idea for the SSL error?
