### ISSUE TITLE
Supported Ubuntu OS Roadmap

### ISSUE THREAD

**Issue by ryananderson0219** [theqvd/theqvd#89]
Hello,

I see that currently, the officially supported Ubuntu OS is 16.04. Do you know when 18.04+ will be supported? I've tried in the past, but had dependency issues so I reinstalled with 16.04.

Thanks,
Ryan

**Comment by vatral** [comment]
Hello,

18.04 is on our roadmap and we've made considerable progress towards it. I can't give an exact release date right now, but it's on our list of things to do as soon as possible.

**Comment by ryananderson0219** [comment]
Thanks for the information!
