### ISSUE TITLE
Let's Encrypt Certificate

### ISSUE THREAD

**Issue by ryananderson0219** [theqvd/theqvd#90]
Hello QVD Team,
I'm trying to integrate a Let's Encrypt Certificate into QVD. I have the admin website showing up correctly without any issues in Firefox, but curl seems to be having issues trusting the certificate. Also when I try: qa4 admin get, I get this error: SSL connect attempt failed error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

I copied the certificates from /etc/letsencrypt/live/qvdnode01.rylees.net to /etc/qvd/certs and renamed them to cert.pem and key.pem. 

I changed /etc/qvd/qa.conf to this:
qa.url = https://localhost:443/
qa.tenant = *
qa.login = superadmin
qa.password = superadmin
qa.format = TABLE
qa.ca = /etc/qvd/certs

Curl Testing:
[ryan.anderson@localhost ~]$ curl -vs https://qvdnode01.rylees.net:443
*   Trying 192.168.2.36:443...
* TCP_NODELAY set
* Connected to qvdnode01.rylees.net (192.168.2.36) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0

What other information is needed to help troubleshoot or what am I missing?

Thanks,
Ryan

**Comment by vatral** [comment]
Hello, please try:

    openssl s_client -connect https://qvdnode01.rylees.net:443

That will dump a lot more info. But my guess is that your system isn't recognizing Let's Encrypt's CA. You probably need to use fullchain.pem for your certificates. 

See https://letsencrypt.org/certificates/ for an illustration of how Let's Encrypt is set up.
