### ISSUE TITLE
VMA for Ubuntu Focal

### ISSUE THREAD

**Issue by savyovinicius** [theqvd/theqvd#93]
Hello!

Looking for the QVD guides, I could see the disk image creation tutorials only up to Ubuntu 18.04.
I have also tried to add the QVD repo for Ubuntu Focal, but it still have just a few packages.

Do you have any plans to update it to allow creating disk images with Ubuntu 20.04?

**Comment by vatral** [comment]
Hello!

Yes, we're going to publish those as soon as we're done with a bit of internal maintenance, which should be in just a few days. I'll update you as soon as we have the packages uploaded.

**Comment by savyovinicius** [comment]
Great!

Thanks for the response.
By the way, is the VMA released for other distros?
Saw in the project page you have tutorials for Ubuntu and SLES, and also an image for CentOS.
Where can I find a list of the other repos?

**Comment by vatral** [comment]
Hello, sorry for the delay. Packages for Ubuntu 20.04 have been released, and we also have a ready disk image for download:

https://www.theqvd.com/download/disk-images
